Repository coder/coder, pull requests merged in 2022-10, with the labels that each got.

#4342 add: deployment annotations
  helm/templates/coder.yaml
  helm/values.yaml
Labels: feature

#4176 Add AWS and Azure quickstarts
  docs/images/quickstart/aws/aws1.png
  docs/images/quickstart/aws/aws10.png
  docs/images/quickstart/aws/aws11.png
  docs/images/quickstart/aws/aws2.png
  docs/images/quickstart/aws/aws3.png
  docs/images/quickstart/aws/aws4.png
  docs/images/quickstart/aws/aws5.png
  docs/images/quickstart/aws/aws6.png
  docs/images/quickstart/aws/aws7.png
  docs/images/quickstart/aws/aws8.png
  docs/images/quickstart/aws/aws9.png
  docs/images/quickstart/azure/azure1.jpg
  docs/images/quickstart/azure/azure10.png
  docs/images/quickstart/azure/azure2.png
  docs/images/quickstart/azure/azure3.png
  docs/images/quickstart/azure/azure4.png
  docs/images/quickstart/azure/azure5.png
  docs/images/quickstart/azure/azure6.png
  docs/images/quickstart/azure/azure7.png
  docs/images/quickstart/azure/azure8.png
  docs/images/quickstart/azure/azure9.png
  docs/manifest.json
  docs/quickstart/aws.md
  docs/quickstart/azure.md
Labels: docs

#4448 fix: Check if the response body is nil before panicing
  codersdk/provisionerdaemons.go
Labels: blocking

#4471 fix: example pvc volume binding mode
  examples/templates/kubernetes/main.tf
Labels: chore

#4610 fix: install index 404
  docs/install/index.md
Labels: bug

#4611 docs: add postgres version requirement
  README.md
  docs/admin/configure.md
  docs/install/binary.md
  docs/install/docker.md
Labels: docs

#4640 helm: add sa annotations
  helm/templates/coder.yaml
  helm/values.yaml
Labels: feature

#4526 add: helm binary download cmd
  docs/install/kubernetes.md
Labels: docs

#4348 feat: adding gcp quickstart
  docs/images/google-cloud.svg
  docs/images/quickstart/google-cloud-platform/gcp0.png
  docs/images/quickstart/google-cloud-platform/gcp1.png
  docs/images/quickstart/google-cloud-platform/gcp2.png
  docs/images/quickstart/google-cloud-platform/gcp3.png
  docs/images/quickstart/google-cloud-platform/gcp4.png
  docs/images/quickstart/google-cloud-platform/gcp5.png
  docs/images/quickstart/google-cloud-platform/gcp6.png
  docs/images/quickstart/google-cloud-platform/gcp7.png
  docs/images/quickstart/google-cloud-platform/gcp8.png
  docs/manifest.json
  docs/quickstart/google-cloud-platform.md
Labels: docs

#4681 helm: fix coder resource ref
  helm/templates/coder.yaml
Labels: bug

#4700 helm: add imagePullSecret for air-gapped cust's
  helm/templates/coder.yaml
  helm/values.yaml
Labels: feature

#4728 docs: add auto-start/stop
  docs/images/auto-start.png
  docs/images/auto-stop.png
  docs/images/schedule.png
  docs/workspaces.md
Labels: docs

#4778 site: fix networking docs link
  site/src/pages/DeploySettingsPage/NetworkSettingsPage.tsx
Labels: bug, site
