Repository coder/coder, pull requests merged in 2022-12, with the labels that each got.

#4641 helm: add certs secret mount
  helm/templates/NOTES.txt
  helm/templates/_helpers.tpl
  helm/values.yaml
Labels: stale, enhancement

#5157 docs: add offical kubernetes provider runtime_class_name
  docs/templates/docker-in-docker.md
Labels: docs, stale

#5467 fix: fix security vulnerabilities reported by CodeQL
  agent/ports_supported.go
  cli/clitest/clitest.go
  cli/server.go
  coderd/gitauth/oauth.go
  coderd/workspaceagents.go
  codersdk/agentconn.go
  provisionersdk/archive.go
  site/site.go
Labels: security
