Repository coder/coder, pull requests merged in 2022-06, with the labels that each got.

#1934 fix: add all regions to aws examples
  examples/templates/aws-linux/main.tf
  examples/templates/aws-windows/main.tf
Labels: terraform

#2140 docs: slim down readme
  README.md
  docs/about.md
  docs/index.md
  docs/quickstart.md
Labels: documentation

#2282 fix: coderd: decouple ttl and deadline
  cli/bump.go
  cli/constants.go
  cli/list.go
  cli/ttl.go
  cli/ttl_test.go
  coderd/autobuild/executor/lifecycle_executor.go
  coderd/autobuild/executor/lifecycle_executor_test.go
  coderd/workspaces.go
  coderd/workspaces_test.go
  site/src/components/WorkspaceSchedule/WorkspaceSchedule.tsx
  site/src/components/WorkspaceScheduleForm/WorkspaceScheduleForm.stories.tsx
  site/src/components/WorkspaceScheduleForm/WorkspaceScheduleForm.test.ts
  site/src/components/WorkspaceScheduleForm/WorkspaceScheduleForm.tsx
  site/src/pages/WorkspaceSchedulePage/WorkspaceSchedulePage.tsx
Labels: Community MVP

#2472 fix: cli: create: use new autostart format, opt-in by default
  cli/create.go
  cli/create_test.go
Labels: CLI, go

#2565 init: oauth docs
  docs/install/oauth.md
  docs/install/postgres.md
  docs/manifest.json
Labels: docs
