Repository coder/coder, pull requests merged in 2022-11, with the labels that each got.

#4888 docs: fix DB URL
  docs/install/kubernetes.md
Labels: bug, docs

#4763 helm: add affinity, nodeSelectors, tolerations
  helm/templates/coder.yaml
  helm/values.yaml
Labels: stale, feature

#5026 docs: deprecate name arg
  docs/ides/web-ides.md
  docs/networking/port-forwarding.md
Labels: bug, chore

#5053 feat(windows): default to PowerShell v7 over v6 and fallback to cmd.exe
  agent/usershell/usershell_windows.go
Labels: enhancement
