Repository coder/coder, pull requests merged in 2022-09, with the labels that each got.

#3690 site: correct documentation on gitsshkey
  site/src/pages/UserSettingsPage/SSHKeysPage/SSHKeysPage.tsx
Labels: stale

#3915 add: ECS example template
  examples/templates/ecs-container/README.md
  examples/templates/ecs-container/main.tf
Labels: feature

#3859 chore: separate install docs
  README.md
  coder.env
  docs/admin/auth.md
  docs/admin/configure.md
  docs/admin/index.md
  docs/admin/upgrade.md
  docs/admin/users.md
  docs/install.md
  docs/install/binary.md
  docs/install/docker.md
  docs/install/index.md
  docs/install/install.sh.md
  docs/install/kubernetes.md
  docs/install/packages.md
  docs/manifest.json
  docs/quickstart.md
  docs/quickstart/docker.md
  helm/README.md
Labels: docs

#3986 docs: add jsjoeio/coder-templates to community
  examples/templates/community-templates.md
Labels: docs

#3968 docs(contributing): add macos homebrew commands
  docs/CONTRIBUTING.md
Labels: docs

#4029 Delete template docs
  docs/images/delete-template.png
  docs/templates.md
Labels: docs

#3970 docs(contributing): enable contribution via devcontainer
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
Labels: docs

#4068 chore: rename AWS ECS template & fix docker template var
  examples/templates/aws-ecs-container/README.md
  examples/templates/aws-ecs-container/main.tf
  examples/templates/docker-with-dotfiles/main.tf
Labels: bug

#4240 feat: `coder ls` should show possible columns to filter by
  cli/cliui/table.go
  cli/list.go
Labels: cli
