Repository coder/coder, pull requests merged in 2022-08, with the labels that each got.

#3332 replace inline svgs with svg icon_path
  docs/images/icons/art-pad.svg
  docs/images/icons/contributing.svg
  docs/images/icons/docker.svg
  docs/images/icons/generic.svg
  docs/images/icons/home.svg
  docs/images/icons/layers.svg
  docs/images/icons/picture.svg
  docs/images/icons/protractor.svg
  docs/images/icons/secrets.svg
  docs/images/icons/star.svg
  docs/images/icons/terminal.svg
  docs/images/icons/users.svg
  docs/images/icons/wrench.svg
  docs/manifest.json
Labels: enhancement

#3161 fix: Ensure terraform tests have a cache path and logger
  provisioner/terraform/executor.go
  provisioner/terraform/parse_test.go
  provisioner/terraform/provision_test.go
  provisioner/terraform/serve.go
Labels: stale

#3439 docs: add upgrade page & update getting started
  docs/install.md
  docs/install/configure.md
  docs/install/upgrade.md
  docs/manifest.json
  docs/quickstart/generic.md
  docs/templates.md
Labels: docs

#3564 fix: quickstart 404
  docs/quickstart.md
Labels: bug, docs

#3618 fix: tooltip 404
  site/src/components/SSHButton/SSHButton.tsx
Labels: bug

#3619 chore: k8s example persistence & coder images
  examples/templates/kubernetes-multi-service/main.tf
  examples/templates/kubernetes-pod/README.md
  examples/templates/kubernetes-pod/main.tf
Labels: chore

#3674 chore: update stale.yaml
  .github/workflows/stale.yaml
Labels: chore

#3740 refactor(scripts): use ln -P on non-darwin arch
  scripts/build_docker.sh
  scripts/package.sh
Labels: chore

#3743 update: google provider to latest
  examples/templates/gcp-linux/main.tf
  examples/templates/gcp-vm-container/main.tf
  examples/templates/gcp-windows/main.tf
Labels: bug, chore

#3739 add: code-server to template examples
  examples/templates/aws-linux/README.md
  examples/templates/aws-linux/main.tf
  examples/templates/docker-image-builds/README.md
  examples/templates/docker-image-builds/main.tf
  examples/templates/docker/README.md
  examples/templates/gcp-linux/README.md
  examples/templates/gcp-linux/main.tf
  examples/templates/gcp-vm-container/README.md
  examples/templates/gcp-vm-container/main.tf
Labels: chore
