Repository coder/coder, pull requests merged in 2023-09, with the labels that each got.

#9496 fix: generate username with uuid to prevent collision
  enterprise/coderd/dormancy/dormantusersjob_test.go
Labels: hotfix

#9500 fix(site): fix workspace parameters update when having immutable parameters
  site/src/pages/WorkspaceBuildPage/WorkspaceBuildPageView.stories.tsx
  site/src/pages/WorkspaceSettingsPage/WorkspaceParametersPage/WorkspaceParametersPage.test.tsx
  site/src/pages/WorkspaceSettingsPage/WorkspaceParametersPage/WorkspaceParametersPage.tsx
  site/src/testHelpers/entities.ts
Labels: hotfix

#9530 chore: exclude generated files from vscode search by default
  .vscode/settings.json
Labels: hotfix

#9534 fix(docs): fix broken markdown links
  docs/CONTRIBUTING.md
  docs/changelogs/v2.1.1.md
  docs/ides/gateway.md
Labels: docs, hotfix

#9503 docs: add `CODER_TLS_ADDRESS` to documentation for TLS setup
  docs/admin/configure.md
Labels: docs, community

#9538 docs: add v2.1.5 changelog
  docs/changelogs/README.md
  docs/changelogs/v2.1.5.md
Labels: hotfix

#9539 fix: use `$coder_version` instead of hardcoded version in release script
  .github/workflows/release.yaml
Labels: hotfix

#9524 docs: fix psk secret cmd
  docs/admin/provisioners.md
Labels: docs

#9548 chore: avoid formatting changelogs
  .prettierrc.yaml
  site/.prettierrc.yaml
Labels: hotfix

#9557 chore: add #9555 to .git-blame-ignore-revs
  .git-blame-ignore-revs
Labels: hotfix

#9559 fix(docs): fix manifest of gcp docs
  docs/manifest.json
Labels: hotfix

#9566 revert: improve flag interpretation for install.sh
  .github/workflows/ci.yaml
  docs/install/install.sh.md
  install.sh
Labels: hotfix

#9567 chore: enable test-2e
  .github/workflows/ci.yaml
Labels: hotfix

#9570 chore(go.mod): update github.com/hashicorp/terraform-json to v0.17.1
  go.mod
  go.sum
Labels: hotfix

#9585 fix(docs): fix broken link
  docs/manifest.json
Labels: hotfix

#9586 fix: remove tf provider versions in examples/
  examples/parameters-dynamic-options/main.tf
  examples/parameters/main.tf
  examples/templates/aws-ecs-container/main.tf
  examples/templates/aws-linux/main.tf
  examples/templates/aws-windows/main.tf
  examples/templates/azure-linux/main.tf
  examples/templates/azure-windows/main.tf
  examples/templates/devcontainer-docker/main.tf
  examples/templates/devcontainer-kubernetes/main.tf
  examples/templates/do-linux/main.tf
  examples/templates/docker-with-dotfiles/main.tf
  examples/templates/docker/main.tf
  examples/templates/envbox/main.tf
  examples/templates/fly-docker-image/main.tf
  examples/templates/gcp-linux/main.tf
  examples/templates/gcp-vm-container/main.tf
  examples/templates/gcp-windows/main.tf
  examples/templates/jfrog/docker/main.tf
  examples/templates/kubernetes-with-podman/main.tf
  examples/templates/kubernetes/main.tf
  examples/update_template_versions.sh
Labels: chore

#9596 fix(scripts): modify logic for determining terraform arch arm64
  scripts/Dockerfile.base
Labels: hotfix

#9569 docs: fix docker-compose update instructions
  docs/admin/upgrade.md
Labels: docs, community

#9616 fix(docs): adjust descriptions in API docs
  docs/api/builds.md
  docs/api/enterprise.md
  docs/api/templates.md
  scripts/apidocgen/markdown-template/main.dot
Labels: hotfix

#9646 docs: remove sysbox 16 pods max
  docs/templates/docker-in-workspaces.md
Labels: community

#9653 fix(site): fix renderer error
  site/package.json
  site/pnpm-lock.yaml
Labels: hotfix

#9677 chore: remove coder trace telemetry
  cli/exp_scaletest.go
  cli/root.go
  cli/server.go
  cli/testdata/coder_server_--help.golden
  cli/testdata/server-config.yaml.golden
  coderd/tracing/exporter.go
  codersdk/deployment.go
  docs/cli/server.md
  enterprise/cli/proxyserver.go
  enterprise/cli/testdata/coder_server_--help.golden
  go.mod
  go.sum
Labels: hotfix

#9681 chore: print page content on failed promise
  site/e2e/tests/webTerminal.spec.ts
Labels: hotfix

#9689 ci: upgrade runners
  .github/workflows/ci.yaml
Labels: hotfix

#9702 ci: cache datadog-ci
  .github/actions/upload-datadog/action.yaml
Labels: hotfix

#9715 docs: fix a typo in README.md
  examples/templates/kubernetes/README.md
Labels: community

#9718 fix(examples): fix typo in examples.gen.json
  examples/examples.gen.json
Labels: hotfix

#9728 chore: increase dependabot open pr limit for `site`
  .github/dependabot.yaml
Labels: hotfix

#9751 fix(cli): specify IgnoreErrors in slogtest options for scaletest cli tests
  cli/exp_scaletest_test.go
Labels: hotfix

#9756 fix(coderd/database/dbtestutil): avoid truncating inserts that span multiple lines
  coderd/database/dbtestutil/db.go
Labels: hotfix

#9768 chore: fix permission for kubeconfig
  .github/workflows/pr-deploy.yaml
Labels: hotfix

#9587 feat: add envFrom value to Helm chart
  helm/coder/templates/_coder.tpl
  helm/coder/tests/chart_test.go
  helm/coder/tests/testdata/auto_access_url_1.golden
  helm/coder/tests/testdata/auto_access_url_1.yaml
  helm/coder/tests/testdata/auto_access_url_2.golden
  helm/coder/tests/testdata/auto_access_url_2.yaml
  helm/coder/tests/testdata/auto_access_url_3.golden
  helm/coder/tests/testdata/auto_access_url_3.yaml
  helm/coder/tests/testdata/env_from.golden
  helm/coder/tests/testdata/env_from.yaml
  helm/coder/values.yaml
Labels: feature

#9771 fix: make sure `fly_app` name is lower case
  examples/templates/fly-docker-image/main.tf
Labels: community

#9774 chore(site): rollback remark-gfm version
  site/package.json
  site/pnpm-lock.yaml
Labels: hotfix

#9784 fix: hide empty update message box
  site/src/pages/WorkspacePage/WorkspaceReadyPage.tsx
Labels: hotfix

#9710 fix(cli): display pasted session token
  cli/login.go
  cli/login_test.go
Labels: cli

#9797 chore: make workspace batch actions enabled by default
  codersdk/deployment.go
Labels: hotfix

#9798 test(site): fix terminal page test flakiness
  site/src/pages/TerminalPage/TerminalPage.test.tsx
Labels: hotfix

#9788 chore: remove extra condition from pr-deploy.yaml
  .github/workflows/pr-deploy.yaml
Labels: hotfix

#9805 chore: bump wgtunnel
  go.mod
  go.sum
Labels: hotfix

#9828 revert: "ci: cache datadog-ci (#9702)"
  .github/actions/upload-datadog/action.yaml
Labels: hotfix

#9829 ci: increase timeout for template build jobs
  coderd/coderdtest/coderdtest.go
Labels: hotfix

#9859 docs: fix typo
  docs/admin/provisioners.md
Labels: hotfix

#9865 fix: resolve flake in log sender by checking context
  codersdk/agentsdk/logs.go
Labels: hotfix

#9866 fix: add case for logs without a source
  site/src/components/Resources/AgentRow.tsx
Labels: hotfix

#9868 fix: allow expansion from `log_path` for `coder_script`
  agent/agentscripts/agentscripts.go
Labels: hotfix

#9869 chore: add git svg icon
  site/static/icon/git.svg
Labels: hotfix

#9871 chore: add icons
  site/static/icon/dotfiles.svg
  site/static/icon/kasmvnc.svg
  site/static/icon/personalize.svg
Labels: hotfix

#9872 fix: remove pinned version for dogfood
  dogfood/main.tf
Labels: hotfix

#9878 feat: allow magic string to generate session token for external apps
  site/src/components/Resources/AppLink/AppLink.tsx
Labels: hotfix

#9776 feat(coderd/httpmw): log `start` timestamp for http requests
  coderd/httpmw/logger.go
Labels: stale

#9891 fix: only specify vscode proxy uri if app subdomains enabled
  coderd/workspaceagents.go
Labels: hotfix

#9910 chore: upgrade go to `1.20.8`
  .github/actions/setup-go/action.yaml
  .github/workflows/ci.yaml
  examples/templates/jfrog/docker/build/Dockerfile
Labels: hotfix

#9911 chore: upgrade alpine to `v3.18.4`
  scripts/Dockerfile.base
Labels: hotfix

#9916 revert: downgrade alpine to `v3.18.3`
  scripts/Dockerfile.base
Labels: hotfix

#9926 fix(site): remove duplicate input for logo url
  site/src/pages/DeploySettingsPage/AppearanceSettingsPage/AppearanceSettingsPageView.tsx
Labels: hotfix

#9928 test: fix flaky TestCreateValidateRichParameters/ValidateString
  cli/create_test.go
Labels: hotfix

#9931 test: fix flaky TestPostWorkspacesByOrganization/Create
  coderd/workspaces_test.go
Labels: hotfix

#9925 chore: update datadog
  .github/actions/upload-datadog/action.yaml
Labels: hotfix

#9947 fix: pass `OnSubscribe` to HA MultiAgent
  enterprise/tailnet/coordinator.go
Labels: hotfix

#9950 fix(site): add space characters to group display name
  site/src/pages/GroupsPage/CreateGroupPageView.tsx
Labels: site, bug

#9959 chore: update helm golden files
  helm/coder/tests/testdata/auto_access_url_1.golden
  helm/coder/tests/testdata/auto_access_url_2.golden
  helm/coder/tests/testdata/auto_access_url_3.golden
  helm/coder/tests/testdata/command.golden
  helm/coder/tests/testdata/command_args.golden
  helm/coder/tests/testdata/default_values.golden
  helm/coder/tests/testdata/env_from.golden
  helm/coder/tests/testdata/labels_annotations.golden
  helm/coder/tests/testdata/provisionerd_psk.golden
  helm/coder/tests/testdata/sa.golden
  helm/coder/tests/testdata/tls.golden
  helm/coder/tests/testdata/workspace_proxy.golden
Labels: hotfix
