Repository coder/coder, pull requests merged in 2023-02, with the labels that each got.

#6046 feat!: Validate monotonic numbers for rich parameters
  cli/cliui/parameter.go
  coderd/apidoc/docs.go
  coderd/apidoc/swagger.json
  coderd/database/dbfake/databasefake.go
  coderd/database/dump.sql
  coderd/database/migrations/000094_rich_parameters_validation_monotonic.down.sql
  coderd/database/migrations/000094_rich_parameters_validation_monotonic.up.sql
  coderd/database/models.go
  coderd/database/queries.sql.go
  coderd/database/queries/templateversionparameters.sql
  coderd/provisionerdserver/provisionerdserver.go
  coderd/templateversions.go
  coderd/workspacebuilds.go
  coderd/workspacebuilds_test.go
  coderd/workspaces.go
  coderd/workspaces_test.go
  codersdk/richparameters.go
  codersdk/templateversions.go
  docs/api/schemas.md
  docs/api/templates.md
  go.mod
  go.sum
  provisioner/terraform/resources.go
  provisionersdk/proto/provisioner.pb.go
  provisionersdk/proto/provisioner.proto
  site/src/api/typesGenerated.ts
  site/src/components/RichParameterInput/RichParameterInput.stories.tsx
  site/src/i18n/en/workspaceBuildParametersPage.json
  site/src/pages/CreateWorkspacePage/CreateWorkspacePageView.tsx
  site/src/pages/WorkspaceBuildParametersPage/WorkspaceBuildParametersPage.test.tsx
  site/src/pages/WorkspaceBuildParametersPage/WorkspaceBuildParametersPageView.tsx
  site/src/testHelpers/entities.ts
Labels: release/breaking

#5934 feat: add iron bank Dockerfile & manifest
  .github/workflows/security.yaml
  scripts/ironbank/.gitignore
  scripts/ironbank/Dockerfile
  scripts/ironbank/build_ironbank.sh
  scripts/ironbank/hardening_manifest.yaml
  scripts/ironbank/terraform-filesystem-mirror.tfrc
  scripts/lib.sh
Labels: feature, enterprise

#6136 helm: add deployment securityContext values
  helm/templates/coder.yaml
  helm/values.yaml
Labels: feature

#6207 fix: set Coder read-only fs to null
  helm/values.yaml
Labels: bug

#6212 docs: add template-level URL override
  docs/networking.md
Labels: docs

#6218 chore: break down dbauthz.System into smaller roles
  coderd/activitybump.go
  coderd/autobuild/executor/lifecycle_executor.go
  coderd/database/dbauthz/dbauthz.go
  coderd/database/dbauthz/querier.go
  coderd/database/dbauthz/querier_test.go
  coderd/database/dbauthz/setup_test.go
  coderd/database/dbauthz/system.go
  coderd/httpmw/apikey.go
  coderd/httpmw/authz.go
  coderd/httpmw/hsts_test.go
  coderd/httpmw/userparam.go
  coderd/httpmw/workspaceagent.go
  coderd/metricscache/metricscache.go
  coderd/provisionerdserver/provisionerdserver.go
  coderd/rbac/authz_internal_test.go
  coderd/rbac/builtin.go
  coderd/rbac/scopes.go
  coderd/userauth.go
  coderd/users.go
  coderd/workspaceagents.go
  coderd/workspaceapps.go
  coderd/workspaceresourceauth.go
  enterprise/coderd/coderd_test.go
  enterprise/coderd/scim.go
  provisionerd/runner/runner.go
Labels: release/experimental

#6337 fix!: replace owner_email with workspace_owner, change action to workspace_transition
  provisionerd/provisionerd.go
  provisionerd/runner/runner.go
Labels: release/breaking
