Repository coder/coder, pull requests merged in 2023-05, with the labels that each got.

#7237 chore: skip timing-sensistive AgentMetadata test in the standard suite
  agent/agent.go
  agent/agent_test.go
  testutil/enable_timing.go
  testutil/timing.go
Labels: stale

#7372 docs: make use of `display_name` and `name` in Open with Coder
  docs/templates/open-in-coder.md
Labels: docs

#7402 feat: add inactivity cleanup and failure cleanup configuration fields to Template Schedule Form
  .vscode/settings.json
  coderd/apidoc/docs.go
  coderd/apidoc/swagger.json
  coderd/database/dbfake/databasefake.go
  coderd/database/dump.sql
  coderd/database/migrations/000122_add_template_cleanup_ttls.down.sql
  coderd/database/migrations/000122_add_template_cleanup_ttls.up.sql
  coderd/database/modelqueries.go
  coderd/database/models.go
  coderd/database/queries.sql.go
  coderd/database/queries/templates.sql
  coderd/database/sqlc.yaml
  coderd/schedule/template.go
  coderd/templates.go
  coderd/templates_test.go
  codersdk/deployment.go
  codersdk/organizations.go
  codersdk/templates.go
  docs/admin/audit-logs.md
  docs/api/schemas.md
  docs/api/templates.md
  enterprise/audit/table.go
  enterprise/coderd/coderd.go
  enterprise/coderd/coderd_test.go
  enterprise/coderd/provisionerdaemons.go
  site/src/api/typesGenerated.ts
  site/src/i18n/en/templateSettingsPage.json
  site/src/pages/TemplateSettingsPage/TemplateSchedulePage/TemplateScheduleForm.tsx
  site/src/pages/TemplateSettingsPage/TemplateSchedulePage/TemplateSchedulePage.test.tsx
  site/src/pages/TemplateSettingsPage/TemplateSchedulePage/TemplateSchedulePage.tsx
  site/src/pages/TemplateSettingsPage/TemplateSchedulePage/TemplateSchedulePageView.stories.tsx
  site/src/pages/TemplateSettingsPage/TemplateSchedulePage/TemplateSchedulePageView.tsx
  site/src/testHelpers/entities.ts
Labels: feature

#7460 docs: fix proxy cmd ref
  docs/admin/workspace-proxies.md
  helm/values.yaml
Labels: docs

#7494 docs: add docs for disabling email/pass auth
  docs/admin/auth.md
Labels: docs

#7475 feat: add deleted_at field to workspace model
  .vscode/settings.json
  cli/testdata/coder_list_--output_json.golden
  coderd/apidoc/docs.go
  coderd/apidoc/swagger.json
  coderd/workspaces.go
  coderd/workspaces_internal_test.go
  codersdk/workspaces.go
  docs/api/schemas.md
  docs/api/workspaces.md
  site/src/api/typesGenerated.ts
  site/src/testHelpers/entities.ts
Labels: feature

#7510 docs: add instructions for connecting to Windows workspaces via RDP
  docs/ides/remote-desktops.md
  docs/images/ides/windows_rdp_client.png
Labels: docs

#7588 feat: add impending deletion indicators to the workspace page
  site/src/components/Workspace/Workspace.stories.tsx
  site/src/components/WorkspaceDeletion/ImpendingDeletionBadge.tsx
  site/src/components/WorkspaceDeletion/ImpendingDeletionBanner.tsx
  site/src/components/WorkspaceDeletion/ImpendingDeletionStat.tsx
  site/src/components/WorkspaceDeletion/ImpendingDeletionText.tsx
  site/src/components/WorkspaceDeletion/index.ts
  site/src/components/WorkspaceDeletion/utils.test.ts
  site/src/components/WorkspaceDeletion/utils.ts
  site/src/components/WorkspaceStats/WorkspaceStats.stories.tsx
  site/src/components/WorkspaceStats/WorkspaceStats.tsx
  site/src/components/WorkspaceStatusBadge/WorkspaceStatusBadge.stories.tsx
  site/src/components/WorkspaceStatusBadge/WorkspaceStatusBadge.tsx
  site/src/pages/TemplateSettingsPage/TemplateSchedulePage/TemplateSchedulePage.tsx
  site/src/pages/WorkspacePage/WorkspacePage.test.tsx
  site/src/pages/WorkspacesPage/WorkspacesPage.tsx
  site/src/pages/WorkspacesPage/WorkspacesPageView.stories.tsx
  site/src/pages/WorkspacesPage/WorkspacesPageView.tsx
  site/src/testHelpers/entities.ts
  site/src/utils/workspace.test.ts
  site/src/utils/workspace.ts
Labels: feature

#7602 chore: remove CPU usage calculation for hosts on cgroup v1
  dogfood/main.tf
Labels: chore

#7614 docs: Add steps to migrate from the built-in database to an external database
  docs/admin/configure.md
Labels: docs

#7661 chore(dogfood): Update sqlc version in dogfood image to match CI
  dogfood/Dockerfile
Labels: bug, bug:p3:internal/low

#7727 hotfix(ci): fix a syntax issue in contrib.yaml
  .github/workflows/contrib.yaml
Labels: ci/cd

#7730 feat: add support for insiders channel to "VS Code Desktop" button
  site/src/components/Icons/VSCodeIcon.tsx
  site/src/components/Icons/VSCodeInsidersIcon.tsx
  site/src/components/Resources/AgentButton.tsx
  site/src/components/TerminalLink/TerminalLink.tsx
  site/src/components/VSCodeDesktopButton/VSCodeDesktopButton.tsx
Labels: feature
