Repository coder/coder, pull requests merged in 2023-04, with the labels that each got.

#6958 chore: mac from docker quickstart
  docs/quickstart/docker.md
Labels: docs

#6922 fix(coderd)!: add CODER_OIDC_IGNORE_USERINFO configuration option
  cli/server.go
  cli/server_test.go
  cli/testdata/coder_server_--help.golden
  coderd/apidoc/docs.go
  coderd/apidoc/swagger.json
  coderd/userauth.go
  coderd/userauth_test.go
  codersdk/deployment.go
  docs/admin/auth.md
  docs/api/general.md
  docs/api/schemas.md
  docs/cli/server.md
  site/src/api/typesGenerated.ts
Labels: release/breaking

#7007 docs: add helm example for OIDC_GROUP_MAPPING var
  docs/admin/auth.md
Labels: docs

#7065 docs: bump tf version in offline docs
  docs/install/offline.md
Labels: docs

#7059 fix(ci): fix typo in cron-weekly.yaml
  .github/workflows/cron-weekly.yaml
Labels: chore

#7139 feat(helm): add labels for coder pod
  helm/templates/coder.yaml
  helm/values.yaml
Labels: feature

#7048 docs: disclaim write load for agent metadata
  docs/templates/agent-metadata.md
Labels: stale

#6352 docs: fixed broken podman template link and added already-installed ide gateway doc
  docs/ides/gateway.md
Labels: stale

#6923 docs: added additional documentation for azure devops git provider
  docs/admin/git-providers.md
Labels: stale

#7324 fix: envbox template 404
  docs/templates/docker-in-workspaces.md
Labels: bug, docs
