Repository coder/coder, pull requests merged in 2023-08, with the labels that each got.

#8826 fix: parse insights start and end time
  coderd/insights_internal_test.go
Labels: hotfix

#8845 docs: rm microsoft vs code server docs
  docs/ides/web-ides.md
Labels: docs

#8853 chore: update concurrency to use PR number
  .github/workflows/pr-deploy.yaml
Labels: hotfix

#8852 fix: avoid agent runLoop exiting due to ws ping
  agent/agent.go
  codersdk/agentsdk/agentsdk.go
Labels: hotfix

#8857 fix: copy secret for the first deployment too
  .github/workflows/pr-deploy.yaml
Labels: hotfix

#8859 fix: add read call to derp-map endpoint to avoid ws ping timeout
  coderd/workspaceagents.go
Labels: hotfix

#8864 fix(site): show error when user exists
  site/src/components/CreateUserForm/CreateUserForm.stories.tsx
  site/src/components/CreateUserForm/CreateUserForm.tsx
  site/src/pages/UsersPage/CreateUserPage/CreateUserPage.tsx
Labels: hotfix

#8863 fix(site): fix initial value for update parameters
  site/src/pages/WorkspacePage/UpdateBuildParametersDialog.tsx
Labels: hotfix

#8811 chore: bump openssl in base image
  scripts/Dockerfile.base
Labels: hotfix

#8878 fix: fix develop script and pnpm command
  scripts/develop.sh
Labels: hotfix

#8882 fix: prevent PR deployment without manual trigger
  .github/workflows/pr-cleanup.yaml
  .github/workflows/pr-deploy.yaml
Labels: hotfix

#8890 chore: add v2 changelog
  docs/changelogs/v2.0.0.md
Labels: hotfix

#8888 fix(helm): set correct prom port in helm notes
  helm/values.yaml
Labels: docs

#8896 ci: delete comments by github-action[bot] on PR close
  .github/workflows/pr-cleanup.yaml
Labels: hotfix

#8901 chore(docs): fix link to helm values highlighting affinity
  docs/admin/scale.md
Labels: docs, hotfix

#8869 docs: clean up k8s install steps and order
  docs/install/kubernetes.md
Labels: docs

#8902 fix(cli): address race condition in scaletest_test output
  cli/exp_scaletest_test.go
Labels: hotfix

#8806 fix(cli): stat: set --host arg in TestStatCPUCmd to avoid test flakes in containers
  cli/stat_test.go
Labels: hotfix

#8916 fix(enterprise): ensure SCIM create user can unsuspend
  enterprise/coderd/scim.go
  enterprise/coderd/scim_test.go
Labels: hotfix

#8917 fix: don't close cached tailnet on pty close
  coderd/workspaceapps/proxy.go
Labels: hotfix

#8579 fix(cli/delete): prompt for confirmation after workspace is found
  cli/delete.go
  cli/delete_test.go
  codersdk/workspaces.go
Labels: hotfix

#8945 fix: update tag name for `coder-preview` image in ci.yaml
  .github/workflows/ci.yaml
Labels: hotfix

#8949 fix: improve formatting in Gateway docs
  docs/ides/gateway.md
Labels: hotfix

#8953 chore: fix `TestTailnet/ForcesWebSockets` flake
  coderd/batchstats/batcher.go
  tailnet/conn_test.go
  tailnet/tailnettest/tailnettest.go
Labels: hotfix

#8952 chore: fix `TestBatchStats` flake
  coderd/batchstats/batcher.go
  coderd/batchstats/batcher_internal_test.go
  coderd/workspaceagents.go
Labels: hotfix

#8958 chore: add e2e test for backwards client ssh compatibility
  site/e2e/helpers.ts
  site/e2e/tests/outdatedCLI.spec.ts
Labels: hotfix

#8975 fix: default to executing e2e ssh without args
  site/e2e/helpers.ts
Labels: hotfix

#8977 ci: make `test-e2e` a required check
  .github/workflows/ci.yaml
Labels: hotfix

#8980 chore: upgrade to alpine `3.18.3`
  scripts/Dockerfile.base
Labels: hotfix

#8985 refactor(site): add default title
  site/index.html
Labels: hotfix

#8989 fix: rename duplicate migration
  coderd/database/migrations/000149_agent_multiple_subsystems.down.sql
  coderd/database/migrations/000149_agent_multiple_subsystems.up.sql
Labels: hotfix

#8990 fix: remove stun nodes from workspace proxy regions
  enterprise/coderd/coderd.go
  enterprise/wsproxy/wsproxy_test.go
Labels: hotfix

#8825 fix: add helper for user to convert OIDC account (#8695)
  coderd/userauth.go
Labels: stale, hotfix

#8986 refactor(site): remove last 7 days label
  site/src/pages/TemplatePage/TemplateInsightsPage/TemplateInsightsPage.tsx
Labels: hotfix

#8997 fix(site): show user avatar on group page
  site/src/components/UserAvatar/UserAvatar.tsx
  site/src/pages/GroupsPage/GroupPage.tsx
Labels: hotfix

#8996 fix(site): make stats bar scrollable on smaller viewports
  site/src/components/DeploymentBanner/DeploymentBannerView.tsx
Labels: hotfix

#8998 fix(site): add horizontal scroll when having many tabs
  site/src/components/TemplateFiles/TemplateFiles.tsx
Labels: hotfix

#9006 chore: fix terraform tests
  .github/actions/setup-tf/action.yaml
  provisioner/terraform/provision_test.go
Labels: hotfix

#9007 chore: increase e2e timeout to 60s
  site/e2e/playwright.config.ts
Labels: hotfix

#9008 chore: use echo provisioners in logging tests
  cli/server_test.go
Labels: hotfix

#8805 fix(scripts): check if PR list is empty
  scripts/release/check_commit_metadata.sh
Labels: stale, community

#9005 fix(site): add search params to auth redirect
  site/src/components/RequireAuth/RequireAuth.tsx
Labels: hotfix

#9004 fix(site): set default color and display error on appearance form
  site/src/pages/DeploySettingsPage/AppearanceSettingsPage/AppearanceSettingsPageView.tsx
  site/src/xServices/appearance/appearanceXService.ts
Labels: hotfix

#9010 fix(site): fix storybook error and inconsistent snapshots
  site/src/components/Resources/AgentMetadata.tsx
  site/src/pages/DeploySettingsPage/GeneralSettingsPage/GeneralSettingsPageView.stories.tsx
  site/src/pages/WorkspacePage/WorkspaceBuildLogsSection.tsx
Labels: hotfix

#9009 refactor(site): add default background color to html and body
  site/index.html
Labels: hotfix

#9025 docs: write 2.0.2 changelog
  docs/admin/provisioners.md
  docs/changelogs/v2.0.2.md
Labels: hotfix

#9028 refactor(site): add minor improvements to the port button
  site/src/components/Resources/PortForwardButton.tsx
  site/src/theme/theme.ts
Labels: hotfix

#9029 feat(site): add tooltip showing the error in the failure badge
  site/src/components/WorkspaceStatusBadge/WorkspaceStatusBadge.tsx
Labels: hotfix

#8993 feat: add support for NodePort service type in Helm chart
  helm/coder/templates/service.yaml
  helm/coder/tests/testdata/command.golden
  helm/coder/tests/testdata/command_args.golden
  helm/coder/tests/testdata/default_values.golden
  helm/coder/tests/testdata/labels_annotations.golden
  helm/coder/tests/testdata/provisionerd_psk.golden
  helm/coder/tests/testdata/sa.golden
  helm/coder/tests/testdata/tls.golden
  helm/coder/tests/testdata/workspace_proxy.golden
  helm/coder/values.yaml
Labels: community

#9046 ci: do not run deploy-pr on main
  .github/workflows/pr-deploy.yaml
Labels: hotfix

#9049 fix: prevent unrequested PR deployments
  .github/workflows/pr-deploy.yaml
Labels: hotfix

#9047 ci: remove deleting comments section from pr-cleanup.yaml
  .github/workflows/pr-cleanup.yaml
Labels: hotfix

#9039 docs: add offline docs for JetBrains Gateway
  docs/ides/gateway.md
Labels: docs

#9038 docs: add coder login to CI docs
  docs/templates/change-management.md
Labels: docs

#9064 fix: update BUILD condition in pr-deploy.yaml
  .github/workflows/pr-deploy.yaml
Labels: hotfix

#9022 chore: update speakeasy to fix stty path bug on nixos
  go.mod
  go.sum
Labels: hotfix

#9069 fix: remove duplication from language of query param error
  coderd/httpapi/queryparams.go
  coderd/searchquery/search_test.go
Labels: hotfix

#9068 fix: remove unnecessary newlines from the end of cli output
  cli/exp_scaletest.go
  cli/gitaskpass.go
  cli/publickey.go
  cli/server.go
  cli/server_createadminuser.go
  cli/speedtest.go
Labels: hotfix

#9070 fix: change dashboard route `/settings/deployment` to `/deployment`
  site/src/AppRouter.tsx
  site/src/components/Navbar/NavbarView.test.tsx
  site/src/components/Navbar/NavbarView.tsx
  site/src/pages/DeploySettingsPage/LicensesSettingsPage/AddNewLicensePage.tsx
  site/src/pages/DeploySettingsPage/LicensesSettingsPage/AddNewLicensePageView.tsx
  site/src/pages/DeploySettingsPage/LicensesSettingsPage/LicensesSettingsPageView.tsx
Labels: hotfix

#8906 chore(docs): fix indentation in install/kubernetes.md
  docs/install/kubernetes.md
Labels: docs, hotfix

#9088 fix: fix CI concurrency
  .github/workflows/ci.yaml
Labels: hotfix

#9094 fix: catch missed output with reconnecting PTY
  agent/agent.go
  agent/reconnectingpty/buffered.go
  agent/reconnectingpty/reconnectingpty.go
  agent/reconnectingpty/screen.go
Labels: hotfix

#9104 revert: 'ci: run tests intelligently based on changes' (#9017)
  .github/workflows/ci.yaml
Labels: hotfix

#9112 docs: update FE stack
  docs/contributing/frontend.md
Labels: hotfix

#9115 docs: add conditional example to optional vs required parameters
  docs/templates/parameters.md
Labels: hotfix

#9097 fix: rename group GET request
  coderd/apidoc/docs.go
  coderd/apidoc/swagger.json
  docs/api/enterprise.md
  enterprise/coderd/groups.go
Labels: docs, api, bug

#9098 fix(tailnet): disable wireguard trimming
  tailnet/conn.go
Labels: hotfix

#9113 docs: add bpmct template repo to community markdown
  examples/templates/community-templates.md
Labels: hotfix

#8921 ci: add Chocolatey support
  .github/workflows/release.yaml
  scripts/chocolatey/coder.nuspec
Labels: community

#9127 refactor(site): use bar chart for DAUs
  site/src/components/DAUChart/DAUChart.tsx
Labels: hotfix

#9096 docs: add missing `last_seen_before` and `last_seen_after` search parameter
  docs/admin/users.md
Labels: hotfix

#8979 fix!: remove jq from image
  scripts/Dockerfile.base
Labels: security, release/breaking

#9143 chore: replace chi with chi/v5
  agent/api.go
  coderd/telemetry/telemetry_test.go
  go.mod
Labels: community

#9160 docs: add 2.1.0 changelog
  docs/changelogs/v2.1.0.md
Labels: hotfix

#9167 fix: do not install strace on Darwin
  flake.nix
Labels: hotfix

#9166 ci: add github token to chocolatey workflow
  .github/workflows/release.yaml
Labels: community

#9177 fix(site): remove mock data from port forward button
  site/src/components/Resources/PortForwardButton.tsx
Labels: hotfix

#9174 chore(scripts/develop.sh): restore original access url setting
  cli/exp_scaletest_test.go
  scripts/develop.sh
Labels: hotfix

#9189 fix: separate dev shell and dev image nix deps
  flake.nix
Labels: hotfix

#9191 fix: allow chsh in dev image
  flake.nix
Labels: hotfix

#9183 fix: use proper link to workspace proxies page
  site/src/components/Navbar/NavbarView.tsx
Labels: hotfix

#9193 fix: add yarn to the dogfood image
  flake.nix
Labels: hotfix

#9190 fix(agent): log correct script timeout for startup script
  agent/agent.go
Labels: hotfix

#9195 fix: remove nix bash from the dogfood image
  flake.nix
Labels: hotfix

#9202 fix: add sapling to the nix flake
  flake.nix
Labels: hotfix

#9078 docs: remove <> and use `shell` for code blocks in azure docs
  docs/platforms/azure.md
Labels: community

#9207 fix: set the location of `locale_archive`
  flake.nix
Labels: hotfix

#9208 chore: add version to top-level package.json to allow importing
  package.json
Labels: hotfix

#9209 chore: add name to top-level package.json to allow importing
  package.json
Labels: hotfix

#9224 chore: add dependencies for js-test to our nix flake
  flake.nix
Labels: hotfix

#9223 fix(site): fix locale dates in timeline component
  site/src/components/Timeline/TimelineDateRow.tsx
  site/src/components/Timeline/utils.test.ts
  site/src/components/Timeline/utils.ts
Labels: hotfix

#9228 chore: downgrade dogfood image to postgres 13
  flake.nix
Labels: hotfix

#9231 chore(dogfood): revert to pre-nix image
  dogfood/main.tf
Labels: hotfix

#9249 docs: add v2.1.1 changelog
  docs/changelogs/README.md
  docs/changelogs/v2.1.1.md
  docs/manifest.json
  docs/templates/process-logging.md
Labels: hotfix

#9273 refactor(site): improve how string values are displayed
  site/src/pages/TemplatePage/TemplateInsightsPage/TemplateInsightsPage.tsx
Labels: hotfix

#9277 fix: resolve deadlock when fetching everyone group for in-memory db
  coderd/database/dbfake/dbfake.go
Labels: hotfix

#9258 chore: add a base directory for TurboSnap
  .github/workflows/ci.yaml
  site/.storybook/main.js
  site/package.json
  site/pnpm-lock.yaml
Labels: community

#9288 chore: write v2.1.2 changelog
  docs/changelogs/README.md
  docs/changelogs/v2.1.2.md
Labels: hotfix

#9270 fix(site): fix vertical scroll in the bottom bar
  site/src/components/DeploymentBanner/DeploymentBannerView.tsx
Labels: hotfix

#9293 fix(coderd): prevent oidc refresh being ignored
  coderd/httpmw/apikey.go
Labels: community

#9272 refactor(site): remove as many 100vh units as possible
  site/src/components/Dashboard/DashboardLayout.tsx
  site/src/components/RuntimeErrorState/RuntimeErrorState.tsx
  site/src/components/SignInLayout/SignInLayout.tsx
  site/src/components/TemplateVersionEditor/TemplateVersionEditor.tsx
  site/src/pages/404Page/404Page.tsx
  site/src/pages/HealthPage/HealthPage.tsx
  site/src/pages/LoginPage/LoginPageView.tsx
  site/src/pages/TemplatePage/TemplateEmbedPage/TemplateEmbedPage.tsx
  site/src/pages/WorkspaceBuildPage/WorkspaceBuildPage.tsx
  site/src/pages/WorkspaceBuildPage/WorkspaceBuildPageView.stories.tsx
  site/src/pages/WorkspaceBuildPage/WorkspaceBuildPageView.tsx
  site/src/theme/theme.ts
Labels: hotfix

#9311 docs: add v2.1.3 changelog
  docs/changelogs/README.md
  docs/changelogs/v2.1.3.md
Labels: hotfix

#9314 fix(site): fix default ephemeral parameter value on parameters page
  site/src/pages/WorkspaceSettingsPage/WorkspaceParametersPage/WorkspaceParametersForm.tsx
Labels: hotfix

#9286 docs: expand on TTL flags
  cli/templatecreate.go
  cli/templateedit.go
  cli/testdata/coder_templates_create_--help.golden
  cli/testdata/coder_templates_edit_--help.golden
  docs/cli/templates_create.md
  docs/cli/templates_edit.md
Labels: docs, cli

#9259 fix(site): render variable width unicode characters in terminal
  site/package.json
  site/pnpm-lock.yaml
  site/src/pages/TerminalPage/TerminalPage.tsx
Labels: hotfix

#9320 fix(site): use WebGL renderer for terminal
  site/package.json
  site/pnpm-lock.yaml
  site/src/AppRouter.tsx
  site/src/pages/TerminalPage/TerminalPage.tsx
Labels: hotfix

#9342 refactor(site): improve the overall user table design
  site/src/components/EditRolesButton/EditRolesButton.tsx
  site/src/components/UsersTable/UsersTable.stories.tsx
  site/src/components/UsersTable/UsersTable.tsx
  site/src/components/UsersTable/UsersTableBody.tsx
  site/src/pages/UsersPage/UsersPage.tsx
  site/src/pages/UsersPage/UsersPageView.stories.tsx
  site/src/pages/UsersPage/UsersPageView.tsx
  site/src/pages/WorkspacesPage/LastUsed.tsx
  site/src/pages/WorkspacesPage/WorkspacesTable.tsx
Labels: hotfix

#9344 fix(site): make right panel scrollable on template editor
  site/src/components/Resources/ResourceCard.tsx
  site/src/components/TemplateVersionEditor/TemplateVersionEditor.stories.tsx
  site/src/components/TemplateVersionEditor/TemplateVersionEditor.tsx
Labels: hotfix

#8936 docs: list firewall exceptions for restricted internet installations
  docs/install/offline.md
Labels: docs

#9356 chore(dogfood): update docker tf provider and metadata
  dogfood/main.tf
Labels: hotfix

#9358 ci: remove `set -x` in pr-cleanup.yaml
  .github/workflows/pr-cleanup.yaml
Labels: hotfix

#9226 feat: add `template_active_version_id` to workspaces
  cli/testdata/coder_list_--output_json.golden
  coderd/apidoc/docs.go
  coderd/apidoc/swagger.json
  coderd/workspaces.go
  codersdk/workspaces.go
  docs/api/schemas.md
  docs/api/workspaces.md
  site/src/api/typesGenerated.ts
  site/src/testHelpers/entities.ts
Labels: hotfix

#9360 fix: truncate websocket close error
  coderd/provisionerjobs.go
Labels: hotfix

#9362 chore: format oidctest
  coderd/coderdtest/oidctest/idp.go
  coderd/coderdtest/oidctest/idp_test.go
Labels: hotfix

#9365 ci: remove redundant groups from dependabot.yaml
  .github/dependabot.yaml
Labels: chore, hotfix

#9376 ci: prefix dependabot github-actions PRs with `ci:`
  .github/dependabot.yaml
Labels: chore

#9398 docs: add v2.1.4 changelog
  docs/changelogs/README.md
  docs/changelogs/v2.1.4.md
Labels: hotfix

#9408 chore: support protobuf files in the UI
  site/src/utils/templateVersion.ts
Labels: hotfix

#9388 docs: add jetbrains offline mode config steps
  docs/ides/gateway.md
  docs/images/gateway/jetbrains-offline-windows.png
  docs/images/gateway/offline-gateway.png
Labels: docs

#9441 fix(site): remove checkbox from ws table loader
  site/src/pages/WorkspacesPage/WorkspacesTable.tsx
Labels: hotfix

#9349 fix: fix aws_linux template
  examples/templates/aws-linux/main.tf
Labels: hotfix

#9476 chore(tailnet): fix `MultiAgentConn` mockgen
  tailnet/tailnettest/multiagentmock.go
  tailnet/tailnettest/tailnettest.go
Labels: hotfix
