Repository coder/coder, pull requests merged in 2023-11, with the labels that each got.

#10492 refactor(site): minor improvements on users page popovers
  site/src/pages/UsersPage/UsersTable/UserGroupsCell.tsx
  site/src/pages/UsersPage/UsersTable/UserRoleCell.tsx
Labels: hotfix

#10497 fix(site): fix favicon theme
  site/src/pages/WorkspacePage/WorkspaceReadyPage.tsx
Labels: hotfix

#10495 refactor(site): remove version and last built from workspace header
  site/src/components/Stats/Stats.tsx
  site/src/components/WorkspaceOutdatedTooltip/WorkspaceOutdatedTooltip.tsx
  site/src/pages/WorkspacePage/BuildRow.tsx
  site/src/pages/WorkspacePage/WorkspaceStats.tsx
Labels: hotfix

#10496 refactor(site): simplify proxy menu
  site/src/components/Dashboard/Navbar/NavbarView.tsx
Labels: hotfix

#10493 refactor(site): make minor design tweaks and fix issues on more options menus
  site/src/components/MoreMenu/MoreMenu.tsx
  site/src/components/TableRowMenu/TableRowMenu.stories.tsx
  site/src/components/TableRowMenu/TableRowMenu.tsx
  site/src/pages/GroupsPage/GroupPage.tsx
  site/src/pages/TemplatePage/TemplatePageHeader.tsx
  site/src/pages/TemplateSettingsPage/TemplatePermissionsPage/TemplatePermissionsPageView.tsx
  site/src/pages/UsersPage/UsersPage.test.tsx
  site/src/pages/UsersPage/UsersTable/UsersTable.tsx
  site/src/pages/UsersPage/UsersTable/UsersTableBody.tsx
  site/src/pages/WorkspacePage/WorkspaceActions/WorkspaceActions.tsx
  site/src/theme/theme.ts
Labels: hotfix

#10502 fix(site): fix health tooltip on deployment bar
  site/src/components/Dashboard/DeploymentBanner/DeploymentBannerView.tsx
  site/src/testHelpers/entities.ts
Labels: hotfix

#10501 fix(site): fix dialog loading buttons displaying text over the spinner
  site/src/components/Dialogs/ConfirmDialog/ConfirmDialog.stories.tsx
  site/src/components/Dialogs/ConfirmDialog/ConfirmDialog.tsx
  site/src/components/Dialogs/DeleteDialog/DeleteDialog.stories.tsx
  site/src/components/Dialogs/Dialog.tsx
  site/src/pages/TemplateSettingsPage/TemplateSchedulePage/ScheduleDialog.tsx
Labels: hotfix

#10514 feat: add `log-dir` flag to vscodessh for debuggability
  cli/vscodessh.go
  cli/vscodessh_test.go
Labels: hotfix

#10513 fix: add support for custom auth header with client secret
  coderd/externalauth/externalauth.go
  coderd/externalauth/externalauth_test.go
  codersdk/externalauth.go
  site/src/api/typesGenerated.ts
Labels: hotfix

#10511 refactor(site): add minor design improvements on the setup page
  site/src/components/Welcome/Welcome.tsx
  site/src/pages/SetupPage/SetupPageView.tsx
Labels: hotfix

#10523 fix(site): fix user dropdown width
  site/src/components/Dashboard/Navbar/UserDropdown/UserDropdown.tsx
Labels: hotfix

#10417 chore: pin devcontainer.json to pre-nix image
  .devcontainer/devcontainer.json
Labels: hotfix

#10517 refactor(site): handle edge cases for non-admin users with no workspaces and templates
  site/src/pages/WorkspacesPage/WorkspacesEmpty.tsx
  site/src/pages/WorkspacesPage/WorkspacesPage.tsx
  site/src/pages/WorkspacesPage/WorkspacesPageView.stories.tsx
  site/src/pages/WorkspacesPage/WorkspacesPageView.tsx
  site/src/pages/WorkspacesPage/WorkspacesTable.tsx
Labels: hotfix

#10448 feat: expose prometheus port in helm chart
  docs/admin/prometheus.md
  helm/coder/templates/service.yaml
  helm/coder/tests/chart_test.go
  helm/coder/tests/testdata/prometheus.golden
  helm/coder/tests/testdata/prometheus.yaml
  helm/coder/values.yaml
Labels: community

#10551 fix: use `DefaultTransport` in `exchangeWithClientSecret` if nil
  coderd/externalauth/externalauth.go
Labels: hotfix

#10552 refactor(site): add version back to workspace header
  site/src/pages/WorkspacePage/Workspace.tsx
  site/src/pages/WorkspacePage/WorkspaceStats.tsx
Labels: hotfix

#10561 fix: disable pagination nav buttons correctly
  site/src/components/PaginationWidget/PaginationWidgetBase.tsx
Labels: hotfix

#10557 fix(site): fix agent log error
  site/src/components/Resources/AgentRow.tsx
Labels: hotfix

#10569 ci: close likely-no issues automatically
  .github/workflows/stale.yaml
Labels: hotfix

#10579 fix(site): fix bottom bar height
  site/src/pages/TerminalPage/TerminalPage.tsx
Labels: hotfix

#10580 chore(site): revert remark-gfm upgrade
  site/package.json
  site/pnpm-lock.yaml
Labels: hotfix

#10584 fix: remove stray 0 when no data is in users table
  site/src/pages/UsersPage/UsersPageView.tsx
Labels: hotfix

#10593 fix: improve language of latest build error
  coderd/workspaceagents.go
Labels: hotfix

#10606 fix(scripts): forward all necessary ports for remote playwright
  scripts/remote_playwright.sh
Labels: hotfix

#10616 fix: remove accidental scrollbar from deployment banner
  site/src/components/Dashboard/DeploymentBanner/DeploymentBannerView.tsx
Labels: site, s3, hotfix, bug

#10617 feat: add docs for Bitbucket Server external auth config
  docs/admin/external-auth.md
Labels: docs

#10591 chore: fix flake.nix to run on macos
  flake.nix
Labels: community

#10631 ci: bump go to version 1.20.11
  .github/actions/setup-go/action.yaml
  .github/workflows/ci.yaml
Labels: hotfix

#10630 ci: bump terraform version to 1.5.7 to match embedded terraform version
  .github/actions/setup-tf/action.yaml
Labels: hotfix

#10485 feat: add debug endpoint for single tailnet
  coderd/apidoc/docs.go
  coderd/apidoc/swagger.json
  coderd/coderd.go
  coderd/coderdtest/swaggerparser.go
  coderd/debug.go
  coderd/tailnet.go
  coderd/workspaceapps/proxy.go
  coderd/wsconncache/wsconncache.go
  docs/api/debug.md
Labels: stale

#10701 chore: update openssl in Dockerfile
  scripts/Dockerfile.base
Labels: hotfix

#10703 chore: tidy go.mod
  go.mod
Labels: hotfix

#10706 chore: fix docs for max lifetime
  docs/enterprise.md
  docs/workspaces.md
Labels: hotfix

#10657 chore: clarify namespace requirement for kubernetes template
  examples/templates/kubernetes/main.tf
Labels: hotfix

#10711 fix: disable flaky test TestSSH/RemoteForward_Unix_Signal
  cli/ssh_test.go
Labels: hotfix

#10704 feat!: bump workspace activity by 1 hour
  coderd/activitybump.go
  coderd/activitybump_internal_test.go
  coderd/activitybump_test.go
  coderd/autobuild/lifecycle_executor.go
  coderd/database/dbauthz/dbauthz.go
  coderd/database/dbmem/dbmem.go
  coderd/database/dbmetrics/dbmetrics.go
  coderd/database/dbmock/dbmock.go
  coderd/database/querier.go
  coderd/database/queries.sql.go
  coderd/database/queries/activitybump.sql
  coderd/workspaceagents.go
Labels: release/breaking

#10683 chore: disable trial activation on e2e tests
  site/e2e/global.setup.ts
  site/src/pages/SetupPage/SetupPageView.tsx
Labels: hotfix

#10739 fix(site): fix group name validation
  site/src/pages/GroupsPage/CreateGroupPageView.tsx
Labels: hotfix

#10742 chore(site): increase stop workspace timeout
  site/e2e/helpers.ts
  site/e2e/playwright.config.ts
Labels: hotfix

#10744 fix(site): fix scroll when having many build options
  site/src/pages/WorkspacePage/WorkspaceActions/BuildParametersPopover.tsx
Labels: hotfix

#10749 test: skip TestCollectInsights
  coderd/prometheusmetrics/insights/metricscollector_test.go
Labels: hotfix

#10751 fix(site): prevent overwriting of newest workspace data during optimistic updates
  site/e2e/helpers.ts
  site/e2e/playwright.config.ts
  site/src/api/queries/workspaces.ts
Labels: hotfix

#10750 refactor(site): adjust a few colors
  site/src/components/DeploySettingsLayout/Sidebar.tsx
  site/src/components/SettingsLayout/Sidebar.tsx
  site/src/components/Tabs/Tabs.tsx
  site/src/components/UsersLayout/UsersLayout.tsx
  site/src/pages/WorkspacesPage/filter/filter.tsx
  site/src/theme/mui.ts
Labels: hotfix

#10758 refactor(site): add minor tweaks to the workspace delete dialog
  site/src/components/Dialogs/Dialog.tsx
  site/src/pages/WorkspacePage/WorkspaceDeleteDialog/WorkspaceDeleteDialog.tsx
  site/src/pages/WorkspacesPage/WorkspacesPageView.tsx
Labels: hotfix

#10757 refactor(site): replace secondary by primary color
  site/src/components/TemplateFiles/TemplateFiles.tsx
  site/src/components/Timeline/TimelineEntry.tsx
  site/src/hooks/useClickableTableRow.ts
  site/src/pages/GroupsPage/GroupsPageView.tsx
  site/src/pages/TemplateSettingsPage/Sidebar.tsx
  site/src/pages/WorkspaceSettingsPage/Sidebar.tsx
Labels: hotfix

#10756 refactor(site): add minor improvements to the schedule controls
  site/src/pages/WorkspacePage/WorkspaceStats.tsx
  site/src/utils/schedule.ts
Labels: hotfix

#10765 chore: lint sink_test.go
  cli/cliutil/sink_test.go
Labels: hotfix

#10770 docs: add v2.4.1 changelog
  docs/changelogs/README.md
  docs/changelogs/v2.4.0.md
Labels: hotfix

#10773 fix: set `ignore_changes` on EC2 example templates
  examples/templates/aws-linux/main.tf
  examples/templates/aws-windows/main.tf
Labels: docs, bug

#10779 docs: align CODER_HTTP_ADDRESS with document
  coder.env
Labels: community

#10780 docs: migrate all deprecated `CODER_ADDRESS `to `CODER_HTTP_ADDRESS`
  docs/admin/high-availability.md
  docs/install/kubernetes.md
  examples/lima/coder.yaml
  helm/coder/README.md
Labels: community

#10783 fix(docs): fix a broken link
  docs/enterprise.md
Labels: hotfix

#10768 refactor(site): refactor login screen
  .vscode/settings.json
  site/src/@types/mui.d.ts
  site/src/pages/LoginPage/LoginPage.test.tsx
  site/src/pages/LoginPage/LoginPageView.tsx
  site/src/pages/LoginPage/OAuthSignInForm.tsx
  site/src/pages/LoginPage/PasswordSignInForm.tsx
  site/src/pages/LoginPage/SignInForm.stories.tsx
  site/src/pages/LoginPage/SignInForm.tsx
  site/src/pages/LoginPage/SignInForm.types.ts
  site/src/theme/constants.ts
  site/src/theme/mui.ts
Labels: hotfix

#10792 fix: prevent alt text from appearing if OIDC icon fail to load
  site/src/pages/LoginPage/OAuthSignInForm.tsx
Labels: hotfix

#10798 chore: remove theme experiment
  coderd/apidoc/docs.go
  coderd/apidoc/swagger.json
  codersdk/deployment.go
  docs/api/schemas.md
  site/src/api/typesGenerated.ts
Labels: hotfix

#10797 fix(site): correctly interpret timezone based on offset in `formatOffset`
  site/src/pages/TemplatePage/TemplateInsightsPage/TemplateInsightsPage.tsx
Labels: hotfix

#10825 chore: refactoring to move the notes at top
  docs/CONTRIBUTING.md
Labels: hotfix

#10826 test: skip flaky HealthyWithNodeDegraded
  coderd/healthcheck/derphealth/derp_test.go
Labels: hotfix

#10837 fix(site): use correct default insights time for day interval
  site/src/pages/TemplatePage/TemplateInsightsPage/TemplateInsightsPage.tsx
Labels: hotfix

#10838 fix(site): fix tabs
  site/src/components/Tabs/Tabs.stories.tsx
  site/src/components/Tabs/Tabs.tsx
Labels: hotfix

#10839 chore(site): ignore chromatic changes on syntax highlight
  site/src/components/SyntaxHighlighter/SyntaxHighlighter.tsx
Labels: hotfix

#10840 fix(docs): disable CODER_DERP_SERVER_STUN_ADDRESSES correctly
  docs/install/offline.md
Labels: community

#10898 fix: hide groups in account page if not enabled
  site/src/pages/UserSettingsPage/AccountPage/AccountPage.tsx
Labels: hotfix

#10903 chore(site): use variable font for inter
  site/jest.config.ts
  site/package.json
  site/pnpm-lock.yaml
  site/src/components/WorkspaceBuildLogs/WorkspaceBuildLogs.tsx
  site/src/theme/constants.ts
  site/src/theme/globalFonts.ts
Labels: hotfix

#10924 fix: numerical validation grammer
  coderd/activitybump_internal_test.go
  site/src/utils/richParameters.ts
Labels: site

#10934 chore(go.mod): update github.com/coder/ssh
  go.mod
  go.sum
Labels: hotfix
