Repository coder/coder, pull requests merged in 2023-07, with the labels that each got.

#8312 chore(dogfood): add `libssl-dev` to image
  dogfood/Dockerfile
Labels: hotfix

#8322 chore: pin terraform to 1.5.2
  .github/actions/setup-tf/action.yaml
  .github/workflows/ci.yaml
  .github/workflows/nightly-gauntlet.yaml
  scripts/Dockerfile.base
Labels: hotfix

#8317 fix(cli)!: protect client Logger and refactor cli scaletest tests
  cli/agent.go
  cli/root.go
  cli/scaletest_test.go
  cli/ssh.go
  cli/ssh_test.go
  coderd/deployment_test.go
  codersdk/agentsdk/agentsdk.go
  codersdk/client.go
  codersdk/client_internal_test.go
  enterprise/coderd/appearance_test.go
  scaletest/agentconn/run.go
  scaletest/createworkspaces/run.go
  scaletest/createworkspaces/run_test.go
  scaletest/reconnectingpty/run.go
  scaletest/workspacebuild/run.go
  scaletest/workspacebuild/run_test.go
  scaletest/workspacetraffic/run.go
  testutil/race.go
  testutil/race_off.go
  testutil/race_on.go
Labels: release/breaking

#8340 chore: upgrade node version on CI to match workspace version
  .github/actions/setup-node/action.yaml
  .github/workflows/ci.yaml
Labels: hotfix

#8354 chore(dogfood): add docker compose
  .github/workflows/dogfood.yaml
  dogfood/Dockerfile
Labels: hotfix

#8355 chore: temporarily skip prisma scan
  .github/workflows/security.yaml
Labels: hotfix

#8339 refactor(cli)!: move scaletest to exp/scaletest
  cli/exp.go
  cli/exp_scaletest.go
  cli/exp_scaletest_test.go
  cli/root.go
  cli/testdata/coder_--help.golden
  docs/cli.md
  docs/cli/scaletest.md
  docs/cli/scaletest_cleanup.md
  docs/cli/scaletest_create-workspaces.md
  docs/cli/scaletest_workspace-traffic.md
  docs/manifest.json
  scaletest/lib/coder_workspacetraffic.sh
  scaletest/scaletest.sh
Labels: release/breaking

#8368 fix(site): resize terminal when alert is dismissed
  site/src/pages/TerminalPage/TerminalPage.tsx
  site/src/pages/TerminalPage/TerminalPageAlert.tsx
Labels: hotfix

#8383 chore(.golangci.yaml): make gocyclo slightly more sensitive
  .golangci.yaml
  scripts/apitypings/main.go
Labels: hotfix

#8389 chore: go mod tidy
  go.mod
  go.sum
Labels: chore

#8409 refactor(site): adjust the proxy menu design
  site/src/components/Navbar/NavbarView.tsx
  site/src/components/ProxyStatusLatency/ProxyStatusLatency.tsx
Labels: hotfix

#8410 refactor(site): re-design proxies table
  site/src/pages/UserSettingsPage/WorkspaceProxyPage/WorkspaceProxyRow.tsx
Labels: hotfix

#8412 chore(cli): unhide `netcheck` command
  cli/netcheck.go
  cli/root.go
  cli/testdata/coder_--help.golden
  cli/testdata/coder_netcheck_--help.golden
  docs/cli.md
  docs/cli/netcheck.md
  docs/manifest.json
Labels: hotfix

#8411 fix: use `expires_in` field for git device refresh
  coderd/gitauth/oauth.go
  coderd/gitauth_test.go
Labels: hotfix

#8428 feat: expand wsproxy settings page by default
  site/src/pages/UserSettingsPage/WorkspaceProxyPage/WorkspaceProxyRow.tsx
Labels: hotfix

#8424 fix(dogfood): use gcr.io/coder-dev-1/alpine mirror to fix rate limit
  dogfood/Dockerfile
Labels: hotfix

#7942 feat: add template info tags to `coderd_agents_up` metric
  coderd/database/dbfake/dbfake.go
  coderd/database/modelqueries.go
  coderd/database/queries.sql.go
  coderd/database/queries/workspaces.sql
  coderd/prometheusmetrics/prometheusmetrics.go
  coderd/prometheusmetrics/prometheusmetrics_test.go
Labels: community

#8433 chore: upgrade Go to 1.20.6
  .github/actions/setup-go/action.yaml
Labels: hotfix

#8431 docs: add note on recommended Azure LB
  docs/install/kubernetes.md
Labels: docs

#8452 chore: remove invalid dependabot config for example templates
  .github/dependabot.yaml
Labels: hotfix

#8421 feat!: add table format to 'coder license ls'
  codersdk/licenses.go
  docs/cli/licenses_list.md
  enterprise/cli/licenses.go
  enterprise/cli/licenses_test.go
  enterprise/cli/testdata/coder_licenses_list_--help.golden
  enterprise/coderd/licenses_test.go
Labels: release/breaking

#8432 chore: server header specifies if wsproxy
  cli/server.go
  enterprise/cli/proxyserver.go
Labels: hotfix

#8256 docs: add devcontainer templates
  docs/images/templates/devcontainers.png
  docs/manifest.json
  docs/templates/devcontainers.md
  examples/templates/devcontainer-docker/README.md
  examples/templates/devcontainer-docker/main.tf
  examples/templates/devcontainer-kubernetes/README.md
  examples/templates/devcontainer-kubernetes/main.tf
Labels: docs

#8459 refactor(site): update build log to be displayed only on active statuses
  site/.storybook/preview.jsx
  site/src/app.tsx
  site/src/components/Workspace/Workspace.tsx
  site/src/components/WorkspaceActions/WorkspaceActions.tsx
  site/src/contexts/LocalPreferencesContext.tsx
  site/src/pages/WorkspacePage/WorkspaceBuildLogsSection.tsx
  site/src/pages/WorkspacePage/WorkspaceReadyPage.tsx
Labels: hotfix

#8406 docs: fix git credentials file name
  docs/templates/modules.md
Labels: community

#8480 chore: upgrade `github.com/codeclysm/extract` to `v3.1.1`
  cli/templatepull.go
  cli/templatepull_test.go
  go.mod
  go.sum
Labels: hotfix

#8490 fix(scaletest/terraform): fix prometheus namespace deps, disable auto-upgrade
  scaletest/terraform/gcp_cluster.tf
  scaletest/terraform/prometheus.tf
Labels: hotfix

#8506 chore: fuzzy match alpine terraform version
  scripts/Dockerfile.base
Labels: hotfix

#7790 fix: add some missing workspace updates
  coderd/coderdtest/coderdtest.go
  coderd/provisionerdserver/provisionerdserver.go
  coderd/workspaces.go
  coderd/workspaces_test.go
  provisionerd/runner/runner.go
Labels: stale

#8530 fix: devcontainer template workspace directory
  examples/templates/devcontainer-kubernetes/main.tf
Labels: community

#8534 chore: remove unmaintained `8Bitz0/coder-rust-template` template
  examples/templates/community-templates.md
Labels: community

#8553 refactor(site): redirect to the workspace page after update parameters
  site/src/pages/WorkspaceSettingsPage/WorkspaceParametersPage/WorkspaceParametersPage.tsx
Labels: hotfix

#8555 chore: remove buggy comment reaction from `deploy-pr.yaml`
  .github/workflows/pr-deploy.yaml
Labels: hotfix

#8559 chore: do not cancel in progress runs in `pr-deploy.yaml`
  .github/workflows/pr-deploy.yaml
Labels: hotfix

#8558 fix(cli): unskip test and explicitly set --host in test cmd invocation
  cli/stat_test.go
Labels: hotfix

#8564 fix(site): remove extra spacing on template variables page
  site/src/pages/TemplateSettingsPage/TemplateVariablesPage/TemplateVariablesPageView.tsx
Labels: hotfix

#8565 refactor(site): add sticky option to the build logs
  site/src/components/WorkspaceBuildLogs/WorkspaceBuildLogs.tsx
  site/src/pages/WorkspacePage/WorkspaceBuildLogsSection.tsx
Labels: hotfix

#8569 chore(coderd): require api key to access derpmap
  coderd/coderd.go
Labels: hotfix

#8528 fix!: remove startup logs eof for streaming
  cli/cliui/agent.go
  cli/cliui/agent_test.go
  coderd/workspaceagents.go
  coderd/workspaceagents_test.go
  codersdk/agentsdk/agentsdk.go
Labels: release/breaking

#8567 feat(helm): add commandArgs for custom entrypoint
  helm/templates/coder.yaml
  helm/tests/chart_test.go
  helm/tests/testdata/command_args.golden
  helm/tests/testdata/command_args.yaml
  helm/values.yaml
Labels: feature

#8258 feat(site): increase max workspace lifetime TTL validation to 30 days
  coderd/database/migrations/000038_template_max_ttl_cap_7_days.up.sql
  coderd/workspaces.go
  coderd/workspaces_test.go
  site/src/components/WorkspaceScheduleForm/WorkspaceScheduleForm.test.ts
  site/src/components/WorkspaceScheduleForm/WorkspaceScheduleForm.tsx
  site/src/i18n/en/createTemplatePage.json
  site/src/i18n/en/templateSettingsPage.json
  site/src/pages/CreateTemplatePage/CreateTemplateForm.tsx
  site/src/pages/TemplateSettingsPage/TemplateSchedulePage/TemplateScheduleForm/formHelpers.tsx
  site/src/pages/TemplateSettingsPage/TemplateSchedulePage/TemplateSchedulePage.test.tsx
Labels: community

#8597 fix: update permissions for /deploy-pr comment
  .github/workflows/pr-deploy.yaml
Labels: hotfix

#8604 chore: remove duplicate logger name in wsproxy ServerTailnet
  enterprise/wsproxy/wsproxy.go
Labels: hotfix

#8606 docs: add link to CODER_DOCS_URL
  docs/install/offline.md
Labels: hotfix

#8608 fix: agent health copy
  site/src/components/WorkspacesTable/WorkspacesRow.tsx
Labels: hotfix

#8612 test(coderd): fix `TestWorkspaceWatcher` flake
  coderd/workspaces_test.go
Labels: hotfix

#8618 fix(scaletest): deploy external provisionerd
  scaletest/terraform/coder.tf
  scaletest/terraform/gcp_cluster.tf
  scaletest/terraform/vars.tf
Labels: scaletest

#8628 test: ignore more spurious pgcoord errors
  enterprise/tailnet/pgcoord.go
Labels: hotfix

#8616 chore: add offlinedocs to `ts` filter in ci.yaml
  .github/workflows/ci.yaml
Labels: hotfix

#8641 test: fix race in `templateedit_test.go`
  cli/templateedit_test.go
Labels: hotfix

#8427 chore: improve workspace proxy copy
  site/src/components/Navbar/NavbarView.tsx
  site/src/pages/UserSettingsPage/WorkspaceProxyPage/WorkspaceProxyPage.tsx
Labels: stale

#8648 docs: add steps for postgres SSL cert config
  docs/install/kubernetes.md
Labels: docs

#8660 fix(site): send build parameters over the confirmation dialog on restart
  site/src/components/WorkspaceActions/BuildParametersPopover.tsx
  site/src/pages/WorkspacePage/WorkspacePage.test.tsx
  site/src/pages/WorkspacePage/WorkspaceReadyPage.tsx
  site/src/pages/WorkspacePage/hooks.ts
Labels: hotfix

#8588 feat(cli): check if dotfiles install script is executable
  cli/dotfiles.go
  docs/dotfiles.md
Labels: community

#8539 fix: do not wait for devcontainer template volume claim bound
  examples/templates/devcontainer-kubernetes/main.tf
Labels: community

#8674 chore: enable deployments for PR deployments
  .github/workflows/pr-deploy.yaml
Labels: hotfix

#8676 chore: install `coder-logstream-kube` for PR deployments
  .github/workflows/pr-deploy.yaml
Labels: hotfix

#8677 chore: do not deploy a PR on deleted comment
  .github/workflows/pr-deploy.yaml
Labels: hotfix

#8678 fix: fix a typo in deploy-pr.yaml
  .github/workflows/pr-deploy.yaml
Labels: hotfix

#8685 chore(scripts): support Sapling in project_root
  scripts/lib.sh
Labels: hotfix

#8691 docs: fix a broken link
  docs/admin/automation.md
Labels: hotfix

#8692 ci: reduce duplication
  .github/actions/setup-sqlc/action.yaml
  .github/workflows/ci.yaml
  .github/workflows/pr-deploy.yaml
  .github/workflows/security.yaml
Labels: hotfix

#8687 chore(scripts): handle Sapling in version.sh
  scripts/version.sh
Labels: hotfix

#8700 fix(site): fix error 'Reduce of empty array with no initial value'
  site/src/contexts/useProxyLatency.ts
Labels: hotfix

#8703 docs: add missing manifest for deployment logs doc
  docs/manifest.json
Labels: docs, bug

#8704 feat(helm)!: set enableDeployments default to true
  helm/values.yaml
Labels: feature, release/breaking

#8708 docs: cleanup jfrog
  docs/platforms/jfrog.md
Labels: hotfix

#8709 docs: slightly improve wording in jfrog.md
  docs/platforms/jfrog.md
Labels: hotfix

#8712 docs: fix duplicate sentence
  cli/portforward.go
  cli/testdata/coder_--help.golden
  cli/testdata/coder_port-forward_--help.golden
  docs/cli.md
  docs/cli/port-forward.md
  docs/manifest.json
Labels: hotfix

#8718 fix(coderd): update icon url to the right one
  cli/templateedit_test.go
  coderd/insights.go
  coderd/templates_test.go
Labels: hotfix

#8719 feat(site): add terminal icon
  site/static/icon/terminal.svg
Labels: hotfix

#8724 docs: explain how to install the JFrog VS Code extension
  docs/platforms/jfrog.md
Labels: hotfix

#8725 fix: use gh cli in pr deploy workflow
  .github/workflows/pr-deploy.yaml
Labels: hotfix

#8720 test: improve pr deployments
  .github/workflows/pr-deploy.yaml
Labels: hotfix

#8728 fix: fix a small issue with pr_deploy.yaml
  .github/workflows/pr-deploy.yaml
Labels: hotfix

#8729 fix: revert back to curl in deply-pr.yaml
  .github/workflows/pr-deploy.yaml
Labels: hotfix

#8730 fix(enterprise): ensure creating a SCIM user is idempotent
  enterprise/coderd/scim.go
  enterprise/coderd/scim_test.go
Labels: hotfix

#8731 fix: remove the usage of -u flag
  .github/workflows/pr-deploy.yaml
Labels: hotfix

#8732 test: remove erroneous quotes from deploy-pr.yaml
  .github/workflows/pr-deploy.yaml
Labels: hotfix

#8733 test: fix comments in `deploy-pr.yaml`
  .github/workflows/pr-deploy.yaml
Labels: hotfix

#8734 ci: add a missing end quote and use https:// with `CODER_ACCESS_URL`
  .github/workflows/pr-deploy.yaml
Labels: hotfix

#8741 fix: fix failed 32-bit builds
  enterprise/coderd/coderd.go
Labels: hotfix

#8744 fix(tailnet): track agent names for http debug
  enterprise/tailnet/coordinator.go
  enterprise/tailnet/pgcoord.go
  go.mod
  tailnet/coordinator.go
  tailnet/trackedconn.go
Labels: hotfix

#8747 chore(scripts): use fake semver when using sapling
  scripts/version.sh
Labels: hotfix

#8749 fix(site): fix latency values
  site/src/pages/TemplatePage/TemplateInsightsPage/TemplateInsightsPage.tsx
Labels: hotfix

#8750 fix: request trial after password is validated
  coderd/users.go
Labels: hotfix

#8751 fix(cli): apply log-filter to debug logs only
  cli/server.go
Labels: hotfix

#8754 chore: fix `Test_parseInsightsStartAndEndTime` test
  coderd/insights_internal_test.go
Labels: hotfix

#8753 chore: attempt to fix windows goleak failures
  cli/templateedit_test.go
Labels: hotfix

#8755 chore: fix workspace proxy flake
  enterprise/coderd/workspaceproxy.go
Labels: hotfix

#8765 feat(site): add restart button when workspace is unhealthy
  site/src/components/Workspace/Workspace.tsx
Labels: hotfix

#8764 ci: further improve pr deployments
  .github/workflows/pr-cleanup.yaml
  .github/workflows/pr-deploy.yaml
  scripts/deploy-pr.sh
Labels: hotfix

#8767 ci: prevent running pr-deploy.yaml on all comments
  .github/workflows/pr-deploy.yaml
Labels: hotfix

#8770 ci: add DB to PR deploys
  .github/workflows/pr-deploy.yaml
Labels: hotfix

#8736 chore(docs): small fixes in JFrog integration docs
  docs/platforms/jfrog.md
Labels: community

#8776 ci: optimize chromatic
  .github/workflows/ci.yaml
Labels: hotfix

#8777 fix: improve the language of the template insights page
  site/src/components/DAUChart/DAUChart.tsx
  site/src/pages/TemplatePage/TemplateInsightsPage/TemplateInsightsPage.tsx
Labels: hotfix

#8781 refactor(site): sort proxies in navbar by latency
  site/src/components/Navbar/NavbarView.tsx
Labels: hotfix

#8790 ci: update secret name in pr-cleanup.yaml
  .github/workflows/pr-cleanup.yaml
Labels: hotfix

#8798 chore: mark `site/src/api/typesGenerated.ts` as generated
  .gitattributes
Labels: hotfix

#8810 chore: reenable prisma image scan
  .github/workflows/security.yaml
Labels: hotfix

#8820 chore: increase fmt timeout
  .github/workflows/ci.yaml
Labels: hotfix
