Repository coder/coder, pull requests merged in 2023-03, with the labels that each got.

#6043 fix: outdated message in latency tooltip
  site/src/components/Resources/AgentLatency.tsx
Labels: stale

#6302 docs: clearer postgres sizing recommendations
  docs/admin/scale.md
Labels: stale

#6548 fix!: Disallow access urls without valid scheme
  cli/server.go
Labels: release/breaking

#6494 chore: fix workspace audit log flake
  coderd/workspaces_test.go
Labels: stale

#6663 docs: add k8s & aws to offline Dockerfile
  docs/install/offline.md
Labels: docs

#6165 docs: add openshift install
  docs/install/openshift.md
  docs/manifest.json
Labels: docs

#6583 docs: clean up OIDC duplicates
  docs/admin/auth.md
Labels: docs

#6703 feat: podAnnotations
  go.mod
  go.sum
  helm/templates/coder.yaml
  helm/tests/testdata/default_values.golden
  helm/tests/testdata/tls.golden
  helm/values.yaml
Labels: feature

#6788 docs: clarify mac docker install
  docs/install/docker.md
Labels: docs
