Repository coder/coder, pull requests merged in 2023-12, with the labels that each got.

#10982 fix(helm/provisioner): run helm dependency update
  helm/provisioner/tests/chart_test.go
Labels: hotfix

#10199 feat: add workspace_id, owner_name to agent manifest
  coderd/apidoc/docs.go
  coderd/apidoc/swagger.json
  coderd/workspaceagents.go
  coderd/workspaceagents_test.go
  codersdk/agentsdk/agentsdk.go
  docs/api/agents.md
  docs/api/schemas.md
Labels: community

#11028 fix(site): fix filter font-size
  site/src/components/Filter/OptionItem.stories.tsx
  site/src/components/Filter/filter.tsx
Labels: hotfix

#11040 fix: disable prefetches for audits table
  site/src/api/queries/audits.ts
  site/src/hooks/usePaginatedQuery.ts
Labels: hotfix

#11041 fix: increase default staleTime for paginated data
  site/src/hooks/usePaginatedQuery.ts
Labels: hotfix

#11045 feat: document suspended users not consuming seat
  docs/admin/users.md
Labels: docs

#11061 chore(site): refactor pagination text
  site/src/components/PaginationWidget/PaginationHeader.tsx
Labels: hotfix

#11062 fix(site): fetch health data only if has permissions
  site/src/components/Dashboard/DeploymentBanner/DeploymentBanner.tsx
Labels: hotfix

#11072 fix(site): fix clickable props on the workspace table row
  site/src/pages/WorkspacesPage/WorkspacesTable.tsx
Labels: hotfix

#11101 fix(site): hide ws proxy on menu when disabled
  site/src/pages/HealthPage/AccessURLPage.stories.tsx
  site/src/pages/HealthPage/DERPPage.stories.tsx
  site/src/pages/HealthPage/DERPRegionPage.stories.tsx
  site/src/pages/HealthPage/DatabasePage.stories.tsx
  site/src/pages/HealthPage/HealthLayout.tsx
  site/src/pages/HealthPage/WebsocketPage.stories.tsx
  site/src/pages/HealthPage/WebsocketProxyPage.stories.tsx
  site/src/pages/HealthPage/storybook.tsx
Labels: hotfix

#11109 docs: add license and template insights prom metrics
  docs/admin/prometheus.md
  scripts/metricsdocgen/metrics
Labels: docs

#11113 chore(site): enable react-query cache
  site/src/App.tsx
Labels: hotfix

#11120 ci: update `tj-actions/branch-names` action in dogfood.yaml
  .github/workflows/dogfood.yaml
Labels: hotfix

#11144 fix: remove URL desyncs when trying to search users table
  site/src/api/queries/users.ts
  site/src/pages/UsersPage/UsersPage.tsx
Labels: hotfix

#11150 fix(coderd/autobuild): wait for template version job in TestExecutorInactiveWorkspace
  coderd/autobuild/lifecycle_executor_test.go
Labels: hotfix

#11155 chore(site): update test entities
  site/src/testHelpers/entities.ts
Labels: site, hotfix

#11143 fix: use correct permission when determining orphan deletion privileges
  site/src/pages/WorkspacePage/WorkspaceReadyPage.tsx
Labels: hotfix

#11159 docs: add text to docs mentioning appearance settings for oidc sign-on page
  docs/admin/auth.md
Labels: docs, hotfix

#11164 ci: set flux version to 2.1.2
  .github/workflows/ci.yaml
Labels: hotfix

#11188 ci: add wildcard support to fly.io wsproxies
  .github/fly-wsproxies/paris-coder.toml
  .github/fly-wsproxies/sao-paulo-coder.toml
  .github/fly-wsproxies/sydney-coder.toml
Labels: hotfix

#11193 ci: bump memory to 1024 MB for fly.io proxies
  .github/fly-wsproxies/paris-coder.toml
  .github/fly-wsproxies/sao-paulo-coder.toml
  .github/fly-wsproxies/sydney-coder.toml
Labels: hotfix

#11194 ci: revert fly proxies to shared cpu type
  .github/fly-wsproxies/paris-coder.toml
  .github/fly-wsproxies/sao-paulo-coder.toml
  .github/fly-wsproxies/sydney-coder.toml
Labels: hotfix

#11195 ci: update wildcard url in fly-wsproxies configuration files
  .github/fly-wsproxies/paris-coder.toml
  .github/fly-wsproxies/sao-paulo-coder.toml
  .github/fly-wsproxies/sydney-coder.toml
Labels: hotfix

#11209 fix(site): fix pending indicator color
  site/src/theme/dark/experimental.ts
  site/src/utils/workspace.tsx
Labels: hotfix

#11212 fix(site): fix pending color
  site/src/theme/darkBlue/experimental.ts
Labels: hotfix

#11213 fix(site): fix initial body background color
  site/index.html
Labels: hotfix

#11215 fix: fix auto theme
  site/src/theme/index.ts
Labels: hotfix

#11220 docs: add v2.5.1 changelog
  docs/changelogs/README.md
  docs/changelogs/v2.5.1.md
Labels: hotfix

#11233 chore: upgrade code-server version to 4.19.1 for docker
  examples/templates/docker/main.tf
Labels: community

#11189 feat!: move workspace renames behind flag, disable by default
  cli/rename_test.go
  cli/server.go
  cli/testdata/coder_list_--output_json.golden
  cli/testdata/coder_server_--help.golden
  cli/testdata/server-config.yaml.golden
  coderd/apidoc/docs.go
  coderd/apidoc/swagger.json
  coderd/coderd.go
  coderd/coderdtest/coderdtest.go
  coderd/workspaces.go
  coderd/workspaces_test.go
  codersdk/deployment.go
  codersdk/workspaces.go
  docs/api/general.md
  docs/api/schemas.md
  docs/api/workspaces.md
  docs/cli/server.md
  enterprise/cli/testdata/coder_server_--help.golden
  site/src/api/typesGenerated.ts
  site/src/pages/WorkspaceSettingsPage/WorkspaceSettingsForm.tsx
  site/src/pages/WorkspaceSettingsPage/WorkspaceSettingsPage.test.tsx
  site/src/pages/WorkspaceSettingsPage/WorkspaceSettingsPageView.stories.tsx
  site/src/testHelpers/entities.ts
Labels: release/breaking

#11254 docs: fix a broken link
  docs/templates/modules.md
Labels: hotfix

#11259 chore: remove unused input from deploy-pr workflow
  .github/workflows/pr-deploy.yaml
Labels: hotfix

#11260 fix(site): fix template editor filetree navigation
  site/src/pages/TemplateVersionEditorPage/FileTreeView.tsx
Labels: hotfix

#11296 docs: add guidelines for debugging group sync
  docs/admin/auth.md
Labels: hotfix

#11318 fix: fix name for external auth connections
  site/src/pages/UserSettingsPage/ExternalAuthPage/ExternalAuthPageView.tsx
Labels: hotfix

#11320 docs: add v2.6.0 changelog
  docs/changelogs/README.md
  docs/changelogs/images/light-theme.png
  docs/changelogs/v2.6.0.md
Labels: hotfix

#11321 fix: prevent UI from jumping around when selecting workspaces
  site/src/components/PaginationWidget/PaginationHeader.tsx
  site/src/pages/WorkspacesPage/WorkspacesPageView.tsx
Labels: hotfix

#11322 docs: fix broken link to JFrog module
  docs/platforms/jfrog.md
Labels: community

#11105 test(site/e2e): catch missing agent defaults in `fillResource`
  site/e2e/helpers.ts
Labels: stale

#11330 ci: fix close reason type for stale issues
  .github/workflows/stale.yaml
Labels: hotfix

#11334 fix(docs): add missing scoped token resource to JFrog docs
  docs/platforms/jfrog.md
Labels: hotfix

#11335 chore(examples/jfrog): always install the latest JFrog extension
  examples/jfrog/docker/main.tf
Labels: hotfix

#11339 chore(dogfood): update nodejs installation method
  .github/workflows/dogfood.yaml
  dogfood/Dockerfile
  dogfood/files/etc/apt/sources.list.d/nodesource.list
  dogfood/files/usr/share/keyrings/nodesource.gpg
Labels: hotfix

#11343 chore(site): update miscellaneous svg icons
  site/src/theme/icons.json
  site/static/icon/aws-dark.svg
  site/static/icon/aws-light.svg
  site/static/icon/aws.svg
  site/static/icon/azure.svg
  site/static/icon/docker-white.svg
  site/static/icon/docker.svg
  site/static/icon/gcp.png
Labels: hotfix

#11341 fix(examples/templates/nomad-docker): ignore `NOMAD_NAMESPACE` and `NOMAD_REGION` when Coder is running in nomad
  examples/templates/nomad-docker/main.tf
Labels: community
