Repository coder/coder, pull requests merged in 2023-10, with the labels that each got.

#9987 test(site): e2e: wait for empty workspaces
  site/e2e/global.setup.ts
  site/src/pages/WorkspacesPage/WorkspacesTable.tsx
Labels: hotfix

#10005 docs: add support to enterprise features
  docs/enterprise.md
Labels: docs

#9976 feat(cli): add reverse tunnelling SSH support for unix sockets
  cli/remoteforward.go
  cli/ssh_test.go
Labels: community

#10008 chore(dogfood): rename `project_directory` to `folder`
  dogfood/main.tf
Labels: hotfix

#10017 chore: update multiple git providers docs
  codersdk/deployment.go
  docs/admin/external-auth.md
  docs/enterprise.md
  enterprise/coderd/coderd.go
  enterprise/coderd/license/license.go
  enterprise/coderd/license/license_test.go
  site/src/api/typesGenerated.ts
Labels: hotfix

#10020 chore: check for valid regex in git auth configs
  coderd/workspaceagents.go
Labels: hotfix

#10021 fix(site): fix navbar hover
  site/src/components/Dashboard/Navbar/NavbarView.tsx
Labels: hotfix

#10025 fix(site): remove 48 weeks option
  site/src/pages/TemplatePage/TemplateInsightsPage/WeekPicker.tsx
Labels: hotfix

#10033 fix(coderd/database/dbtestutil): fix typo in pgDump
  coderd/database/dbtestutil/db.go
Labels: hotfix

#10036 fix(site): fix orphan values on insights
  site/src/pages/TemplatePage/TemplateInsightsPage/TemplateInsightsPage.stories.tsx
  site/src/pages/TemplatePage/TemplateInsightsPage/TemplateInsightsPage.tsx
Labels: hotfix

#10044 chore: revert docs for git-auth until release
  docs/admin/git-providers.md
  docs/manifest.json
Labels: hotfix

#10043 fix(coderd): fetch workspace agent scripts and log sources using system auth ctx
  coderd/workspaceagents.go
  coderd/workspaceagents_test.go
Labels: hotfix

#10051 fix: silence bash deprecation warning on macOS runners
  .github/workflows/ci.yaml
Labels: hotfix

#10055 docs: add v2.2.1 changelog
  docs/changelogs/README.md
  docs/changelogs/v2.2.1.md
  site/src/components/DeploySettingsLayout/Sidebar.tsx
Labels: hotfix

#10062 docs: update offline tf provider config
  docs/install/offline.md
Labels: docs, bug

#10059 fix(site): fix chart label depending on interval
  site/src/components/ActiveUserChart/ActiveUserChart.tsx
Labels: hotfix

#10060 fix(site): fix users page for template admins
  site/src/pages/UsersPage/UsersPage.tsx
Labels: hotfix

#10066 chore: increase `ForceCancelInterval` for test flakes
  coderd/coderdtest/coderdtest.go
Labels: hotfix

#10071 chore: add mod replace wireguard-go to fix race condition
  go.mod
  go.sum
Labels: hotfix

#10079 chore: use JobStatus computed from the db
  coderd/database/db2sdk/db2sdk_test.go
  coderd/templateversions.go
Labels: hotfix

#10089 fix: add build status favicons based on system theme
  site/src/pages/WorkspacePage/WorkspaceReadyPage.tsx
  site/static/favicons/favicon-error-dark.png
  site/static/favicons/favicon-error-dark.svg
  site/static/favicons/favicon-error-light.png
  site/static/favicons/favicon-error-light.svg
  site/static/favicons/favicon-running-dark.png
  site/static/favicons/favicon-running-dark.svg
  site/static/favicons/favicon-running-light.png
  site/static/favicons/favicon-running-light.svg
  site/static/favicons/favicon-success-dark.png
  site/static/favicons/favicon-success-dark.svg
  site/static/favicons/favicon-success-light.png
  site/static/favicons/favicon-success-light.svg
  site/static/favicons/favicon-warning-dark.png
  site/static/favicons/favicon-warning-dark.svg
  site/static/favicons/favicon-warning-light.png
  site/static/favicons/favicon-warning-light.svg
Labels: hotfix

#10090 fix: use proper state in system theme
  site/src/pages/WorkspacePage/WorkspaceReadyPage.tsx
Labels: hotfix

#10092 fix: apply the same border for button groups
  site/src/theme/theme.ts
Labels: hotfix

#10091 fix(site): fix logo width on sign in
  site/src/pages/LoginPage/LoginPageView.tsx
Labels: hotfix

#10094 fix: use proper react hook for favicon theme
  site/src/pages/WorkspacePage/WorkspaceReadyPage.tsx
Labels: hotfix

#10097 fix: invert the favicon on dark mode
  site/src/pages/WorkspacePage/WorkspaceReadyPage.tsx
Labels: hotfix

#10107 fix: make the dark mode a bit less dark
  site/src/theme/colors.ts
Labels: hotfix

#10110 chore: fix servertailnet test flake
  coderd/tailnet.go
  tailnet/conn.go
Labels: hotfix

#10116 fix(coder): properly check for missing organization membership
  coderd/users.go
Labels: hotfix

#10140 fix: check for nil pointer in AwaitWorkspaceAgents
  coderd/coderdtest/coderdtest.go
Labels: hotfix

#10125 chore: add vault icon
  site/src/theme/icons.json
  site/static/icon/vault.svg
Labels: hotfix

#10145 feat: add `request_id` to HTTP trace spans
  coderd/httpmw/requestid.go
Labels: hotfix

#10146 fix: properly trim spaces so multi-line shebang executes
  agent/agentssh/agentssh.go
Labels: hotfix

#10147 chore: run `go mod tidy`
  go.mod
Labels: hotfix

#10155 fix: apply default `ExtraTokenKeys` to oauth
  coderd/externalauth/externalauth.go
Labels: hotfix

#10156 fix: use query to get external-auth by id
  coderd/workspaceagents.go
Labels: hotfix

#10173 fix(site): fix week range for insights
  site/src/pages/TemplatePage/TemplateInsightsPage/DateRange.tsx
  site/src/pages/TemplatePage/TemplateInsightsPage/TemplateInsightsPage.tsx
  site/src/pages/TemplatePage/TemplateInsightsPage/WeekPicker.tsx
  site/src/pages/TemplatePage/TemplateInsightsPage/utils.test.ts
  site/src/pages/TemplatePage/TemplateInsightsPage/utils.ts
Labels: hotfix

#10181 chore: fix lint failures
  cli/templatepull_test.go
  go.mod
  go.sum
Labels: hotfix

#10185 chore: upgrade Go to `1.20.10`
  .github/actions/setup-go/action.yaml
  .github/workflows/ci.yaml
Labels: hotfix

#10198 feat: add slackme module to dogfood
  dogfood/main.tf
Labels: hotfix

#10201 fix: append external auth env vars
  go.mod
  go.sum
  provisioner/terraform/provision.go
Labels: hotfix

#10212 fix(scaletest/dashboard): fix early exit due to validate
  cli/exp_scaletest.go
  scaletest/dashboard/config.go
  scaletest/dashboard/run.go
Labels: hotfix

#10215 chore(site): fix inconsistent fetching results on tests
  site/src/App.tsx
  site/src/pages/WorkspacePage/WorkspacePage.test.tsx
  site/src/testHelpers/renderHelpers.tsx
Labels: hotfix

#10221 docs: add v2.3.0 changelog
  docs/changelogs/README.md
  docs/changelogs/v2.3.0.md
Labels: hotfix

#10229 chore: recrop some icons for more consistent sizing
  site/static/icon/jax.svg
  site/static/icon/jfrog.svg
  site/static/icon/rust.svg
Labels: hotfix

#10233 fix: update create workspace button to recognize template names+display names
  site/src/pages/WorkspacesPage/WorkspacesButton.tsx
Labels: hotfix

#10243 docs: clarify external auth regex
  docs/admin/external-auth.md
Labels: docs

#10283 feat(site): decrease the number of statuses in the workspaces filter
  site/src/pages/WorkspacesPage/filter/menus.ts
Labels: hotfix

#10287 fix(site): do not return next page if the current size is lower than the limit
  site/src/api/queries/workspaceBuilds.ts
Labels: hotfix

#10291 chore: fix broken links in docs
  docs/changelogs/v2.3.0.md
  docs/templates/open-in-coder.md
Labels: hotfix

#10296 fix(site): fix state used to check if creating was loading
  site/src/pages/CreateWorkspacePage/CreateWorkspacePageView.tsx
Labels: hotfix

#10320 chore: delete filebrowser.db
  filebrowser.db
Labels: hotfix

#10317 chore: fix linting issues and generated files
  .github/actions/setup-sqlc/action.yaml
  Makefile
  cli/templates.go
  cli/templateversionarchive.go
  cli/templateversions.go
  coderd/database/generate.sh
  package.json
  site/build/tsconfig.tsbuildinfo
  site/package.json
Labels: hotfix

#10321 fix: set K8s deployment strategy to `Recreate`
  .github/pr-deployments/template/main.tf
  examples/templates/devcontainer-kubernetes/main.tf
  examples/templates/kubernetes/main.tf
Labels: bug

#10327 docs: update vscode web docs
  docs/ides/web-ides.md
  site/src/theme/icons.json
  site/static/icon/discord.svg
Labels: hotfix

#10328 ci(.github): set DataDog upload timeout
  .github/workflows/ci.yaml
Labels: hotfix

#10334 fix(site): fix tabs in the template layout
  site/src/components/Tabs/Tabs.tsx
  site/src/components/UsersLayout/UsersLayout.tsx
  site/src/pages/TemplatePage/TemplateLayout.tsx
Labels: hotfix

#10366 docs: fix additional cluster SA, role names
  docs/platforms/kubernetes/additional-clusters.md
Labels: docs, bug

#10371 docs: add v2.3.2 changelog
  docs/changelogs/README.md
  docs/changelogs/v2.3.2.md
Labels: hotfix

#10387 test(coderd): fix TestWorkspaceBuild flake
  coderd/workspacebuilds_test.go
Labels: hotfix

#10386 fix(agent): prevent metadata from being discarded if report is slow
  agent/agent.go
Labels: hotfix

#10385 test(agent): improve TestAgent_Session_TTY_MOTD_Update
  agent/agent_test.go
Labels: hotfix

#10275 fix(README.md): update installation link
  README.md
Labels: community

#10306 feat(provisioner): expose template version to provisioner
  provisioner/terraform/provision.go
Labels: community

#10404 chore(examples): fix a small typo
  examples/web-server/nginx/README.md
Labels: hotfix

#10406 chore: limit history to the last 30 runs/days for PR deploy and cleanup workflows
  .github/workflows/stale.yaml
Labels: hotfix

#10414 fix: disable tests broken by daylight savings
  codersdk/deployment_test.go
Labels: hotfix

#10324 feat: add tailnet and agent API definitions
  Makefile
  agent/proto/agent.pb.go
  agent/proto/agent.proto
  agent/proto/agent_drpc.pb.go
  tailnet/proto/tailnet.pb.go
  tailnet/proto/tailnet.proto
  tailnet/proto/tailnet_drpc.pb.go
Labels: stale

#10434 fix: add new aws regions to instance identity
  coderd/awsidentity/awsidentity.go
Labels: hotfix

#10435 docs: add v2.3.3 changelog
  docs/changelogs/README.md
  docs/changelogs/v2.3.3.md
Labels: hotfix

#10444 chore: revert "bump go.uber.org/goleak from 1.2.1 to 1.3.0"
  go.mod
  go.sum
Labels: hotfix
