Repository coder/coder, pull requests merged in 2023-06, with the labels that each got.

#7747 docs: describe gateway and internal certs
  docs/ides/gateway.md
Labels: docs

#7800 chore(dependabot): automate frontend team assignment for dependabot PR reviews
  .github/dependabot.yaml
Labels: chore

#7821 docs: add note on log truncation
  docs/workspaces.md
Labels: docs

#7822 docs: resolve README 404s
  docs/README.md
  docs/about/architecture.md
  docs/admin/configure.md
  docs/admin/high-availability.md
  docs/ides.md
  docs/install/binary.md
  docs/install/database.md
  docs/install/docker.md
  docs/install/install.sh.md
  docs/install/kubernetes.md
  docs/install/offline.md
  docs/install/packages.md
  docs/install/windows.md
  docs/manifest.json
  docs/networking/index.md
  docs/platforms/aws.md
  docs/platforms/azure.md
  docs/platforms/docker.md
  docs/platforms/google-cloud-platform.md
  docs/platforms/other.md
  docs/templates/index.md
  docs/templates/resource-persistence.md
  docs/workspaces.md
Labels: bug, docs

#7831 ci: skip DataDog upload for dependabot
  .github/actions/upload-datadog/action.yaml
Labels: hotfix

#7832 perf(provisioner/terraform): upgrade hc-install
  go.mod
  go.sum
  provisioner/terraform/install_test.go
Labels: hotfix

#7866 ci: run `dogfood.yaml` action upon action update
  .github/workflows/dogfood.yaml
Labels: hotfix

#7818 feat(site): add new filter to the users page
  site/src/components/Filter/filter.tsx
  site/src/components/Filter/menu.ts
  site/src/components/Filter/options.ts
  site/src/components/PaginationStatus/PaginationStatus.tsx
  site/src/pages/UsersPage/UsersFilter.tsx
  site/src/pages/UsersPage/UsersPage.tsx
  site/src/pages/UsersPage/UsersPageView.stories.tsx
  site/src/pages/UsersPage/UsersPageView.tsx
  site/src/pages/WorkspacesPage/WorkspacesPage.tsx
  site/src/pages/WorkspacesPage/WorkspacesPageView.stories.tsx
  site/src/pages/WorkspacesPage/WorkspacesPageView.tsx
  site/src/pages/WorkspacesPage/filter/autocompletes.ts
  site/src/pages/WorkspacesPage/filter/filter.tsx
  site/src/pages/WorkspacesPage/filter/menus.ts
  site/src/pages/WorkspacesPage/filter/options.ts
Labels: community

#7871 refactor(site): remove terminal padding and add border to bottom bar
  site/src/pages/TerminalPage/TerminalPage.tsx
Labels: hotfix, community

#7873 fix(site): update the template form when a value is changed
  site/src/pages/TemplateSettingsPage/TemplateGeneralSettingsPage/TemplateSettingsPage.tsx
  site/src/pages/TemplateSettingsPage/TemplateSettingsLayout.tsx
Labels: hotfix, community

#7875 docs: add docs for the available query filter for workspaces and users
  docs/admin/users.md
  docs/workspaces.md
Labels: community

#7858 feat: add metric for provisioner daemons
  cli/server.go
  provisionerd/provisionerd.go
  provisionerd/runner/runner.go
Labels: community

#7883 chore: upgrade openssl
  scripts/Dockerfile.base
Labels: hotfix

#7886 ci: rename `cron-weekly.yaml` to `weekly-docs.yaml`
  .github/workflows/weekly-docs.yaml
Labels: hotfix

#7888 fix(cli): remove remaining references to cliui.Styles.Code
  cli/root.go
  cli/server_slim.go
  enterprise/cli/proxyserver_slim.go
Labels: hotfix

#7906 fix(site): return correct user when using "me" on filter menu
  site/src/components/Filter/UserFilter.tsx
Labels: hotfix

#7835 feat(provisioner): add support for .tf.json templates
  provisioner/terraform/parameters.go
  provisioner/terraform/parse.go
  provisioner/terraform/provision_test.go
  provisionersdk/archive.go
  provisionersdk/archive_test.go
Labels: community

#7911 test(agent/agentssh): close SSH servers in all tests
  agent/agentssh/agentssh_internal_test.go
  agent/agentssh/agentssh_test.go
Labels: hotfix

#7819 chore: add scaletest convenience script
  .gitignore
  .prettierignore
  scaletest/README.md
  scaletest/lib/coder_init.sh
  scaletest/lib/coder_shim.sh
  scaletest/lib/coder_workspacetraffic.sh
  scaletest/scaletest.sh
  scaletest/terraform/README.md
  scaletest/terraform/coder.tf
  scaletest/terraform/coder_shim.sh
  scaletest/terraform/prometheus.tf
  scaletest/terraform/scenario-large.tfvars
  scaletest/terraform/scenario-medium.tfvars
  scaletest/terraform/scenario-small.tfvars
  scaletest/terraform/secrets.tfvars.tpl
  scaletest/workspacetraffic/run.go
  site/.eslintignore
  site/.prettierignore
Labels: chore, scaletest

#7917 chore(cli/configssh): add comment about wait and skip proxy
  cli/configssh.go
Labels: hotfix

#7918 docs(templates): fix docs for updated --wait flag
  docs/templates/index.md
Labels: hotfix

#7920 ci: prevent running nightly-gauntlet.yaml on PRs
  .github/workflows/nightly-gauntlet.yaml
Labels: hotfix

#7925 fix(enterprise): ensure scim usernames are validated
  coderd/users.go
  enterprise/coderd/scim.go
  enterprise/coderd/scim_test.go
Labels: hotfix

#7941 docs: add multi git providers to enterprise chart
  docs/enterprise.md
Labels: docs

#7943 ci: improve test parallelism
  .github/actions/setup-go/action.yaml
  .github/workflows/ci.yaml
  Makefile
Labels: hotfix

#7134 ci: skip ts or go tests based on changed files
  .github/workflows/ci.yaml
Labels: chore

#7974 fix(cli/ssh): fix lint error
  cli/ssh.go
Labels: hotfix

#7954 ci: improve Go caching
  .github/actions/setup-go/action.yaml
  .github/workflows/ci.yaml
  .golangci.yaml
  Makefile
  enterprise/cli/root_internal_test.go
Labels: hotfix

#7981 ci: reduce Windows parallelism
  .github/workflows/ci.yaml
Labels: hotfix

#7985 chore: prevent gen from rerunning every time
  Makefile
  site/package.json
Labels: hotfix

#7991 fix(docs): capture and export audit logs
  docs/admin/audit-logs.md
Labels: hotfix

#8002 chore: remove key comparison check to fix gitsshkey flake
  coderd/gitsshkey_test.go
Labels: hotfix

#8004 fix: scope errors to subtests to reduce flake
  enterprise/coderd/workspaceproxy_test.go
Labels: hotfix

#8019 feat(site): add documentation links to webterminal notifications
  site/src/components/WarningAlert/WarningAlert.stories.tsx
  site/src/pages/TerminalPage/TerminalPage.tsx
  site/src/pages/TerminalPage/TerminalPageAlert.stories.tsx
  site/src/pages/TerminalPage/TerminalPageAlert.tsx
Labels: community

#8036 fix(site): fix footer year
  site/src/pages/LoginPage/LoginPageView.tsx
Labels: hotfix

#8030 chore: lazily initialize find commands in makefile
  Makefile
Labels: hotfix

#8056 chore: tidy up grafana example dashboard
  coderd/coderd.go
  examples/monitoring/dashboards/grafana/README.md
  examples/monitoring/dashboards/grafana/dashboard.json
Labels: hotfix

#8042 docs: add oidc keycloak docs
  docs/admin/auth.md
Labels: docs, community

#8075 fix: show git provider id instead of type
  site/src/pages/DeploySettingsPage/GitAuthSettingsPage/GitAuthSettingsPageView.tsx
Labels: hotfix

#8077 feat: add region querying to pre-fetched html
  enterprise/coderd/coderd.go
  enterprise/coderd/workspaceproxy.go
  site/index.html
  site/site.go
  site/src/contexts/ProxyContext.tsx
Labels: hotfix

#8102 fix(site): prevent filter input update when focused
  site/src/components/Filter/filter.tsx
Labels: hotfix

#8103 fix(site): fix filters errors display
  site/src/components/Filter/filter.tsx
  site/src/pages/AuditPage/AuditPage.tsx
  site/src/pages/AuditPage/AuditPageView.tsx
  site/src/pages/UsersPage/UsersPage.tsx
  site/src/pages/UsersPage/UsersPageView.stories.tsx
  site/src/pages/UsersPage/UsersPageView.tsx
  site/src/pages/WorkspacesPage/WorkspacesPageView.tsx
  site/src/xServices/users/usersXService.ts
Labels: hotfix

#8113 docs: add prometheus scrape_config example
  docs/admin/prometheus.md
Labels: docs

#8037 ci: scan images with sysdig
  .github/workflows/security.yaml
Labels: hotfix

#8125 fix(site): show error when parameter is invalid
  codersdk/richparameters.go
  site/src/components/Alert/ErrorAlert.tsx
  site/src/pages/WorkspaceSettingsPage/WorkspaceParametersPage/WorkspaceParametersPage.tsx
Labels: hotfix

#8133 docs: add coder ping example for troubleshooting
  docs/networking/index.md
Labels: docs

#8135 ci: update sqlc version in security scan
  .github/workflows/security.yaml
Labels: hotfix

#8159 ci: replace double quotes with single quotes
  .github/workflows/pr-deploy.yaml
Labels: hotfix

#8158 ci: get PR number correctly from pull_request event in `pr-cleanup.yaml`
  .github/workflows/pr-cleanup.yaml
Labels: hotfix

#8185 docs: add max lifetime docs and refactor UI helper text
  docs/workspaces.md
  site/src/i18n/en/createTemplatePage.json
  site/src/i18n/en/templateSettingsPage.json
Labels: docs, site

#8184 docs: add default dir for VS Code Desktop
  docs/ides.md
Labels: docs

#8191 docs: fix incorrect command in project documentation
  docs/platforms/kubernetes/additional-clusters.md
Labels: community

#8190 docs: replace localhost with actual domain in additional-clusters.md
  docs/platforms/kubernetes/additional-clusters.md
Labels: community

#8196 chore: add examples templates to docs filter
  .github/workflows/ci.yaml
Labels: hotfix

#8224 chore: fix condition in `pr-deploy.yaml`
  .github/workflows/pr-cleanup.yaml
Labels: hotfix

#8225 chore: delete skipped workflow runs of `pr-deploy.yaml`
  .github/workflows/stale.yaml
Labels: hotfix

#8198 chore: fix broken docs links
  docs/admin/audit-logs.md
  docs/networking/port-forwarding.md
Labels: docs

#8230 test(agent): fix lifecycle test flakeyness
  agent/agent_test.go
Labels: hotfix

#8229 fix(cli/agent): wrap lumberjack logger to prevent re-open
  cli/agent.go
Labels: hotfix

#8233 feat: add deployment rbac perms in helm chart
  helm/templates/rbac.yaml
  helm/values.yaml
Labels: feature

#8251 docs: hotfix fix broken link in the group sync docs
  docs/admin/auth.md
Labels: hotfix

#8264 docs: add note about SSH key location in workspaces
  docs/secrets.md
Labels: docs

#8270 fix: pin datadog-ci version
  .github/actions/upload-datadog/action.yaml
Labels: hotfix

#8271 fix: scaletest: mount CODER_CACHE volume under /tmp
  scaletest/terraform/coder.tf
Labels: hotfix

#8272 fix: examples/lima: use new parameter name when creating template
  examples/lima/coder.yaml
Labels: hotfix

#8273 chore: bump migration to remove conflict
  coderd/database/migrations/000133_oauth_convert_audit.down.sql
  coderd/database/migrations/000133_oauth_convert_audit.up.sql
Labels: hotfix

#8284 chore: react to deploy-pr comment
  .github/workflows/pr-deploy.yaml
Labels: hotfix
