Repository coder/coder, pull requests merged in 2024-06, with the labels that each got.

#13450 chore: linting fixes
  Makefile
  cli/organizationroles.go
  cli/server.go
  cli/templatepush.go
  cli/templateversionarchive.go
  codersdk/rbacresources_gen.go
  scripts/apitypings/main.go
  scripts/rbacgen/codersdk.gotmpl
Labels: hotfix

#13451 chore: fix `(*coderdtest.WorkspaceAgentWaiter).Wait()` flake
  coderd/coderdtest/coderdtest.go
Labels: hotfix

#13449 chore: add light mode snapshot to chromatic for `WorkspaceBuildPageView`
  site/src/pages/WorkspaceBuildPage/WorkspaceBuildPageView.stories.tsx
Labels: hotfix

#13453 chore: fix `TestServer/Prometheus/DBMetricsDisabled` test flake
  cli/server_test.go
  coderd/prometheusmetrics/prometheusmetrics.go
Labels: hotfix

#13455 chore(dogfood): bump module versions
  dogfood/main.tf
Labels: hotfix

#13469 chore: update docs for v2.12 mainline and v2.11 stable
  docs/ides/remote-desktops.md
  docs/install/kubernetes.md
  docs/install/releases.md
Labels: hotfix

#13485 chore(scripts): remove remaining `gh_auth` calls from release scripts
  scripts/release/check_commit_metadata.sh
  scripts/release/generate_release_notes.sh
  scripts/release/publish.sh
Labels: hotfix

#13487 docs: bump k8s install version
  docs/install/kubernetes.md
Labels: hotfix

#13497 fix(site): fix tooltip in start button group
  site/src/pages/WorkspacePage/WorkspaceActions/Buttons.tsx
Labels: hotfix

#13493 fix(site): allow user to update their name
  site/src/pages/UserSettingsPage/AccountPage/AccountForm.stories.tsx
  site/src/pages/UserSettingsPage/AccountPage/AccountForm.test.tsx
  site/src/pages/UserSettingsPage/AccountPage/AccountForm.tsx
Labels: hotfix

#13495 fix(site): don't show start button while starting
  site/src/pages/WorkspacePage/WorkspaceActions/WorkspaceActions.tsx
Labels: hotfix

#13384 fix: transform underscores to hyphens for github login
  coderd/userauth.go
  coderd/userauth_test.go
Labels: stale

#13562 feat!: add interface report to coder netcheck
  cli/netcheck.go
  cli/netcheck_test.go
  coderd/healthcheck/health/model.go
  codersdk/healthsdk/healthsdk.go
  codersdk/healthsdk/interfaces.go
  codersdk/healthsdk/interfaces_internal_test.go
  docs/admin/healthcheck.md
Labels: release/breaking

#13561 docs: add validated architecture
  docs/admin/architectures/architecture.md
  docs/admin/architectures/scale-testing.md
  docs/admin/architectures/validated-arch.md
  docs/admin/scale.md
  docs/manifest.json
  docs/platforms/other.md
Labels: docs

#13574 docs: reorganize scaling docs
  docs/admin/architectures/validated-arch.md
  docs/admin/provisioners.md
  docs/admin/scaling/scale-testing.md
  docs/admin/scaling/scale-utility.md
  docs/manifest.json
  docs/platforms/aws.md
  docs/platforms/gcp.md
Labels: docs

#13582 docs: add screenshots page
  docs/about/screenshots.md
  docs/images/screenshots/audit.png
  docs/images/screenshots/healthcheck.png
  docs/images/screenshots/login.png
  docs/images/screenshots/settings.png
  docs/images/screenshots/starter_templates.png
  docs/images/screenshots/templates_insights.png
  docs/images/screenshots/templates_listing.png
  docs/images/screenshots/terraform.png
  docs/images/screenshots/workspace_launch.png
  docs/images/screenshots/workspaces_listing.png
  docs/manifest.json
Labels: hotfix

#13606 fix: use a privileged sidecar container in Kubernetes-based templates
  docs/templates/docker-in-workspaces.md
Labels: community

#13426 fix!: remove `failing_sections` from healthcheck
  coderd/apidoc/docs.go
  coderd/apidoc/swagger.json
  coderd/healthcheck/healthcheck.go
  coderd/healthcheck/healthcheck_test.go
  codersdk/healthsdk/healthsdk.go
  docs/api/debug.md
  docs/api/schemas.md
  site/src/api/typesGenerated.ts
  site/src/testHelpers/entities.ts
Labels: release/breaking

#13632 docs: bump mainline version to v2.12.2
  docs/install/kubernetes.md
Labels: hotfix

#13633 chore: manually updated autoversion for 2.11.3 release
  docs/install/kubernetes.md
Labels: hotfix

#13647 chore(scripts): add missing $ to release.sh
  scripts/release.sh
Labels: hotfix

#13649 chore(scripts): add changelog script flag for release channel
  scripts/release.sh
Labels: hotfix

#13652 docs: bump mainline version to v2.12.3
  docs/install/kubernetes.md
Labels: hotfix
