Repository coder/coder, pull requests merged in 2024-10, with the labels that each got.

#14888 fix: remove redundant flaking test
  coderd/apikey_test.go
Labels: hotfix

#14892 test: ignore log errors
  coderd/insights_test.go
Labels: hotfix

#14778 docs: add organizations, provisioners, and premium license docs
  docs/admin/appearance.md
  docs/admin/audit-logs.md
  docs/admin/auth.md
  docs/admin/external-auth.md
  docs/admin/groups.md
  docs/admin/high-availability.md
  docs/admin/notifications.md
  docs/admin/organizations.md
  docs/admin/provisioners.md
  docs/admin/quotas.md
  docs/admin/rbac.md
  docs/admin/upgrade.md
  docs/admin/users.md
  docs/changelogs/v2.0.0.md
  docs/contributing/feature-stages.md
  docs/enterprise.md
  docs/faqs.md
  docs/guides/configuring-okta.md
  docs/guides/index.md
  docs/guides/using-organizations.md
  docs/images/add-license-ui.png
  docs/images/admin/organizations/custom-roles.png
  docs/images/admin/organizations/default-organization.png
  docs/images/admin/organizations/deployment-organizations.png
  docs/images/admin/organizations/diagram.png
  docs/images/admin/organizations/group-sync.png
  docs/images/admin/organizations/new-organization.png
  docs/images/admin/organizations/organization-members.png
  docs/images/admin/organizations/role-sync.png
  docs/images/admin/organizations/template-org-picker.png
  docs/images/admin/organizations/workspace-list.png
  docs/images/icons/licensing.svg
  docs/images/icons/orgs.svg
  docs/licensing.md
  docs/manifest.json
  docs/networking/index.md
  docs/networking/port-forwarding.md
  docs/workspaces.md
  scripts/apidocgen/postprocess/main.go
  scripts/clidocgen/main.go
  site/src/components/Paywall/Paywall.tsx
  site/src/components/Paywall/PopoverPaywall.tsx
  site/src/pages/ManagementSettingsPage/CreateOrganizationPageView.tsx
  site/src/pages/ManagementSettingsPage/IdpSyncPage/IdpSyncHelpTooltip.tsx
  site/src/pages/ManagementSettingsPage/IdpSyncPage/IdpSyncPage.tsx
  site/src/pages/ManagementSettingsPage/IdpSyncPage/IdpSyncPageView.tsx
  site/src/pages/ManagementSettingsPage/OrganizationProvisionersPageView.tsx
  site/src/pages/SetupPage/SetupPageView.tsx
Labels: multi-org

#14920 chore: fix label for orgs docs
  docs/manifest.json
Labels: hotfix

#14926 chore(docs): bump stable version
  docs/install/kubernetes.md
  docs/install/releases.md
Labels: hotfix

#14890 feat: remove dark blue theme
  coderd/database/migrations/000260_remove_dark_blue_theme.down.sql
  coderd/database/migrations/000260_remove_dark_blue_theme.up.sql
  site/src/pages/UserSettingsPage/AppearancePage/AppearanceForm.tsx
  site/src/pages/UserSettingsPage/AppearancePage/AppearancePage.test.tsx
  site/src/pages/UsersPage/storybookData/users.ts
  site/src/theme/darkBlue/branding.ts
  site/src/theme/darkBlue/experimental.ts
  site/src/theme/darkBlue/index.ts
  site/src/theme/darkBlue/monaco.ts
  site/src/theme/darkBlue/mui.ts
  site/src/theme/darkBlue/roles.ts
  site/src/theme/index.ts
Labels: community

#14972 test: use static port for Prometheus
  enterprise/cli/proxyserver_test.go
Labels: hotfix

#14990 chore(docs): fix broken links and update file paths
  docs/changelogs/v2.0.0.md
  docs/install/kubernetes.md
  docs/install/other/openshift.md
  docs/tutorials/faqs.md
Labels: hotfix

#14994 chore(docs): fix a wrong link in v2.0.0 changelog
  docs/changelogs/v2.0.0.md
Labels: hotfix

#15012 chore: add OpenSSF badge
  .github/workflows/scorecard.yml
  README.md
Labels: hotfix

#14991 chore(README.md): add setup coder GitHub action link
  README.md
Labels: hotfix

#14941 docs: explain --rich-parameter-file format
  cli/parameter.go
  cli/testdata/coder_create_--help.golden
  cli/testdata/coder_restart_--help.golden
  cli/testdata/coder_start_--help.golden
  cli/testdata/coder_update_--help.golden
  docs/reference/cli/create.md
  docs/reference/cli/restart.md
  docs/reference/cli/start.md
  docs/reference/cli/update.md
Labels: community

#14880 feat: implement feature to support template version while creating workspace using cli
  cli/create.go
  cli/create_test.go
  cli/testdata/coder_create_--help.golden
  docs/reference/cli/create.md
Labels: community

#14706 docs: reorganize and edit docs README
  docs/README.md
Labels: docs

#15071 fix: fix error handling to prevent spam in proc prio management
  agent/agent.go
Labels: hotfix

#15075 test: skip scaletest/reconnectingpty Test_Runner
  scaletest/createworkspaces/run_test.go
Labels: hotfix

#15076 test: skip scaletest/reconnectingpty Test_Runner
  scaletest/createworkspaces/run_test.go
  scaletest/reconnectingpty/run_test.go
Labels: hotfix

#15102 fix(docs): fix a typo in the devcontainer documentation
  docs/admin/templates/managing-templates/devcontainers.md
Labels: hotfix

#15104 fix: match go version in go.mod and CI
  .github/actions/setup-go/action.yaml
Labels: hotfix

#15120 fix: check unstaged files during ci lint
  .github/workflows/ci.yaml
  coderd/activitybump_test.go
  enterprise/wsproxy/keyfetcher.go
Labels: hotfix

#15051 feat: allow promoting an existing template version to active from CLI
  cli/templateversions.go
  cli/templateversions_test.go
  cli/testdata/coder_templates_versions_--help.golden
  cli/testdata/coder_templates_versions_promote_--help.golden
  docs/manifest.json
  docs/reference/cli/templates_versions.md
  docs/reference/cli/templates_versions_promote.md
Labels: community

#15121 test: improve logging around `TestAgentScript`
  provisionersdk/agent_test.go
Labels: hotfix

#15124 fix: correct default wsproxy table columns
  enterprise/cli/workspaceproxy.go
Labels: hotfix

#15127 chore: remove duplicated harden-runner step
  .github/workflows/pr-deploy.yaml
Labels: community

#15146 chore: skip ssh exec-ing test on windows
  cli/configssh_test.go
Labels: hotfix

#14817 feat(helm): add setting to disable service account creation
  helm/coder/templates/coder.yaml
  helm/coder/values.yaml
Labels: community

#15070 chore(docs): remove workspace proxy map
  docs/admin/networking/workspace-proxies.md
  docs/images/admin/networking/workspace-proxies/proxydiagram.png
Labels: docs

#15185 docs: add primary to wsproxy ls
  docs/admin/networking/workspace-proxies.md
Labels: docs

#14744 chore(docs): add Quickstart doc to tutorials
  docs/README.md
  docs/admin/templates/managing-templates/index.md
  docs/images/screenshots/create-template.png
  docs/images/screenshots/welcome-create-admin-user.png
  docs/images/screenshots/workspace-running-with-topbar.png
  docs/install/index.md
  docs/manifest.json
  docs/start/coder-tour.md
  docs/tutorials/index.md
  docs/tutorials/quickstart.md
Labels: docs

#15196 fix: make helm golden files to fix ci
  helm/coder/tests/testdata/auto_access_url_1.golden
  helm/coder/tests/testdata/auto_access_url_2.golden
  helm/coder/tests/testdata/auto_access_url_3.golden
  helm/coder/tests/testdata/command.golden
  helm/coder/tests/testdata/command_args.golden
  helm/coder/tests/testdata/default_values.golden
  helm/coder/tests/testdata/env_from.golden
  helm/coder/tests/testdata/extra_templates.golden
  helm/coder/tests/testdata/labels_annotations.golden
  helm/coder/tests/testdata/prometheus.golden
  helm/coder/tests/testdata/provisionerd_psk.golden
  helm/coder/tests/testdata/sa.golden
  helm/coder/tests/testdata/sa_extra_rules.golden
  helm/coder/tests/testdata/tls.golden
  helm/coder/tests/testdata/workspace_proxy.golden
Labels: hotfix

#15199 docs: add date to Quickstart guide
  docs/tutorials/quickstart.md
Labels: docs

#15168 feat(helm): add topologySpreadConstraints value
  helm/coder/tests/chart_test.go
  helm/coder/tests/testdata/topology.golden
  helm/coder/tests/testdata/topology.yaml
  helm/coder/values.yaml
  helm/libcoder/templates/_coder.yaml
Labels: helm

#15238 chore: change promtheus label to 'tx_id'
  coderd/database/dbmetrics/dbmetrics.go
  coderd/database/dbmetrics/dbmetrics_test.go
Labels: hotfix

#15251 chore: name unlabeled db transaction metrics
  coderd/database/dbmetrics/dbmetrics.go
  coderd/database/dbmetrics/dbmetrics_test.go
Labels: hotfix

#15258 chore(docs): change mentions of enterprise to premium
  docs/admin/infrastructure/architecture.md
  docs/admin/infrastructure/scale-testing.md
  docs/admin/monitoring/notifications/index.md
  docs/admin/networking/index.md
  docs/admin/networking/port-forwarding.md
  docs/admin/security/audit-logs.md
  docs/admin/templates/extending-templates/process-logging.md
  docs/admin/templates/managing-templates/index.md
  docs/admin/templates/managing-templates/schedule.md
  docs/admin/templates/template-permissions.md
  docs/tutorials/faqs.md
  docs/tutorials/index.md
  docs/user-guides/workspace-access/port-forwarding.md
  docs/user-guides/workspace-management.md
  docs/user-guides/workspace-scheduling.md
Labels: docs, hotfix

#15268 fix(site): fix workspace timings verbiage
  site/src/modules/workspaces/WorkspaceTiming/StagesChart.tsx
  site/src/modules/workspaces/WorkspaceTiming/WorkspaceTimings.tsx
Labels: hotfix

#15280 chore(docs): add documentation on custom roles
  docs/admin/users/groups-roles.md
  docs/images/admin/users/roles/assigning-custom-role.PNG
  docs/images/admin/users/roles/creating-custom-role.PNG
  docs/images/admin/users/roles/custom-roles.PNG
Labels: hotfix

#15293 fix: check correct default during template push from stdin
  cli/templatepush.go
Labels: hotfix

#15307 refactor(site): refactor DAU chart to avoid seat consumption focus
  site/src/components/ActiveUserChart/ActiveUserChart.stories.tsx
  site/src/components/ActiveUserChart/ActiveUserChart.tsx
  site/src/pages/DeploymentSettingsPage/GeneralSettingsPage/GeneralSettingsPageView.stories.tsx
  site/src/pages/DeploymentSettingsPage/GeneralSettingsPage/GeneralSettingsPageView.tsx
  site/src/pages/TemplatePage/TemplateInsightsPage/TemplateInsightsPage.stories.tsx
  site/src/pages/TemplatePage/TemplateInsightsPage/TemplateInsightsPage.tsx
Labels: hotfix
