Repository coder/coder, pull requests merged in 2024-01, with the labels that each got.

#11362 fix: test for expiry 3 months on Azure certs
  coderd/azureidentity/azureidentity_test.go
Labels: hotfix

#11361 chore: disable failing metrics check until it can be fixed
  scaletest/workspacetraffic/run_test.go
Labels: hotfix

#11371 fix(site): fix workspace topbar back button
  site/src/pages/WorkspacePage/WorkspaceTopbar/WorkspaceTopbar.tsx
Labels: hotfix

#11368 fix(site): fix pill spinner size
  site/src/components/Pill/Pill.stories.tsx
  site/src/components/Pill/Pill.tsx
  site/src/utils/workspace.tsx
Labels: hotfix

#11372 chore(site): implement ignoring deletion date on chromatic
  site/src/pages/WorkspacePage/WorkspaceTopbar/WorkspaceTopbar.tsx
Labels: hotfix

#11373 fix(site): fix external auth button loading state
  site/src/pages/CreateWorkspacePage/ExternalAuth.tsx
Labels: hotfix

#11374 chore(site): move workspace topbar component
  site/src/pages/WorkspacePage/Workspace.tsx
  site/src/pages/WorkspacePage/WorkspaceTopbar.stories.tsx
  site/src/pages/WorkspacePage/WorkspaceTopbar.tsx
Labels: hotfix

#11384 chore(coderd/database/dbfake): fix pq test flake in TestStart_Starting
  coderd/database/dbfake/dbfake.go
Labels: hotfix

#11391 fix(site): fix insights picker and disable animation
  site/src/components/ActiveUserChart/ActiveUserChart.tsx
  site/src/pages/TemplatePage/TemplateInsightsPage/DateRange.tsx
Labels: hotfix

#11392 fix(site): fix loading spinner on template version status badge
  site/src/pages/TemplateVersionEditorPage/TemplateVersionStatusBadge.tsx
Labels: hotfix

#11394 fix: create tempdir prior to cleanup
  provisionerd/provisionerd_test.go
Labels: hotfix

#11397 chore: mark template update policies as GA in docs
  docs/templates/general-settings.md
  docs/workspaces.md
Labels: hotfix

#11404 chore: add lxc logo
  site/src/theme/icons.json
  site/static/icon/lxc.svg
Labels: hotfix

#11429 docs: add guide for Google to AWS federation
  docs/guides/gcp-to-aws.md
  docs/images/guides/gcp-to-aws/aws-create-role.png
  docs/manifest.json
Labels: docs, feature

#11432 fix: gcp federation guide formatting
  docs/guides/gcp-to-aws.md
Labels: docs

#11439 refactor(site): only show derp tags if they are true
  site/src/pages/HealthPage/WorkspaceProxyPage.tsx
Labels: hotfix

#11458 ci: add variable to template push in dogfood.yaml
  .github/workflows/dogfood.yaml
Labels: hotfix

#11459 chore(dogfood): install corepack
  dogfood/Dockerfile
Labels: hotfix

#11472 chore: increase dependabot PRs limit for go
  .github/dependabot.yaml
Labels: hotfix

#11488 fix(site): display github login config
  site/src/utils/deployOptions.ts
Labels: hotfix

#11489 refactor(site): improve settings option
  site/src/components/DeploySettingsLayout/Option.tsx
  site/src/components/DeploySettingsLayout/OptionsTable.tsx
Labels: hotfix

#11511 docs: remove empty page
  coderd/apidoc/docs.go
  coderd/apidoc/swagger.json
  docs/api/applications enterprise.md
  docs/manifest.json
  enterprise/coderd/workspaceproxy.go
Labels: hotfix

#11513 docs: escape enum pipe
  cli/clibase/values.go
  docs/cli/config-ssh.md
  docs/cli/speedtest.md
  docs/cli/ssh.md
  docs/cli/stat_disk.md
  docs/cli/stat_mem.md
  docs/cli/templates_init.md
Labels: hotfix

#11516 fix(site): adjust unhealthy regions border colour in HealthPage/WorkspaceProxyPage
  site/src/pages/HealthPage/WorkspaceProxyPage.tsx
Labels: hotfix

#11543 docs(faqs): add FAQ regarding unsupported base image for VS Code Server
  docs/faqs.md
Labels: hotfix

#11548 chore(docs): remove provider logos from 1-click install
  docs/images/install/ec2.svg
  docs/images/install/eks.svg
  docs/images/install/fly.io.svg
  docs/images/install/gce.svg
  docs/images/install/heroku.svg
  docs/images/install/railway.svg
  docs/images/install/render.png
  docs/install/1-click.md
Labels: hotfix

#11535 chore: update Digital Ocean example template (#11528)
  examples/templates/do-linux/main.tf
  site/src/theme/icons.json
  site/static/icon/almalinux.svg
Labels: community

#11573 fix(site): fix loading indicator alignment
  site/src/theme/mui.ts
Labels: hotfix

#11574 fix(site): remove refetch on windows focus
  site/src/api/queries/users.ts
Labels: hotfix

#11351 chore: add optional coder_app to faq
  docs/faqs.md
Labels: stale

#11582 feat(site): add docs links on health page
  site/src/pages/HealthPage/AccessURLPage.tsx
  site/src/pages/HealthPage/Content.tsx
  site/src/pages/HealthPage/DERPPage.tsx
  site/src/pages/HealthPage/DERPRegionPage.tsx
  site/src/pages/HealthPage/DatabasePage.tsx
  site/src/pages/HealthPage/ProvisionerDaemonsPage.tsx
  site/src/pages/HealthPage/WorkspaceProxyPage.tsx
Labels: hotfix

#11585 chore: convert faq headers to dropdowns
  docs/faqs.md
Labels: docs

#11596 fix(site): fix workspace resource width on ultra wide screens
  site/src/pages/WorkspacePage/Workspace.tsx
Labels: hotfix

#11599 fix(site): remove search menu vertical padding
  site/src/components/Filter/filter.tsx
Labels: hotfix

#11597 feat(site): display builds logs by default
  site/src/hooks/useWorkspaceBuildLogs.ts
  site/src/pages/WorkspacePage/WorkspaceReadyPage.tsx
Labels: hotfix

#11601 refactor(site): make cosmetic changes on agent logs
  site/src/components/Resources/AgentRow.tsx
  site/src/components/WorkspaceBuildLogs/Logs.tsx
Labels: hotfix

#11608 docs: add guide for template ImagePullSecret
  docs/guides/example-guide.md
  docs/guides/gcp-to-aws.md
  docs/guides/image-pull-secret.md
  docs/manifest.json
Labels: docs

#11610 chore(docs): fix a minor punctuation error
  docs/about/architecture.md
Labels: hotfix

#11613 chore(docs/guides): add author name to guides
  docs/guides/gcp-to-aws.md
  docs/guides/image-pull-secret.md
Labels: docs

#11612 docs: add steps to configure supportLinks in Helm chart
  docs/admin/appearance.md
Labels: docs

#11375 chore: update README.md to reference industry term Cloud Development Environments
  README.md
Labels: stale

#11630 chore(docs/install/docker.md): shorten headings length
  docs/install/docker.md
Labels: docs, hotfix

#11146 docs: add workspace cleanup docs
  docs/images/template-scheduling.png
  docs/manifest.json
  docs/templates/schedule.md
Labels: docs

#11664 fix: revert "detect JetBrains running on local ipv6 (#11653)"
  agent/agent_test.go
  agent/agentssh/portinspection_supported.go
  scripts/echoserver/main.go
Labels: hotfix

#11667 fix: fix typo in whitespace
  coderd/httpapi/name.go
Labels: hotfix

#11674 fix(site): fix search menu for creating workspace and templates filter
  site/src/components/Filter/filter.tsx
  site/src/components/Menu/Search.tsx
  site/src/pages/WorkspacesPage/WorkspacesButton.tsx
  site/src/pages/WorkspacesPage/WorkspacesSearchBox.tsx
Labels: hotfix

#11706 fix: set request header before do
  coderd/externalauth/externalauth.go
Labels: hotfix

#11709 chore: fix `TemplateVersionEditor` story
  site/src/pages/TemplateVersionEditorPage/TemplateVersionEditor.stories.tsx
Labels: hotfix

#11724 fix(docs): fix tabs for support links
  docs/admin/appearance.md
Labels: hotfix

#11726 chore(docs): remove tabs from appearance settings
  docs/admin/appearance.md
Labels: hotfix

#11728 chore: use correct anchor link on `scale.md`
  docs/admin/scale.md
Labels: community

#11744 fix: use DiscoPing (partially reverts #11306)
  tailnet/conn.go
Labels: hotfix

#11747 docs: add v2.7.1 changelog
  docs/changelogs/README.md
  docs/changelogs/v2.7.1.md
Labels: hotfix

#11746 chore(site): minor refactor to the resource metadata code
  site/src/pages/WorkspacePage/ResourceMetadata.stories.tsx
  site/src/pages/WorkspacePage/ResourceMetadata.tsx
  site/src/pages/WorkspacePage/Workspace.tsx
Labels: hotfix

#11755 chore(site): add test for sensitive value
  site/src/pages/WorkspacePage/ResourceMetadata.stories.tsx
Labels: hotfix

#11760 chore: fix broken docs links
  docs/CONTRIBUTING.md
  docs/README.md
  docs/admin/appearance.md
  docs/admin/configure.md
  docs/changelogs/v2.1.5.md
  docs/changelogs/v2.5.1.md
  docs/changelogs/v2.7.0.md
  docs/faqs.md
  docs/guides/example-guide.md
  docs/install/1-click.md
  docs/install/docker.md
  docs/install/index.md
  docs/platforms/aws.md
  docs/templates/icons.md
Labels: docs, chore

#11774 chore(dogfood): add versioning to coder modules
  dogfood/main.tf
Labels: hotfix

#11803 refactor(site): increase form fields gap
  site/src/components/Form/Form.tsx
Labels: hotfix

#11785 chore: cleanup various auth things
  site/src/modules/dashboard/entitlements.test.ts
  site/src/modules/dashboard/entitlements.ts
  site/src/modules/dashboard/useFeatureVisibility.ts
  site/src/pages/CliAuthPage/CliAuthPage.tsx
  site/src/pages/CliAuthPage/CliAuthPageView.tsx
Labels: hotfix

#11844 fix: fix color reference
  site/src/components/Resources/AgentMetadata.tsx
Labels: hotfix

#11867 ci: validate template before pushing
  .github/workflows/dogfood.yaml
  dogfood/main.tf
Labels: hotfix

#11864 docs: add guide for azure federation
  docs/guides/azure-federation.md
  docs/manifest.json
Labels: docs

#11865 ci: fix winget-release workflow
  .github/workflows/release.yaml
Labels: block-release

#11891 fix(site): fix capitalized username
  site/src/components/WorkspaceBuild/WorkspaceBuildData.tsx
Labels: hotfix

#11895 chore(docs): fix a typo
  docs/admin/provisioners.md
Labels: hotfix

#11957 chore(dogfood): use better names for image options
  dogfood/main.tf
Labels: hotfix

#11958 fix(dogfood): fix startup script on workspace creation
  dogfood/main.tf
Labels: hotfix
