Repository coder/coder, pull requests merged in 2024-04, with the labels that each got.

#12698 feat(cli): add golden tests for errors (#11588)
  Makefile
  cli/clitest/golden.go
  cli/errors.go
  cli/errors_test.go
  cli/root.go
  cli/server_test.go
  cli/testdata/coder_exp_example-error_api.golden
  cli/testdata/coder_exp_example-error_arg-required.golden
  cli/testdata/coder_exp_example-error_cmd.golden
  cli/testdata/coder_exp_example-error_multi-error.golden
  cli/testdata/coder_exp_example-error_multi-multi-error.golden
  cli/testdata/coder_exp_example-error_validation.golden
Labels: community

#12836 chore: move log output message before logs begin streaming
  cli/server.go
Labels: hotfix

#12845 docs: fix coder-logstream-kube typo in deployment-logs.md
  docs/platforms/kubernetes/deployment-logs.md
Labels: community

#12847 chore: remove unnecessary extraction library
  cli/templatepull.go
  cli/templatepull_test.go
  go.mod
  go.sum
  provisionersdk/archive.go
Labels: hotfix

#12861 chore: upgrade go to `1.21.9`
  .github/actions/setup-go/action.yaml
  .github/workflows/ci.yaml
  dogfood/Dockerfile
Labels: hotfix

#12874 ci: disable `--in-memory` for enterprise e2e tests
  .github/workflows/ci.yaml
  site/e2e/playwright.config.ts
  site/e2e/tests/updateTemplate.spec.ts
Labels: hotfix

#12873 fix(install.sh): use `--version` if provided
  install.sh
Labels: community

#12878 fix(install.sh): change post-install advisory when installing specific version
  install.sh
Labels: hotfix

#12969 chore: add `created_at` to workspace resource telemetry
  coderd/telemetry/telemetry.go
Labels: hotfix

#12945 chore: fix linting issue
  coderd/database/dbmem/dbmem.go
Labels: hotfix

#12979 fix: disable azureidentity test on darwin
  coderd/azureidentity/azureidentity_test.go
Labels: hotfix

#12982 fix: skip dependency license review on main
  .github/workflows/ci.yaml
Labels: hotfix

#12993 docs: explain that mainline stays around for one month now
  docs/install/releases.md
Labels: hotfix

#13018 chore: fix 404 for managed terraform variables
  docs/platforms/kubernetes/additional-clusters.md
Labels: community

#12991 feat: add --env flag for "coder ssh"
  cli/ssh.go
  cli/ssh_test.go
  cli/testdata/coder_ssh_--help.golden
  docs/cli/ssh.md
Labels: community

#13019 chore: fix link to install
  docs/guides/support-bundle.md
Labels: community

#13015 chore: fix broken mainline link
  docs/install/releases.md
Labels: community

#13056 chore(docs): fix broken links
  .github/workflows/weekly-docs.yaml
  docs/about/architecture.md
  docs/changelogs/v0.26.1.md
  examples/templates/devcontainer-docker/README.md
  examples/templates/devcontainer-kubernetes/README.md
Labels: community

#12976 chore: deprecate gauge metrics with _total suffix (#12744)
  coderd/prometheusmetrics/prometheusmetrics.go
  coderd/prometheusmetrics/prometheusmetrics_test.go
  coderd/promoauth/oauth2.go
  docs/admin/prometheus.md
  scripts/metricsdocgen/metrics
Labels: community

#13040 chore(docs): add k8s terraform link to k8s installation docs
  docs/install/kubernetes.md
Labels: community

#13064 chore(docs): update helm install version flags to patch releases
  docs/install/kubernetes.md
Labels: docs, chore

#13059 chore(README): add contributing section to readme
  README.md
Labels: community

#13083 chore: correct name for github enterprise example
  docs/admin/external-auth.md
Labels: community

#13097 chore: lower azure expires soon
  coderd/azureidentity/azureidentity_test.go
Labels: hotfix

#13104 chore: centralize build info for site
  coderd/coderd.go
  coderd/deployment.go
  site/site.go
Labels: hotfix

#13105 chore: fix dependency review action
  .github/workflows/ci.yaml
Labels: hotfix

#13106 chore: remove `GITHUB_TOKEN` from dogfood env vars
  dogfood/main.tf
Labels: hotfix

#13109 chore: fix leaking dns lookup by updating tailscale
  go.mod
  go.sum
Labels: hotfix
