Repository coder/coder, pull requests merged in 2024-05, with the labels that each got.

#13128 fix: start packet capture immediately on speedtest
  cli/speedtest.go
  codersdk/workspacesdk/workspacesdk.go
  tailnet/conn.go
Labels: networking

#13113 docs: add island integration guide
  docs/guides/island-integration.md
  docs/manifest.json
Labels: docs

#13145 fix: add more tests for metadata hook functionality
  site/src/hooks/useEmbeddedMetadata.test.ts
Labels: hotfix

#12870 fix: install openrc service on alpine (#12294)
  scripts/linux-pkg/coder-openrc
  scripts/linux-pkg/coder-workspace-proxy-openrc
  scripts/linux-pkg/nfpm-alpine.yaml
  scripts/package.sh
Labels: community

#13164 chore: fix build ci
  coderd/database/dbpurge/dbpurge_test.go
  scripts/package.sh
Labels: hotfix

#13166 docs(admin/external-auth.md): add JFrog Artifactory guide
  docs/admin/external-auth.md
Labels: hotfix

#13178 fix: reverts "fix: install openrc service on alpine (#12294)"
  scripts/linux-pkg/coder-openrc
  scripts/linux-pkg/coder-workspace-proxy-openrc
  scripts/linux-pkg/nfpm-alpine.yaml
  scripts/package.sh
Labels: hotfix

#13180 fix: revert "chore: fix build ci"
  scripts/package.sh
Labels: hotfix

#13187 ci: sync terraform version
  .github/actions/setup-tf/action.yaml
Labels: hotfix

#13162 docs: show the proper Redirect URI for Gitea
  docs/admin/external-auth.md
Labels: community

#13201 ci: disable make test-migrations in release.yaml
  .github/workflows/release.yaml
Labels: hotfix

#13205 docs: describe AWS hard NAT
  docs/networking/stun.md
Labels: docs

#13179 docs(ides): document connection via JetBrains Fleet
  docs/ides.md
  docs/ides/fleet.md
  docs/images/fleet/ssh-connect-to-coder.png
Labels: docs, hotfix

#13239 fix: skip license review for dependabot
  .github/workflows/ci.yaml
Labels: hotfix

#13243 fix: fix nix flake sed command
  scripts/update-flake.sh
Labels: hotfix

#13262 chore(site): fix port forward issue with vite
  site/vite.config.ts
Labels: hotfix

#13302 docs: bump k8s install version
  docs/install/kubernetes.md
Labels: hotfix

#13309 ci: re-pin `actions/dependency-review-action` back to a release
  .github/workflows/ci.yaml
Labels: hotfix

#13275 chore: update kubernetes.md, bumping stable from v2.9.4 to v2.10.2
  docs/install/kubernetes.md
Labels: stale

#13341 refactor(site): hide unavailable usage information
  site/src/pages/TemplatePage/TemplateInsightsPage/TemplateInsightsPage.stories.tsx
  site/src/pages/TemplatePage/TemplateInsightsPage/TemplateInsightsPage.tsx
Labels: hotfix

#13346 chore(docs): update k8s mainline version
  docs/install/kubernetes.md
Labels: hotfix

#13347 chore(scripts): remove `gh_auth` from `release.sh`
  scripts/release.sh
Labels: hotfix

#13388 chore: upgrade `go.uber.org/goleak`
  flake.nix
  go.mod
  go.sum
Labels: hotfix

#13368 fix(cli): skip optional coder_external_auth
  cli/cliui/externalauth.go
Labels: community

#13423 fix: update `DeleteWorkspaceOptions` to pick properties correctly
  site/src/api/api.ts
  site/src/pages/WorkspacePage/WorkspacePage.test.tsx
  site/src/pages/WorkspacePage/WorkspaceReadyPage.tsx
Labels: hotfix
