Repository coder/coder, pull requests merged in 2024-08, with the labels that each got.

#14073 chore: update meticulous CI job
  .github/workflows/ci.yaml
  .github/workflows/meticulous.yaml
Labels: community

#14106 chore: skip dogfood workflow for dependabot PRs
  .github/workflows/dogfood.yaml
Labels: hotfix

#14111 chore: skip dogfood workflow for dependabot PRs
  .github/workflows/dogfood.yaml
Labels: hotfix

#14122 chore: license pnpm packages
  .github/workflows/ci.yaml
Labels: hotfix

#14125 fix: check for io.EOF error in derpmap to resolve flake
  codersdk/workspacesdk/connector.go
Labels: hotfix

#14128 chore(docs): update version flags for 2.12.6 and 2.13.3
  docs/install/kubernetes.md
Labels: hotfix

#14121 chore(site): remove proxy menu warnings about using fragment as child
  site/src/modules/dashboard/Navbar/ProxyMenu.tsx
Labels: hotfix

#14137 chore(site): fix storybook font issue
  site/.storybook/preview.jsx
Labels: hotfix

#14116 feat: allow admins to modify notification template delivery method
  cli/notifications_test.go
  coderd/apidoc/docs.go
  coderd/apidoc/swagger.json
  coderd/coderd.go
  coderd/database/queries.sql.go
  coderd/database/queries/notifications.sql
  coderd/httpmw/notificationtemplateparam.go
  coderd/notifications.go
  coderd/notifications/enqueuer.go
  coderd/notifications/manager.go
  coderd/notifications/metrics_test.go
  coderd/notifications/notifications_test.go
  coderd/notifications/notifier.go
  coderd/notifications_test.go
  codersdk/notifications.go
  docs/api/enterprise.md
  docs/api/general.md
  docs/api/notifications.md
  docs/api/schemas.md
  docs/manifest.json
  enterprise/coderd/coderd.go
  enterprise/coderd/notifications.go
  enterprise/coderd/notifications_test.go
  site/src/api/typesGenerated.ts
Labels: enterprise

#14183 chore: update github.com/docker/docker
  flake.nix
  go.mod
  go.sum
Labels: hotfix

#14184 chore(scripts): remove branch checks from release script
  scripts/release.sh
  scripts/release/tag_version.sh
Labels: hotfix

#14185 chore: bump github.com/docker/docker
  flake.nix
  go.mod
  go.sum
Labels: hotfix

#14191 chore(docs): update version flags and release calendar for 2.14 release
  docs/install/kubernetes.md
  docs/install/releases.md
Labels: hotfix

#14028 fix(examples): use more precise example kubernetes template labels
  examples/templates/kubernetes/main.tf
Labels: community

#14069 feat: add custom roles
  site/src/api/api.ts
  site/src/api/queries/organizations.ts
  site/src/api/queries/roles.ts
  site/src/pages/ManagementSettingsPage/CustomRolesPage/CreateEditRolePage.tsx
  site/src/pages/ManagementSettingsPage/CustomRolesPage/CreateEditRolePageView.stories.tsx
  site/src/pages/ManagementSettingsPage/CustomRolesPage/CreateEditRolePageView.tsx
  site/src/pages/ManagementSettingsPage/CustomRolesPage/CustomRolesPage.tsx
  site/src/pages/ManagementSettingsPage/CustomRolesPage/CustomRolesPageView.stories.tsx
  site/src/pages/ManagementSettingsPage/CustomRolesPage/CustomRolesPageView.tsx
  site/src/pages/ManagementSettingsPage/SidebarView.stories.tsx
  site/src/pages/ManagementSettingsPage/SidebarView.tsx
  site/src/pages/ManagementSettingsPage/UserTable/EditRolesButton.tsx
  site/src/router.tsx
  site/src/testHelpers/entities.ts
Labels: feature

#14226 refactor(site): make switches smaller
  site/src/pages/UserSettingsPage/NotificationsPage/NotificationsPage.tsx
Labels: hotfix

#14259 chore: fix dead link to privileged docker containers in docs
  docs/templates/docker-in-workspaces.md
Labels: hotfix

#14200 fix: allow group members to read group information
  coderd/apidoc/docs.go
  coderd/apidoc/swagger.json
  coderd/database/db2sdk/db2sdk.go
  coderd/database/dbauthz/dbauthz.go
  coderd/database/dbauthz/dbauthz_test.go
  coderd/database/dbauthz/groupsauth_test.go
  coderd/database/dbgen/dbgen.go
  coderd/database/dbgen/dbgen_test.go
  coderd/database/dbmem/dbmem.go
  coderd/database/dbmetrics/dbmetrics.go
  coderd/database/dbmock/dbmock.go
  coderd/database/dump.sql
  coderd/database/migrations/000242_group_members_view.down.sql
  coderd/database/migrations/000242_group_members_view.up.sql
  coderd/database/modelmethods.go
  coderd/database/models.go
  coderd/database/querier.go
  coderd/database/queries.sql.go
  coderd/database/queries/groupmembers.sql
  coderd/database/queries/groups.sql
  coderd/database/sqlc.yaml
  coderd/rbac/object_gen.go
  coderd/rbac/policy/policy.go
  coderd/rbac/roles.go
  coderd/rbac/roles_test.go
  coderd/telemetry/telemetry_test.go
  codersdk/groups.go
  codersdk/rbacresources_gen.go
  docs/api/enterprise.md
  docs/api/members.md
  docs/api/schemas.md
  enterprise/coderd/groups.go
  enterprise/coderd/groups_test.go
  enterprise/coderd/templates.go
  site/src/api/rbacresources_gen.ts
  site/src/api/typesGenerated.ts
  site/src/pages/UserSettingsPage/AccountPage/AccountUserGroups.tsx
  site/src/testHelpers/entities.ts
Labels: community

#14256 chore: update envbox template image
  examples/templates/envbox/main.tf
Labels: community

#14269 chore(site): reduce flakiness on terminal stories
  site/src/pages/TerminalPage/TerminalPage.stories.tsx
Labels: hotfix

#14297 chore: ignore tabs change when using git blame
  .git-blame-ignore-revs
Labels: hotfix

#14329 chore: enable `noConsoleLog` lint
  site/biome.json
  site/e2e/helpers.ts
  site/e2e/hooks.ts
  site/e2e/proxy.ts
  site/e2e/reporter.ts
  site/e2e/tests/webTerminal.spec.ts
  site/src/contexts/useProxyLatency.ts
Labels: hotfix

#14221 chore: update docs links
  cli/rename.go
  cli/server.go
  docs/admin/README.md
  docs/platforms/README.md
  docs/platforms/azure.md
  dogfood/contents/guide.md
  examples/lima/coder.yaml
  examples/web-server/caddy/README.md
  helm/coder/README.md
  scripts/linux-pkg/coder-workspace-proxy.service
  scripts/linux-pkg/coder.service
Labels: hotfix

#14380 fix: add missing commit for provisioner timings PR
  coderd/database/migrations/000246_provisioner_job_timings.down.sql
  coderd/database/migrations/000246_provisioner_job_timings.up.sql
  coderd/database/migrations/testdata/fixtures/000246_provisioner_job_timings.up.sql
  provisioner/terraform/internal/timings_test_utils.go
Labels: hotfix

#14385 chore(docs): add WebRDP to restructure docs
  docs/images/user-guides/web-rdp-demo.png
  docs/user-guides/workspace-access.md
  docs/user-guides/workspace-access/remote-desktops.md
Labels: docs, chore

#14386 chore(docs): update version flags for 2.14.2 and 2.13.5
  docs/install/kubernetes.md
Labels: hotfix

#14422 fix(examples/templates/gcp-devcontainer): fix location of env file
  examples/templates/gcp-devcontainer/main.tf
Labels: hotfix

#14383 chore!: allow CreateUser to accept multiple organizations
  cli/clitest/golden.go
  cli/schedule_test.go
  cli/server_createadminuser.go
  cli/user_delete_test.go
  cli/usercreate.go
  coderd/apidoc/docs.go
  coderd/apidoc/swagger.json
  coderd/coderdtest/coderdtest.go
  coderd/insights_test.go
  coderd/userauth.go
  coderd/userauth_test.go
  coderd/users.go
  coderd/users_test.go
  coderd/workspaceapps/apptest/apptest.go
  coderd/workspaces_test.go
  codersdk/users.go
  codersdk/users_test.go
  docs/reference/api/schemas.md
  docs/reference/api/users.md
  enterprise/coderd/groups_test.go
  enterprise/coderd/scim.go
  enterprise/coderd/userauth_test.go
  enterprise/coderd/users_test.go
  scaletest/createworkspaces/run.go
  site/e2e/api.ts
  site/src/api/api.ts
  site/src/api/typesGenerated.ts
  site/src/pages/CreateUserPage/CreateUserForm.tsx
Labels: release/breaking

#14455 fix: detect nested dotfiles scripts
  cli/dotfiles.go
  cli/dotfiles_test.go
Labels: hotfix

#14466 fix: wait for provisioner daemon jobs to finish after sigterm
  enterprise/cli/provisionerdaemonstart.go
Labels: hotfix

#14485 fix: fix light mode styles for organization delete button
  site/src/pages/ManagementSettingsPage/OrganizationSettingsPageView.stories.tsx
  site/src/pages/ManagementSettingsPage/OrganizationSettingsPageView.tsx
Labels: hotfix
