Repository coder/coder, pull requests merged in 2024-11, with the labels that each got.

#15314 fix: create contexts per sub-test to fix flake
  coderd/database/querier_test.go
Labels: hotfix

#15296 docs: add new best practice doc to speed up templates and workspaces
  docs/images/best-practice/build-timeline.png
  docs/install/kubernetes.md
  docs/manifest.json
  docs/tutorials/best-practices/index.md
  docs/tutorials/best-practices/speed-up-templates.md
Labels: docs

#15043 chore: fix docs/admin links and upgrade notice
  cli/server.go
  cli/templatecreate.go
  cli/templateedit.go
  cli/testdata/coder_templates_create_--help.golden
  cli/testdata/coder_templates_edit_--help.golden
  docs/admin/templates/extending-templates/web-ides.md
  docs/reference/cli/templates_create.md
  docs/reference/cli/templates_edit.md
  install.sh
  site/src/api/queries/workspaces.ts
Labels: docs, stale

#14983 docs: provide example regexes to properly escape . characters
  docs/admin/external-auth.md
Labels: stale

#15194 chore: update dependabot config and pin Docker images
  .github/dependabot.yaml
  .github/workflows/pr-deploy.yaml
  dogfood/contents/Dockerfile
  examples/jfrog/docker/build/Dockerfile
  scaletest/templates/scaletest-runner/Dockerfile
Labels: hotfix

#15349 chore: update workflow permissions
  .github/workflows/ci.yaml
  .github/workflows/contrib.yaml
  .github/workflows/pr-cleanup.yaml
Labels: hotfix

#15372 chore: correct typos and configure permissions in pr-deploy.yaml
  .github/workflows/pr-deploy.yaml
Labels: hotfix

#15382 docs: disable markdown link check on mailto links
  .github/workflows/mlc_config.json
  docs/changelogs/v2.0.0.md
  docs/tutorials/faqs.md
Labels: docs

#15405 fix: use NoLock dbmem subqueries for `GetWorkspaceAgentScriptTimingsByBuildID`
  coderd/database/dbmem/dbmem.go
  coderd/workspacebuilds_test.go
Labels: hotfix

#15436 chore: add VSCode TailwindCSS extension as recommendation
  .vscode/extensions.json
Labels: hotfix

#15415 docs: add deploy id to license doc
  docs/admin/licensing/index.md
  docs/images/admin/deployment-id-copy-clipboard.png
Labels: docs, customer-requested

#15384 docs: add workplace scheduling to manifest
  docs/manifest.json
Labels: docs

#15383 chore: clarify template provisioning speed doc
  docs/tutorials/best-practices/speed-up-templates.md
Labels: docs

#15430 chore: improve PR deployments
  .github/workflows/ci.yaml
  .github/workflows/pr-deploy.yaml
Labels: hotfix

#15313 chore: include if direct connection is over private network in ping diagnostics
  cli/cliui/agent.go
  cli/ping.go
Labels: stale, hotfix

#15484 ci: disable weekly-docs temporarily
  .github/workflows/weekly-docs.yaml
Labels: hotfix

#15101 docs: update template-from-scratch
  docs/images/templates/coder-login-web.png
  docs/images/templates/coder-session-token.png
  docs/images/templates/upload-create-template-form.png
  docs/images/templates/upload-create-your-first-template.png
  docs/images/templates/workspace-apps.png
  docs/tutorials/template-from-scratch.md
  site/src/pages/CreateTemplatePage/TemplateUpload.tsx
Labels: docs

#15501 docs: update version flags
  docs/install/kubernetes.md
  docs/install/releases.md
Labels: hotfix

#15514 ci: run go tests when examples are updated
  .github/workflows/ci.yaml
  examples/examples_test.go
Labels: hotfix

#15530 chore(coderd/database): fix duplicate migration numbers
  coderd/database/migrations/000275_rename_user_link_claims.down.sql
  coderd/database/migrations/000275_rename_user_link_claims.up.sql
Labels: hotfix

#15533 chore(coderd/database): fix duplicate migration numbers
  coderd/database/migrations/000274_rename_user_link_claims.down.sql
  coderd/database/migrations/000274_rename_user_link_claims.up.sql
  coderd/database/migrations/000275_check_tags.down.sql
  coderd/database/migrations/000275_check_tags.up.sql
Labels: hotfix

#15274 chore: generate countries.tsx from Go code
  Makefile
  cli/login.go
  coderd/rbac/object_gen.go
  codersdk/countries.go
  codersdk/rbacresources_gen.go
  scripts/apitypings/main.go
  scripts/typegen/codersdk.gotmpl
  scripts/typegen/countries.tstmpl
  scripts/typegen/main.go
  scripts/typegen/rbacobject.gotmpl
  scripts/typegen/typescript.tstmpl
  site/src/api/countriesGenerated.ts
  site/src/api/rbacresourcesGenerated.ts
  site/src/pages/SetupPage/SetupPageView.tsx
  site/src/pages/SetupPage/countries.tsx
Labels: community

#15509 feat!: allow disabling notifications
  cli/server.go
  cli/testdata/coder_server_--help.golden
  cli/testdata/server-config.yaml.golden
  coderd/apidoc/docs.go
  coderd/apidoc/swagger.json
  coderd/notifications/dispatch/smtp.go
  coderd/notifications/dispatch/smtp_test.go
  coderd/notifications/notifications_test.go
  codersdk/deployment.go
  codersdk/deployment_test.go
  docs/admin/monitoring/notifications/index.md
  docs/reference/api/general.md
  docs/reference/api/schemas.md
  docs/reference/cli/server.md
  enterprise/cli/testdata/coder_server_--help.golden
Labels: release/breaking

#15528 docs: add guide for CI/CD template testing
  docs/admin/templates/managing-templates/change-management.md
  docs/manifest.json
  docs/tutorials/testing-templates.md
Labels: docs

#15611 docs: create a markdown code snippet file to make it easier for contributors
  .gitignore
  .prettierignore
  .vscode/markdown.code-snippets
Labels: docs

#15182 fix(site): set min and max attributes for workspace number parameters
  site/src/components/RichParameterInput/RichParameterInput.stories.tsx
  site/src/components/RichParameterInput/RichParameterInput.tsx
  site/src/pages/WorkspaceSettingsPage/WorkspaceParametersPage/WorkspaceParametersForm.tsx
  site/src/pages/WorkspaceSettingsPage/WorkspaceParametersPage/WorkspaceParametersPage.test.tsx
Labels: community

#15631 fix: deduplicate agent script timings
  site/src/modules/workspaces/WorkspaceTiming/WorkspaceTimings.stories.tsx
  site/src/modules/workspaces/WorkspaceTiming/WorkspaceTimings.tsx
Labels: hotfix

#15657 fix: update `/builds` transition example
  coderd/apidoc/docs.go
  coderd/apidoc/swagger.json
  codersdk/workspaces.go
  docs/reference/api/builds.md
  docs/reference/api/schemas.md
Labels: docs, api, s3

#15662 chore: update testify to v1.9.0 in go.sum
  go.sum
Labels: hotfix

#15676 fix: add additional context to agent exec errors
  agent/agentexec/cli_linux.go
Labels: hotfix

#15658 chore: update group and role sync notes
  coderd/apidoc/docs.go
  coderd/apidoc/swagger.json
  codersdk/idpsync.go
  docs/reference/api/schemas.md
Labels: hotfix

#15551 feat(examples/templates/gcp-vm-container): promote module usage
  examples/templates/gcp-vm-container/main.tf
Labels: stale

#15552 feat(examples/templates/gcp-windows): add GCP region module
  examples/templates/gcp-windows/main.tf
Labels: stale

#15680 fix: update portforward storybook tests to include host
  site/src/modules/resources/PortForwardPopoverView.stories.tsx
Labels: hotfix

#15544 feat(examples/templates/devcontainer-docker): promote module usage
  examples/templates/devcontainer-docker/main.tf
Labels: stale
