Repository coder/coder, pull requests merged in 2024-02, with the labels that each got.

#11977 refactor(site): add table chosmetic changes
  .vscode/settings.json
  site/src/@types/mui.d.ts
  site/src/components/AvatarData/AvatarData.tsx
  site/src/pages/WorkspacesPage/WorkspacesTable.tsx
  site/src/theme/mui.ts
Labels: hotfix

#11979 refactor(site): only display quota if it is higher than 0
  site/src/pages/WorkspacePage/WorkspaceTopbar.tsx
Labels: hotfix

#11981 fix(site): fix text overflow on batch ws deletion
  site/src/pages/WorkspacesPage/BatchDeleteConfirmation.tsx
Labels: hotfix

#11984 chore(dogfood): fix nix icon path
  dogfood/main.tf
Labels: hotfix

#11919 docs: update remote docker host docs
  docs/platforms/docker.md
Labels: docs

#11995 fix(site): fix parameter input icon shrink
  site/src/components/RichParameterInput/RichParameterInput.tsx
Labels: hotfix

#11996 feat(site): show deprecation message on template page
  site/src/pages/TemplatePage/TemplatePageHeader.stories.tsx
  site/src/pages/TemplatePage/TemplatePageHeader.tsx
Labels: hotfix

#12007 docs: add faq for gateway reconnects
  docs/faqs.md
Labels: docs

#12039 fix: use `replace` when redirecting from /health
  site/src/AppRouter.tsx
Labels: hotfix

#10413 feat(cli): support header and header-command in config-ssh
  cli/configssh.go
  cli/configssh_test.go
Labels: community

#12043 docs: fix `/audit` & `/insights` params
  coderd/apidoc/docs.go
  coderd/apidoc/swagger.json
  coderd/audit.go
  coderd/insights.go
  docs/api/audit.md
  docs/api/insights.md
Labels: docs, api, bug

#12055 fix(site): enable submit when auto start and stop are both disabled
  site/src/components/Badges/Badges.tsx
  site/src/pages/WorkspaceSettingsPage/WorkspaceSchedulePage/WorkspaceScheduleForm.stories.tsx
  site/src/pages/WorkspaceSettingsPage/WorkspaceSchedulePage/WorkspaceScheduleForm.test.tsx
  site/src/pages/WorkspaceSettingsPage/WorkspaceSchedulePage/WorkspaceScheduleForm.tsx
Labels: hotfix

#12059 fix(site): fix infinity loading when template has no previous version
  site/src/api/api.ts
  site/src/api/queries/templates.ts
  site/src/pages/TemplatePage/TemplateFilesPage/TemplateFilesPage.test.tsx
  site/src/pages/TemplatePage/TemplateFilesPage/TemplateFilesPage.tsx
Labels: hotfix

#12073 docs: fix jetbrains reconnect faq
  docs/faqs.md
Labels: docs

#12103 chore(docs/networking/stun): fix diagram in section 2
  docs/networking/stun.md
Labels: hotfix

#12109 fix(docs): remove inline mermaid diagrams (#12107)
  docs/images/networking/stun1.png
  docs/images/networking/stun1.svg
  docs/images/networking/stun2.1.png
  docs/images/networking/stun2.1.svg
  docs/images/networking/stun2.2.png
  docs/images/networking/stun2.2.svg
  docs/images/networking/stun3.png
  docs/images/networking/stun3.svg
  docs/networking/stun.md
Labels: hotfix

#12108 ci: use repo secret for syncing winget-pkgs fork
  .github/workflows/release.yaml
Labels: community

#12120 chore(examples/templates/incus): fix incus group name in README
  examples/templates/incus/README.md
Labels: hotfix

#11911 docs: update modules docs
  docs/changelogs/v2.1.0.md
  docs/install/offline.md
  docs/templates/modules.md
Labels: docs

#12123 chore(examples/templates/incus): fix a typo
  examples/templates/incus/README.md
Labels: hotfix

#12153 chore(docs): update artifactory-integration guide
  docs/guides/artifactory-integration.md
Labels: docs, hotfix

#12113 docs: add kubevirt coder template in list of community templates
  examples/templates/community-templates.md
Labels: community

#12176 fix(codersdk): correctly log coordination error
  codersdk/workspaceagents.go
Labels: hotfix

#12177 fix(cli): avoid panic when external auth name isn't provided
  cli/externalauth.go
  cli/externalauth_test.go
Labels: hotfix

#12178 fix: improve clipboard support on HTTP connections and older browsers
  site/src/hooks/useClipboard.ts
Labels: hotfix

#12169 chore(dogfood): revert to pre-artifactory state
  .github/workflows/dogfood.yaml
  dogfood/main.tf
Labels: hotfix

#12186 ci: fix broken dogfood workflow
  .github/workflows/dogfood.yaml
Labels: hotfix

#12188 fix(site): fix language detection for Dockerfile
  site/src/modules/templates/TemplateFiles/TemplateFiles.tsx
Labels: hotfix

#12193 docs: fix header font
  docs/templates/resource-ordering.md
Labels: docs, hotfix

#12214 fix(helm)!: remove prometheus-http port declaration from coderd service spec
  docs/admin/prometheus.md
  helm/coder/templates/service.yaml
  helm/coder/tests/testdata/prometheus.golden
  helm/coder/values.yaml
Labels: security, release/breaking

#12227 revert: remove anti-flicker clipboard styling
  site/src/hooks/useClipboard.ts
Labels: hotfix

#12216 chore(site): refactor tests for global hooks  
  site/src/hooks/debounce.test.ts
  site/src/hooks/events.test.ts
  site/src/hooks/events.ts
  site/src/hooks/hookPolyfills.test.ts
Labels: site

#12231 fix(site): fix parameters field size
  site/src/components/Form/Form.tsx
  site/src/pages/CreateWorkspacePage/CreateWorkspacePageView.tsx
Labels: hotfix

#12247 chore(site): fix storybook for agent row with port forward button
  site/src/modules/resources/AgentRow.stories.tsx
Labels: hotfix

#12249 fix(site): fix error when typing long number on ttl
  site/src/pages/WorkspaceSettingsPage/WorkspaceSchedulePage/WorkspaceScheduleForm.tsx
Labels: hotfix

#12288 chore: upgrade `github.com/hashicorp/hc-install` to `v0.6.3`
  go.mod
  go.sum
Labels: hotfix

#12072 docs: add steps for postgres server verification
  docs/guides/postgres-ssl.md
  docs/install/kubernetes.md
  docs/manifest.json
Labels: docs, stale

#12295 docs: add gitlab self-managed example
  docs/admin/external-auth.md
Labels: community

#12255 chore(docs): inline OIDC flow diagram
  docs/admin/auth.md
Labels: community

#12298 chore(dogfood): bump jetbrains-gateway module to 1.0.6
  dogfood/main.tf
Labels: hotfix

#12316 chore(site): apply code conventions
  site/jest.setup.ts
  site/src/pages/CreateTemplatePage/BuildLogsDrawer.tsx
Labels: hotfix

#12334 docs: add k8s security reference
  docs/install/kubernetes.md
Labels: docs

#12352 fix: enhance readability of license key rows
  site/src/pages/DeploySettingsPage/LicensesSettingsPage/AddNewLicensePageView.tsx
Labels: hotfix

#12369 fix(site): fix form layout for tablet viewports
  site/src/components/Form/Form.tsx
Labels: hotfix
