Repository coder/coder, pull requests merged in 2024-12, with the labels that each got.

#15711 fix(site): avoid constructing invalid apps url
  site/src/utils/apps.ts
  site/src/utils/portForward.ts
Labels: hotfix

#15458 docs: improve dev containers documentation for user start-up
  docs/admin/index.md
  docs/admin/templates/index.md
  docs/admin/templates/managing-templates/devcontainers.md
  docs/admin/templates/managing-templates/devcontainers/add-devcontainer.md
  docs/admin/templates/managing-templates/devcontainers/devcontainer-releases-known-issues.md
  docs/admin/templates/managing-templates/devcontainers/devcontainer-security-caching.md
  docs/admin/templates/managing-templates/devcontainers/index.md
  docs/admin/templates/managing-templates/image-management.md
  docs/admin/templates/managing-templates/index.md
  docs/images/templates/template-menu-settings.png
  docs/manifest.json
Labels: docs

#15724 chore(cli): fix test flake introduced by #15688
  cli/delete_test.go
Labels: hotfix

#15756 fix: remove backtick from valid password characters
  examples/templates/azure-windows/main.tf
Labels: s3, bug risk, customer-reported

#15777 fix: fix broken 'Learn more' link in Listening Ports popup
  site/src/modules/resources/PortForwardButton.tsx
Labels: community

#15794 fix(examples/templates/aws-linux): add `hashicorp/cloudinit` provider
  examples/templates/aws-linux/main.tf
Labels: backport

#15800 fix(provisioner/terraform/tfparse): evaluate coder_parameter defaults with variables
  provisioner/terraform/tfparse/tfparse.go
  provisioner/terraform/tfparse/tfparse_test.go
Labels: backport

#15673 docs: add cli steps for org sync
  docs/admin/users/idp-sync.md
  docs/images/admin/users/organizations/idp-org-sync.png
Labels: docs

#15771 feat: add workspace build timing metrics
  provisionerd/provisionerd.go
  provisionerd/runner/runner.go
Labels: community

#15826 fix: docs reference in create headless user flow
  site/src/pages/CreateUserPage/CreateUserForm.tsx
Labels: site, s3, backport

#15733 docs: add istio docs
  docs/admin/integrations/istio.md
  docs/manifest.json
Labels: docs

#15732 docs: add new organizations docs to best practices section
  .github/.linkspector.yml
  docs/images/best-practice/organizations-architecture.png
  docs/manifest.json
  docs/tutorials/best-practices/organizations.md
Labels: docs

#15661 feat(site): add numbers to SSHButton content for clarity
  site/src/modules/resources/SSHButton/SSHButton.tsx
Labels: community

#15854 ci: try building images on GitHub-hosted runner again
  .github/workflows/ci.yaml
Labels: hotfix

#15868 fix: use random names for TestUpdateUserProfile
  coderd/users_test.go
Labels: hotfix

#15819 fix: encode `.dockerconfigjson` value for kubernetes-devcontainer example template
  examples/templates/kubernetes-devcontainer/main.tf
Labels: community

#15737 chore(docs): bump version in release calendar, kubernetes install docs
  docs/install/kubernetes.md
  docs/install/releases.md
  scratch/resourcepool-gcp-disk/main.tf
Labels: hotfix

#15873 ci: pin weekly-docs runner ubuntu version to 22.04
  .github/workflows/weekly-docs.yaml
Labels: hotfix

#15765 fix(dogfood): re-enable process priority management for dogfood
  dogfood/contents/main.tf
Labels: stale

#15633 feat: support created_at filter for the GET /users endpoint
  coderd/database/dbmem/dbmem.go
  coderd/database/modelqueries.go
  coderd/database/queries.sql.go
  coderd/database/queries/users.sql
  coderd/searchquery/search.go
  coderd/users.go
  coderd/users_test.go
  docs/admin/users/index.md
Labels: community

#15888 docs: copy edit the organizations doc and add link to best practices
  docs/admin/users/organizations.md
  docs/tutorials/using-organizations.md
Labels: docs

#15774 docs: move premium and enterprise badges from heading to info in admonition
  .vscode/markdown.code-snippets
  docs/admin/external-auth.md
  docs/admin/infrastructure/validated-architectures/index.md
  docs/admin/monitoring/notifications/index.md
  docs/admin/networking/index.md
  docs/admin/networking/port-forwarding.md
  docs/admin/setup/appearance.md
  docs/admin/templates/managing-templates/index.md
  docs/admin/templates/managing-templates/schedule.md
  docs/admin/templates/template-permissions.md
  docs/admin/users/groups-roles.md
  docs/admin/users/idp-sync.md
  docs/admin/users/oidc-auth.md
  docs/user-guides/workspace-access/vscode.md
  docs/user-guides/workspace-management.md
  docs/user-guides/workspace-scheduling.md
  enterprise/coderd/scim.go
  site/src/pages/DeploymentSettingsPage/SecuritySettingsPage/SecuritySettingsPageView.tsx
  site/src/pages/TemplateVersionEditorPage/PublishTemplateVersionDialog.tsx
Labels: docs

#15902 docs: add beta back to orgs
  docs/admin/users/organizations.md
Labels: docs, hotfix

#15901 docs: add context for wireguard in places referencing tailscale
  docs/admin/networking/index.md
  docs/admin/networking/stun.md
  docs/install/offline.md
  docs/tutorials/support-bundle.md
Labels: docs

#15897 fix(coderd/wsbuilder): correctly evaluate dynamic workspace tag values
  coderd/wsbuilder/wsbuilder.go
  coderd/wsbuilder/wsbuilder_test.go
  enterprise/coderd/coderdenttest/coderdenttest.go
  enterprise/coderd/workspaces_test.go
  provisioner/terraform/tfparse/tfparse.go
Labels: backport

#15918 chore: ignore storybook files on biome
  site/biome.jsonc
Labels: hotfix

#15799 chore(docs): clarify that variables be edited through the web UI
  docs/admin/templates/extending-templates/variables.md
Labels: stale

#15931 docs: add a link to the quickstart guide in the install Coder document
  docs/install/index.md
Labels: docs

#15945 fix: use icon mode for org avatar
  site/src/pages/WorkspacePage/WorkspaceTopbar.tsx
Labels: hotfix

#15545 feat(examples/templates/kubernetes-devcontainer): switch code-server to a module and add JetBrains
  examples/templates/kubernetes-devcontainer/main.tf
Labels: stale

#15961 chore: add Collapsible component
  site/package.json
  site/pnpm-lock.yaml
  site/src/components/Collapsible/Collapsible.stories.tsx
  site/src/components/Collapsible/Collapsible.tsx
Labels: hotfix

#15935 feat: allow entering non-default values in multi-select
  cli/cliui/select.go
  cli/cliui/select_test.go
  cli/prompts.go
Labels: community

#15546 feat(examples/templates/digitalocean-linux): add code-server and jetbrains gateway modules
  examples/templates/digitalocean-linux/main.tf
Labels: stale
