Repository coder/coder, pull requests merged in 2024-03, with the labels that each got.

#12377 chore: fix `Test_parseInsightsStartAndEndTime` flake
  coderd/insights_internal_test.go
Labels: hotfix

#12381 fix: add service banner to workspace page
  site/src/pages/WorkspacePage/WorkspacePage.tsx
Labels: community

#12201 feat: add support for Entra ID auth when using Azure DevOps external auth
  coderd/externalauth/externalauth.go
  codersdk/externalauth.go
  docs/admin/external-auth.md
  site/src/api/typesGenerated.ts
Labels: community

#12430 feat(site): display error messages on ws and access url health pages
  site/src/pages/HealthPage/AccessURLPage.stories.tsx
  site/src/pages/HealthPage/AccessURLPage.tsx
  site/src/pages/HealthPage/WebsocketPage.stories.tsx
  site/src/pages/HealthPage/WebsocketPage.tsx
  site/src/pages/HealthPage/WorkspaceProxyPage.stories.tsx
  site/src/pages/HealthPage/storybook.tsx
Labels: hotfix

#12419 fix: ensure auto-workspace creation waits until all parameters are ready
  site/src/pages/CreateWorkspacePage/CreateWorkspacePage.tsx
Labels: site, hotfix

#11946 docs: simplify install docs
  docs/images/install/coder-setup.png
  docs/install/index.md
  docs/templates/creating.md
Labels: docs

#12219 chore(site): update and refactor all custom hook tests that rely on React Router
  site/src/hooks/index.ts
  site/src/hooks/usePaginatedQuery.test.ts
  site/src/hooks/useSearchParamsKey.test.ts
  site/src/hooks/useSearchParamsKey.ts
  site/src/hooks/useTab.ts
  site/src/pages/CreateWorkspacePage/useWorkspaceDuplication.test.tsx
  site/src/pages/WorkspaceBuildPage/WorkspaceBuildPageView.tsx
  site/src/pages/WorkspacePage/Workspace.tsx
  site/src/pages/WorkspacePage/useResourcesNav.ts
  site/src/testHelpers/hooks.tsx
  site/src/testHelpers/renderHelpers.tsx
Labels: site

#12512 feat(site): add dotnet icon
  site/src/theme/icons.json
  site/static/icon/dotnet.svg
Labels: community

#12453 fix: devcontainer-docker bad default directory
  examples/templates/devcontainer-docker/main.tf
Labels: community

#12466 feat(cli): make url optional for login command (#10925)
  cli/login.go
  cli/login_test.go
  cli/logout_test.go
  cli/root.go
  cli/testdata/coder_login_--help.golden
  docs/cli/login.md
Labels: community

#12513 feat(site): add microsoft teams icon
  site/src/theme/icons.json
  site/static/icon/microsoft-teams.svg
Labels: community

#12547 fix(site): allow triggering builds on non-dirtied template version in TemplateVersionEditor
  site/src/pages/TemplateVersionEditorPage/TemplateVersionEditor.tsx
Labels: hotfix

#12551 chore: add package manager
  package.json
Labels: hotfix

#12556 chore: update duplicate migration file
  coderd/database/migrations/000201_ensure_default_everyone_group.down.sql
  coderd/database/migrations/000201_ensure_default_everyone_group.up.sql
Labels: hotfix

#12572 feat(site): add cpp icon
  site/src/theme/icons.json
  site/static/icon/cpp.svg
Labels: community

#12574 feat: upgrade tailscale fork to set TCP options for perf
  go.mod
  go.sum
Labels: networking

#12587 chore(examples/templates/incus): fix metadata
  examples/templates/incus/README.md
Labels: hotfix

#12589 chore(examples/templates/incus): fix metadata harder
  examples/templates/incus/README.md
Labels: hotfix

#12620 fix(coderd/database/migrations/000196_external_auth_providers_jsonb.up.sql): remove hardcoded public
  coderd/database/migrations/000196_external_auth_providers_jsonb.down.sql
  coderd/database/migrations/000196_external_auth_providers_jsonb.up.sql
Labels: community

#12621 fix: correct typo error about minTerraformVersion
  provisioner/terraform/serve.go
Labels: community

#12623 chore: fix false positives for docs links checker
  docs/admin/architectures/index.md
  docs/guides/artifactory-integration.md
Labels: hotfix

#12624 fix(cli): show error/hide help for unsupported subcommands (#10760)
  cli/help.go
  cli/portforward.go
  cli/portforward_test.go
  cli/root.go
  cli/root_test.go
  go.sum
Labels: community

#12630 chore: reduce slack spam for manually run docs link checker workflows
  .github/workflows/weekly-docs.yaml
Labels: hotfix

#12645 fix: fix flaky TestWorkspaceProxy_Server_PrometheusEnabled
  enterprise/cli/proxyserver_test.go
Labels: hotfix

#12658 docs: we do not offer phone support
  docs/changelogs/v2.7.2.md
  docs/changelogs/v2.8.0.md
  docs/enterprise.md
Labels: hotfix

#12663 chore: fix changelog typos
  docs/changelogs/v2.7.2.md
  docs/changelogs/v2.8.0.md
Labels: hotfix

#12644 chore!: remove max_ttl from templates
  cli/templatecreate.go
  cli/templateedit.go
  cli/templateedit_test.go
  cli/testdata/coder_server_--help.golden
  cli/testdata/coder_templates_create_--help.golden
  cli/testdata/coder_templates_edit_--help.golden
  cli/testdata/server-config.yaml.golden
  coderd/activitybump_test.go
  coderd/apidoc/docs.go
  coderd/apidoc/swagger.json
  coderd/database/dbmem/dbmem.go
  coderd/database/dump.sql
  coderd/database/migrations/000202_remove_max_ttl.down.sql
  coderd/database/migrations/000202_remove_max_ttl.up.sql
  coderd/database/modelqueries.go
  coderd/database/models.go
  coderd/database/queries.sql.go
  coderd/database/queries/templates.sql
  coderd/database/sqlc.yaml
  coderd/provisionerdserver/provisionerdserver_test.go
  coderd/schedule/autostop.go
  coderd/schedule/autostop_test.go
  coderd/schedule/template.go
  coderd/telemetry/telemetry.go
  coderd/templates.go
  coderd/templates_test.go
  coderd/workspaces.go
  codersdk/deployment.go
  codersdk/organizations.go
  codersdk/templates.go
  codersdk/users.go
  docs/admin/audit-logs.md
  docs/api/schemas.md
  docs/api/templates.md
  docs/cli/templates_create.md
  docs/cli/templates_edit.md
  enterprise/audit/table.go
  enterprise/cli/templateedit_test.go
  enterprise/cli/testdata/coder_server_--help.golden
  enterprise/coderd/schedule/template.go
  enterprise/coderd/schedule/template_test.go
  enterprise/coderd/templates_test.go
  site/src/api/typesGenerated.ts
  site/src/pages/CreateTemplatePage/CreateTemplateForm.tsx
  site/src/pages/CreateTemplatePage/utils.ts
  site/src/pages/TemplateSettingsPage/TemplateGeneralSettingsPage/TemplateSettingsPage.test.tsx
  site/src/pages/TemplateSettingsPage/TemplateSchedulePage/TTLHelperText.tsx
  site/src/pages/TemplateSettingsPage/TemplateSchedulePage/TemplateScheduleForm.tsx
  site/src/pages/TemplateSettingsPage/TemplateSchedulePage/TemplateSchedulePage.test.tsx
  site/src/pages/TemplateSettingsPage/TemplateSchedulePage/formHelpers.tsx
  site/src/testHelpers/entities.ts
Labels: release/breaking

#12729 fix: create workspace with optional auth providers
  site/src/pages/CreateWorkspacePage/CreateWorkspacePage.test.tsx
  site/src/pages/CreateWorkspacePage/CreateWorkspacePageView.stories.tsx
  site/src/pages/CreateWorkspacePage/CreateWorkspacePageView.tsx
Labels: hotfix

#12749 fix(cli): fix newline escape sequence in support blurb
  cli/support.go
Labels: hotfix

#12753 chore: make `build` only run on main
  .github/workflows/ci.yaml
Labels: hotfix

#12785 fix: nil ptr dereference when removing a license
  enterprise/coderd/coderd.go
Labels: hotfix

#12810 docs: document how to run workspace-proxy as a system service
  docs/admin/configure.md
  docs/admin/workspace-proxies.md
Labels: community
