Repository coder/coder, pull requests merged in 2024-09, with the labels that each got.

#14519 chore: add notification troubleshooting tips and make minor corrections
  docs/admin/notifications.md
  docs/images/admin/notification-states.png
Labels: hotfix

#14567 docs: add new marketecture
  docs/images/architecture-multi-region.png
  docs/images/architecture-single-region.png
Labels: docs

#14574 chore: update installation landing page
  docs/install/README.md
Labels: hotfix

#14584 fix: analyze build times over 30 days not 30 months
  coderd/metricscache/metricscache.go
Labels: hotfix

#14588 fix: increase text contrast for 'create workspace' button
  site/src/pages/TemplatesPage/TemplatesPageView.tsx
Labels: site, hotfix

#14591 test: add some default group/roles claims to testidp
  scripts/testidp/main.go
Labels: hotfix

#14618 docs: fix SCIM env var
  docs/admin/auth.md
Labels: docs

#14617 fix: prefer organization display name for workspaces table
  site/src/@types/storybook.d.ts
  site/src/pages/WorkspacesPage/WorkspacesPageView.stories.tsx
  site/src/pages/WorkspacesPage/WorkspacesTable.tsx
  site/src/testHelpers/storybook.tsx
Labels: site, hotfix

#14604 fix(helm): use list instead of dict for tolerations
  helm/coder/values.yaml
Labels: community

#14633 fix: remove coderdtest dependency from codersdk
  codersdk/users_test.go
Labels: hotfix

#14637 ci(.github): disable stalebot
  .github/workflows/stale.yaml
Labels: hotfix

#14601 fix(site): prevent 404s by removing version postfix from URLs
  site/src/utils/docs.ts
Labels: community

#14634 fix: fix TestPing/1Ping flake
  cli/ping_test.go
Labels: hotfix

#14520 feat: turn off notification via email
  coderd/database/queries.sql.go
  coderd/database/queries/notifications.sql
  coderd/notifications/dispatch/smtp/html.gotmpl
  coderd/notifications/enqueuer.go
  coderd/notifications/render/gotmpl_test.go
  coderd/notifications/types/payload.go
  site/src/api/queries/notifications.ts
  site/src/pages/UserSettingsPage/NotificationsPage/NotificationsPage.stories.tsx
  site/src/pages/UserSettingsPage/NotificationsPage/NotificationsPage.tsx
Labels: community

#14655 fix: avoid logging no such process errors for process priority
  agent/agent.go
Labels: hotfix

#14658 fix(scripts): allow docs_update_experiments.sh to be run on macOS
  scripts/lib.sh
  scripts/release/docs_update_experiments.sh
Labels: hotfix

#14660 fix: suppress benign errors when listing processes
  agent/agent.go
  agent/agentproc/proc_unix.go
Labels: hotfix

#14663 fix(docs): update terraform backend link
  docs/templates/change-management.md
Labels: hotfix

#14664 ci(.github): remove success from release-labels job
  .github/workflows/contrib.yaml
Labels: hotfix

#14667 ci(.github): run release-labels when draft PRs are ready
  .github/workflows/contrib.yaml
Labels: hotfix

#14629 chore: add navigation test for workspace details page
  site/src/contexts/auth/RequireAuth.tsx
  site/src/pages/WorkspacePage/WorkspacePage.test.tsx
  site/src/pages/WorkspacePage/WorkspaceTopbar.tsx
  site/src/pages/WorkspacesPage/WorkspacesPageView.stories.tsx
  site/src/testHelpers/renderHelpers.tsx
Labels: site

#14709 chore: remove db import from cli package
  cli/root.go
Labels: hotfix

#14631 feat!: add `--default-token-lifetime`
  cli/testdata/coder_server_--help.golden
  cli/testdata/server-config.yaml.golden
  coderd/apidoc/docs.go
  coderd/apidoc/swagger.json
  coderd/apikey.go
  coderd/apikey_test.go
  coderd/provisionerdserver/provisionerdserver.go
  coderd/users_test.go
  codersdk/deployment.go
  docs/reference/api/general.md
  docs/reference/api/schemas.md
  docs/reference/cli/server.md
  enterprise/cli/testdata/coder_server_--help.golden
  site/src/api/typesGenerated.ts
Labels: release/breaking

#14714 fix: use floats in report template
  cli/server.go
  coderd/database/migrations/000254_fix_report_float.down.sql
  coderd/database/migrations/000254_fix_report_float.up.sql
  coderd/notifications/notifications_test.go
  coderd/notifications/reports/generator.go
Labels: hotfix

#14738 chore: fix comment
  site/src/theme/index.ts
Labels: hotfix

#14675 fix(docs): add dotfiles module reference
  docs/dotfiles.md
Labels: community

#14743 chore(site): add cursor ide icon
  site/src/theme/icons.json
  site/static/icon/cursor.svg
Labels: hotfix

#14748 chore(dogfood): add cursor IDE
  dogfood/contents/main.tf
Labels: hotfix

#14771 fix: use latest build version name on workspace page
  site/src/pages/WorkspacePage/WorkspaceTopbar.tsx
Labels: hotfix

#14728 chore: add ability to include custom protoc-gen-go dependency in nix flake
  flake.nix
  scripts/update-flake.sh
Labels: community

#14790 chore(docs): correct external auth typos
  docs/admin/external-auth.md
Labels: docs, chore, hotfix

#14812 fix: make sure avatar data for owner displays correctly
  site/src/pages/WorkspacePage/WorkspaceTopbar.tsx
Labels: hotfix

#14836 fix(examples/templates/aws-devcontainer): fix code-server module address
  examples/templates/aws-devcontainer/main.tf
Labels: hotfix

#14828 docs: add `coderd_workspace_latest_build_status` prometheus metric
  docs/admin/prometheus.md
  scripts/metricsdocgen/metrics
Labels: hotfix

#14786 chore(docs): outline new feature stages
  docs/contributing/feature-stages.md
  docs/manifest.json
Labels: docs

#14807 chore(docs): update JetBrains gateway setup
  docs/images/gateway/plugin-connect-to-coder.png
  docs/user-guides/workspace-access/jetbrains.md
Labels: docs

#14864 chore(docs): removes dead navigation options
  docs/admin/monitoring/metrics.md
  docs/manifest.json
  docs/user-guides/workspace-access/jetbrains.md
Labels: docs, hotfix

#14813 feat: implement feature to create a token on behalf of another user in the cli
  cli/testdata/coder_tokens_create_--help.golden
  cli/tokens.go
  cli/tokens_test.go
  docs/reference/cli/tokens_create.md
Labels: community
