Repository coder/coder, pull requests merged in 2024-07, with the labels that each got.

#13722 docs: move architecture to top level
  docs/admin/scaling/scale-testing.md
  docs/admin/scaling/scale-utility.md
  docs/architecture/1k-users.md
  docs/architecture/2k-users.md
  docs/architecture/3k-users.md
  docs/architecture/architecture.md
  docs/architecture/validated-arch.md
  docs/images/icons/container.svg
  docs/manifest.json
  docs/platforms/other.md
Labels: docs

#13756 chore: remove database import from cli
  cli/root.go
Labels: hotfix

#13767 ci: use postgres version 13 to test migrations
  .github/workflows/release.yaml
Labels: hotfix

#13769 ci: remove release make concurrency to fix docker image race
  .github/workflows/release.yaml
Labels: hotfix

#13766 docs: bump mainline version to v2.13.0
  docs/install/kubernetes.md
Labels: hotfix

#13773 docs: clarify envbox version pinning
  examples/templates/envbox/README.md
  examples/templates/envbox/main.tf
Labels: docs

#13781 fix(dogfood/Dockerfile): revert add explicit --chown to COPY directive (#13569)
  dogfood/Dockerfile
  dogfood/files/etc/sudoers.d/nopasswd
Labels: hotfix

#13681 chore: update troubleshooting documentation about dir setting
  docs/templates/troubleshooting.md
Labels: community

#13795 docs: update release schedule
  docs/install/kubernetes.md
  docs/install/releases.md
Labels: hotfix

#13815 chore: fix typo in oidctest package
  coderd/coderdtest/oidctest/idp.go
Labels: hotfix

#13820 chore: upgrade Go to 1.22.5
  .github/actions/setup-go/action.yaml
  dogfood/Dockerfile
  go.mod
Labels: hotfix

#13823 chore(docs): correct typo in release calendar
  docs/install/releases.md
Labels: hotfix

#13842 chore(offlinedocs): update braces to `v3.0.3`
  offlinedocs/pnpm-lock.yaml
Labels: hotfix

#13849 chore: use base64 encoded kubeconfig for pr deployments
  .github/workflows/pr-deploy.yaml
Labels: hotfix

#13851 chore: use base64 encoded kubeconfig for pr deployments
  .github/workflows/pr-deploy.yaml
Labels: hotfix

#13824 fix: remove `templates plan` docs
  cli/templates.go
  cli/testdata/coder_templates_--help.golden
  docs/cli/templates.md
Labels: cli, bug

#13854 feat(site): display tooltip in bars for app usage chart
  site/src/pages/TemplatePage/TemplateInsightsPage/TemplateInsightsPage.tsx
  site/src/theme/mui.ts
Labels: hotfix

#13837 fix!: remove `TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA` cipher by default
  .github/workflows/typos.toml
  cli/server.go
  cli/server_internal_test.go
Labels: release/breaking

#13814 feat: added whomai cmd to coder cli
  cli/root.go
  cli/testdata/coder_--help.golden
  cli/testdata/coder_whoami_--help.golden
  cli/whoami.go
  cli/whoami_test.go
  docs/cli.md
  docs/cli/whoami.md
  docs/manifest.json
Labels: community

#13862 fix: add missing `nolint` comment
  coderd/database/dbpurge/dbpurge_test.go
Labels: hotfix

#13863 chore: improve notifications tests
  coderd/database/dbauthz/dbauthz_test.go
  coderd/database/dbmem/dbmem.go
  coderd/notifications/manager_test.go
  coderd/notifications/notifications_test.go
  coderd/notifications/utils_test.go
Labels: chore

#13785 docs: fix vs code web module reference
  docs/ides/web-ides.md
Labels: docs, bug

#13724 docs: fix docs on deploying workspaces in additional namespaces
  docs/platforms/kubernetes/additional-clusters.md
Labels: docs

#13898 fix: revert "fix(dogfood/Dockerfile): change ownership of /etc/sudoers.d t…
  dogfood/Dockerfile
Labels: hotfix

#13933 chore: move `notiffake` to `testutil`
  coderd/autobuild/lifecycle_executor_test.go
  coderd/coderdtest/coderdtest.go
  testutil/notifications.go
Labels: hotfix

#13940 fix: hardcode default organization id in `DashboardProvider`
  site/src/modules/dashboard/DashboardProvider.tsx
  site/src/pages/CreateTemplatePage/CreateTemplatePage.test.tsx
  site/src/pages/CreateWorkspacePage/CreateWorkspacePage.test.tsx
Labels: hotfix

#13902 feat: add SMTP auth & TLS support
  .github/workflows/typos.toml
  cli/testdata/coder_server_--help.golden
  cli/testdata/server-config.yaml.golden
  coderd/apidoc/docs.go
  coderd/apidoc/swagger.json
  coderd/notifications/dispatch/fixtures/ca.conf
  coderd/notifications/dispatch/fixtures/ca.crt
  coderd/notifications/dispatch/fixtures/ca.key
  coderd/notifications/dispatch/fixtures/ca.srl
  coderd/notifications/dispatch/fixtures/generate.sh
  coderd/notifications/dispatch/fixtures/password.txt
  coderd/notifications/dispatch/fixtures/server.conf
  coderd/notifications/dispatch/fixtures/server.crt
  coderd/notifications/dispatch/fixtures/server.csr
  coderd/notifications/dispatch/fixtures/server.key
  coderd/notifications/dispatch/fixtures/v3_ext.conf
  coderd/notifications/dispatch/smtp.go
  coderd/notifications/dispatch/smtp/html.gotmpl
  coderd/notifications/dispatch/smtp_test.go
  coderd/notifications/dispatch/smtp_util_test.go
  codersdk/deployment.go
  docs/api/general.md
  docs/api/schemas.md
  docs/cli/server.md
  enterprise/cli/testdata/coder_server_--help.golden
  flake.nix
  go.mod
  go.sum
  site/src/api/typesGenerated.ts
Labels: feature

#13784 feat: implement multi-org template gallery
  codersdk/organizations.go
  site/src/api/api.ts
  site/src/api/queries/audits.ts
  site/src/api/queries/templates.ts
  site/src/api/typesGenerated.ts
  site/src/components/Filter/filter.tsx
  site/src/modules/templates/TemplateCard/TemplateCard.stories.tsx
  site/src/modules/templates/TemplateCard/TemplateCard.tsx
  site/src/pages/StarterTemplatesPage/StarterTemplatesPage.tsx
  site/src/pages/StarterTemplatesPage/StarterTemplatesPageView.stories.tsx
  site/src/pages/StarterTemplatesPage/StarterTemplatesPageView.tsx
  site/src/pages/TemplatesPage/MultiOrgTemplatePage/TemplatesPageView.stories.tsx
  site/src/pages/TemplatesPage/MultiOrgTemplatePage/TemplatesPageView.tsx
  site/src/pages/TemplatesPage/TemplatePage/TemplatesPageView.stories.tsx
  site/src/pages/TemplatesPage/TemplatePage/TemplatesPageView.tsx
  site/src/pages/TemplatesPage/TemplatesPage.tsx
  site/src/pages/WorkspacesPage/WorkspacesPage.tsx
  site/src/pages/WorkspacesPage/filter/menus.tsx
  site/src/utils/filters.ts
  site/src/utils/starterTemplates.ts
  site/src/utils/templateAggregators.ts
Labels: feature

#13950 chore: only add Meticulous recorder when running in dev mode
  site/src/index.tsx
Labels: community

#13951 chore(docs): update version flags for 2.12.4 and 2.13.1
  docs/install/kubernetes.md
Labels: hotfix

#13964 docs: update caddy config example & guide
  examples/web-server/caddy/Caddyfile
  examples/web-server/caddy/README.md
Labels: community

#13918 chore(docs): add missing author to support bundle guide
  docs/guides/support-bundle.md
Labels: docs, chore

#13796 chore(examples): update sample devcontainer templates
  examples/templates/devcontainer-docker/README.md
  examples/templates/devcontainer-docker/main.tf
  examples/templates/devcontainer-kubernetes/README.md
  examples/templates/devcontainer-kubernetes/main.tf
Labels: stale

#13980 chore(scripts): fix cherry-pick check in `check_commit_metadata.sh`
  scripts/release/check_commit_metadata.sh
Labels: hotfix

#13981 fix: test: no parallel when starting Prometheus endpoint
  enterprise/cli/provisionerdaemons_test.go
Labels: hotfix

#13983 fix: use correct webhook endpoint YAML attribute name
  cli/testdata/server-config.yaml.golden
  codersdk/deployment.go
  docs/cli/server.md
Labels: hotfix

#13992 fix(site): select default organization on /organizations page
  site/src/pages/ManagementSettingsPage/ManagementSettingsLayout.tsx
Labels: hotfix

#13994 chore(scripts): fix cherry-pick check in `check_commit_metadata.sh`
  scripts/release/check_commit_metadata.sh
Labels: hotfix

#13995 chore(docs): update version flag for patches 2.12.5 and 2.13.2
  docs/install/kubernetes.md
Labels: hotfix

#13996 test: skip `TestProvisionerDaemon_PrometheusEnabled`
  enterprise/cli/provisionerdaemons_test.go
Labels: hotfix

#13997 chore: add stable version info to repository-dispatch event
  .github/workflows/release.yaml
Labels: hotfix

#14015 fix: resolve text overflow issues for workspace empty state
  site/src/pages/WorkspacesPage/WorkspacesEmpty.tsx
Labels: hotfix

#14021 feat(site): add JetBrains fleet icon
  site/src/theme/icons.json
  site/static/icon/fleet.svg
Labels: community

#14022 docs: add proxmox coder template in list of community templates
  examples/templates/community-templates.md
Labels: community

#14025 fix: handle legacy licenses missing feature_set field
  site/src/api/api.ts
  site/src/pages/DeploySettingsPage/LicensesSettingsPage/LicenseCard.tsx
  site/src/testHelpers/entities.ts
Labels: hotfix

#14047 fix: duplicate tags map in mutation to resolve race
  enterprise/cli/create_test.go
  provisionersdk/provisionertags.go
Labels: hotfix
