Repository coder/coder, pull requests merged in 2025-08, with the labels that each got.

#18681 docs: update module registry URLs to correct path structure
  docs/admin/templates/extending-templates/modules.md
Labels: docs

#19118 chore: add openai icon
  site/src/theme/externalImages.ts
  site/src/theme/icons.json
  site/static/icon/openai.svg
Labels: community

#19186 chore(docs): update calendar and helm install docs for v2.25.0
  docs/install/kubernetes.md
  docs/install/releases/index.md
Labels: docs

#19250 docs: fix marketplace links for GCP
  docs/install/cloud/compute-engine.md
Labels: docs

#19329 chore: update docs to mention debug logging config explicitly
  docs/admin/monitoring/logs.md
Labels: docs

#19441 chore: fix typo in clientNetcheckSummary for support bundle command
  cli/support.go
Labels: cli

#19482 chore: fix typo in clientNetcheckSummary for support bundle command
  cli/support.go
Labels: cli

#18816 docs: add dev containers and scheduling to prebuilt workspaces known issues
  docs/admin/templates/extending-templates/prebuilt-workspaces.md
Labels: docs

#19437 feat(docs): add docs for external workspaces
  docs/admin/templates/index.md
  docs/admin/templates/managing-templates/external-workspaces.md
  docs/images/admin/templates/external-workspace.png
  docs/manifest.json
Labels: cherry-pick/v2.26

#19612 fix(coderd/taskname): ensure generated name is within 32 byte limit
  coderd/taskname/taskname.go
Labels: cherry-pick/v2.26

#19615 chore(docs): set external workspaces as premium feature in manifest.json
  docs/manifest.json
Labels: cherry-pick/v2.26

#19503 feat: add prebuild timing metrics to Prometheus
  cli/server.go
  coderd/coderd.go
  coderd/coderdtest/coderdtest.go
  coderd/database/dbauthz/dbauthz.go
  coderd/database/dbauthz/dbauthz_test.go
  coderd/database/dbmetrics/querymetrics.go
  coderd/database/dbmock/dbmock.go
  coderd/database/querier.go
  coderd/database/queries.sql.go
  coderd/database/queries/prebuilds.sql
  coderd/database/queries/workspaces.sql
  coderd/prometheusmetrics/prometheusmetrics.go
  coderd/prometheusmetrics/prometheusmetrics_test.go
  coderd/provisionerdserver/metrics.go
  coderd/provisionerdserver/provisionerdserver.go
  coderd/provisionerdserver/provisionerdserver_test.go
  docs/admin/integrations/prometheus.md
  docs/admin/templates/extending-templates/prebuilt-workspaces.md
  enterprise/coderd/provisionerdaemons.go
  enterprise/coderd/workspaces_test.go
  scripts/metricsdocgen/metrics
Labels: cherry-pick/v2.26

#19601 fix: suppress license expiry warning if a new license covers the gap
  enterprise/coderd/license/license.go
  enterprise/coderd/license/license_internal_test.go
  enterprise/coderd/license/license_test.go
Labels: cherry-pick/v2.26

#19641 fix(coderd): fix logic for reporting prebuilt workspace duration metric
  coderd/provisionerdserver/metrics.go
  enterprise/coderd/coderdenttest/coderdenttest.go
  enterprise/coderd/workspaces_test.go
Labels: cherry-pick/v2.26

#19636 chore: replace GetManagedAgentCount query with aggregate table
  coderd/database/dbauthz/dbauthz.go
  coderd/database/dbauthz/dbauthz_test.go
  coderd/database/dbmetrics/querymetrics.go
  coderd/database/dbmock/dbmock.go
  coderd/database/dump.sql
  coderd/database/migrations/000362_aggregate_usage_events.down.sql
  coderd/database/migrations/000362_aggregate_usage_events.up.sql
  coderd/database/migrations/migrate_test.go
  coderd/database/models.go
  coderd/database/querier.go
  coderd/database/querier_test.go
  coderd/database/queries.sql.go
  coderd/database/queries/licenses.sql
  coderd/database/queries/usageevents.sql
  coderd/database/unique_constraint.go
  enterprise/coderd/coderd.go
  enterprise/coderd/license/license.go
  enterprise/coderd/license/license_test.go
Labels: cherry-pick/v2.26
