Repository coder/coder, pull requests merged in 2025-02, with the labels that each got.

#16378 feat: add docs explaining how Coder integrates with PlatformX
  docs/admin/integrations/platformx.md
  docs/images/integrations/platformx-screenshot.png
  docs/manifest.json
Labels: docs

#16429 fix(flake.nix): readd grep for agent startup script
  flake.nix
Labels: hotfix

#16434 fix(docs): indicate that custom roles are premium only
  docs/admin/users/groups-roles.md
Labels: docs, enterprise

#16439 fix: log unsuccessful webhook response body as a string
  coderd/notifications/dispatch/webhook.go
Labels: community

#16450 fix(coderd): set default provisionerjobs limit to 50
  coderd/provisionerjobs.go
  coderd/provisionerjobs_test.go
Labels: hotfix

#16453 ci: ignore 503s on wiki.ubuntu.com
  .github/.linkspector.yml
Labels: hotfix

#16466 ci: set xcode sdk version when building dylib
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
Labels: hotfix

#16467 docs: cleanup Zed editor connection docs
  docs/user-guides/workspace-access/zed.md
Labels: hotfix

#16457 docs: comment out optional lines in `values.yaml`
  docs/install/kubernetes.md
Labels: docs

#16484 docs: update licensing steps in faq
  docs/admin/licensing/index.md
  docs/tutorials/faqs.md
Labels: docs

#16502 chore(agent/agentcontainers): skip TestDockerCLIContainerLister by default
  agent/agentcontainers/containers_dockercli.go
  agent/agentcontainers/containers_internal_test.go
Labels: hotfix

#16504 ci: add missing files to gen/mark-fresh
  .github/workflows/ci.yaml
  Makefile
Labels: hotfix

#16530 chore: enable forward ports to Coder UI using any host for Vite dev server
  site/vite.config.mts
Labels: hotfix

#16512 feat: add run_as_non_root=True to Kubernetes Starter template
  examples/templates/kubernetes/main.tf
Labels: community

#16545 docs: fix link to CODER_QUIET_HOURS_DEFAULT_SCHEDULE in schedule doc
  docs/admin/templates/managing-templates/schedule.md
Labels: docs

#16542 docs: add markdown fields in webhook payloads
  docs/admin/monitoring/notifications/slack.md
  docs/admin/monitoring/notifications/teams.md
Labels: docs

#16516 chore(docs): update list of events in notification docs
  docs/admin/monitoring/notifications/index.md
Labels: docs

#16565 fix(vpn/tunnel): fix panic when starting tunnel with headers
  vpn/tunnel.go
  vpn/tunnel_internal_test.go
Labels: hotfix

#16573 chore: add top level permission to docs-ci
  .github/workflows/docs-ci.yaml
Labels: hotfix

#15138 docs: add mention of CLI command to create token on behalf of another user
  docs/admin/users/sessions-tokens.md
Labels: docs

#16314 docs: add doc on how to try a coder-preview build
  docs/install/docker.md
Labels: docs

#16597 docs: highlight the tip in coder-preview section and move step
  docs/install/docker.md
Labels: docs

#16602 docs: update ssh key description
  coderd/apidoc/docs.go
  coderd/apidoc/swagger.json
  codersdk/gitsshkey.go
  docs/reference/api/schemas.md
Labels: hotfix

#16605 chore: add biome to devcontainer.json
  .devcontainer/devcontainer.json
Labels: hotfix

#16619 chore(docs): fix 2.19 release status in `releases.md`
  docs/install/releases.md
Labels: hotfix

#16614 fix!: enforce agent names be case-insensitive-unique per-workspace
  coderd/provisionerdserver/provisionerdserver.go
  coderd/provisionerdserver/provisionerdserver_test.go
  provisioner/terraform/resources.go
  provisioner/terraform/resources_test.go
Labels: release/breaking

#16641 fix!: enforce regex for agent names
  coderd/database/dbauthz/dbauthz_test.go
  coderd/database/dbfake/dbfake.go
  coderd/provisionerdserver/provisionerdserver.go
  coderd/provisionerdserver/provisionerdserver_test.go
  coderd/templateversions_test.go
  coderd/workspaceagents_test.go
  coderd/workspacebuilds_test.go
  coderd/workspaceresourceauth_test.go
  coderd/workspaces_test.go
  enterprise/coderd/templates_test.go
  provisioner/appslug.go
  provisioner/appslug_test.go
  provisioner/regexes.go
  provisioner/regexes_test.go
  provisioner/terraform/resources.go
  provisioner/terraform/resources_test.go
  site/site.go
Labels: release/breaking

#16658 docs: update Coder version in Kubernetes doc
  docs/install/kubernetes.md
  docs/install/releases.md
Labels: docs

#16717 fix: remove provisioners from deployment sidebar
  site/src/modules/management/DeploymentSidebarView.tsx
Labels: hotfix

#16724 docs: clarified prometheus integration behavior
  docs/admin/integrations/prometheus.md
Labels: docs

#16719 docs: document new feature stages
  docs/about/feature-stages.md
  docs/contributing/feature-stages.md
  docs/manifest.json
Labels: docs

#16727 docs: fix broken links in feature-stages
  docs/admin/monitoring/notifications/index.md
  docs/changelogs/v0.26.0.md
  docs/changelogs/v2.9.0.md
  docs/install/releases.md
  scripts/release/docs_update_experiments.sh
  site/src/components/FeatureStageBadge/FeatureStageBadge.tsx
Labels: docs, hotfix

#16730 docs: copy edit early access section in feature-stages doc
  docs/about/feature-stages.md
Labels: docs

#16748 fix(agent/agentcontainers): remove empty warning if no containers exist
  agent/agentcontainers/containers_dockercli.go
Labels: hotfix
