Repository coder/coder, pull requests merged in 2025-09, with the labels that each got.

#19667 fix: expire token for prebuilds user when regenerating session token
  coderd/apikey.go
  coderd/apikey_test.go
  coderd/database/dbauthz/dbauthz.go
  coderd/database/dbauthz/dbauthz_test.go
  coderd/database/dbgen/dbgen.go
  coderd/database/dbmetrics/querymetrics.go
  coderd/database/dbmock/dbmock.go
  coderd/database/dbpurge/dbpurge.go
  coderd/database/dbpurge/dbpurge_test.go
  coderd/database/querier.go
  coderd/database/queries.sql.go
  coderd/database/queries/apikeys.sql
  coderd/provisionerdserver/provisionerdserver.go
  coderd/provisionerdserver/provisionerdserver_test.go
Labels: cherry-pick/v2.25, cherry-pick/v2.26, cherry-pick/v2.24

#19700 docs: add guidelines about PR size
  docs/about/contributing/CONTRIBUTING.md
Labels: docs

#19788 fix!: use client ip when creating connection logs for workspace proxied app accesses
  coderd/database/dump.sql
  coderd/database/migrations/000369_nullable_conn_log_ip.down.sql
  coderd/database/migrations/000369_nullable_conn_log_ip.up.sql
  codersdk/connectionlog.go
  enterprise/coderd/connectionlog.go
  enterprise/coderd/workspaceproxy.go
  enterprise/coderd/workspaceproxy_test.go
  enterprise/wsproxy/tokenprovider.go
  enterprise/wsproxy/wsproxysdk/wsproxysdk.go
  enterprise/wsproxy/wsproxysdk/wsproxysdk_test.go
  site/src/api/typesGenerated.ts
Labels: release/breaking

#19810 chore: fix grammar issue
  docs/tutorials/quickstart.md
Labels: docs

#19888 chore(site): add rustdesk icon
  site/src/theme/icons.json
  site/static/icon/rustdesk.svg
Labels: community

#19951 chore: update okta icon
  site/src/theme/externalImages.ts
  site/static/icon/okta.svg
Labels: community

#19966 fix(coderd)!: only show task status for current build
  cli/exp_task_status_test.go
  coderd/aitasks.go
  coderd/aitasks_test.go
  codersdk/aitasks.go
  site/src/api/typesGenerated.ts
Labels: release/breaking

#19982 refactor!: rename prompt field to input for task creation
  cli/exp_task_create.go
  cli/exp_task_create_test.go
  coderd/aitasks.go
  coderd/aitasks_test.go
  codersdk/aitasks.go
  site/src/api/typesGenerated.ts
  site/src/pages/TasksPage/TaskPrompt.tsx
  site/src/pages/TasksPage/TasksPage.stories.tsx
Labels: release/breaking

#19750 feat: remove agent name from app URLs
  coderd/agentapi/manifest.go
  coderd/agentapi/manifest_test.go
  coderd/database/db2sdk/db2sdk.go
  coderd/workspaceapps/apptest/setup.go
  coderd/workspaceapps/appurl/appurl.go
  coderd/workspaceapps/appurl/appurl_test.go
Labels: stale

#19884 fix: fix for template dormancy hour/day toggle
  site/src/components/DurationField/DurationField.stories.tsx
  site/src/components/DurationField/DurationField.tsx
Labels: site, enterprise, template
