Repository coder/coder, pull requests merged in 2025-04, with the labels that each got.

#17183 chore(mcp): fix test flakes
  mcp/mcp_test.go
Labels: hotfix

#17092 docs: add new cursor and windsurf docs
  docs/images/user-guides/ides/windsurf-coder-extension.png
  docs/manifest.json
  docs/user-guides/workspace-access/cursor.md
  docs/user-guides/workspace-access/index.md
  docs/user-guides/workspace-access/windsurf.md
Labels: docs

#17190 fix(cli): exp mcp: remove unnecessary cli flag
  cli/exp_mcp.go
Labels: hotfix

#17161 docs: update SMTP configuration in notifications docs
  docs/admin/monitoring/notifications/index.md
Labels: docs

#16879 docs: clarify that CODER_EXTERNAL_AUTH_0_ID is used in callback URLs
  docs/admin/external-auth.md
Labels: docs

#17199 chore(docs): move feature stage docs to install directory
  docs/admin/monitoring/notifications/index.md
  docs/changelogs/v0.26.0.md
  docs/changelogs/v2.10.0.md
  docs/changelogs/v2.9.0.md
  docs/install/cli.md
  docs/install/index.md
  docs/install/kubernetes.md
  docs/install/rancher.md
  docs/install/releases/feature-stages.md
  docs/install/releases/index.md
  docs/manifest.json
  scripts/release/docs_update_experiments.sh
  site/src/components/FeatureStageBadge/FeatureStageBadge.tsx
Labels: docs

#17096 docs: remove beta badge from notifications doc
  docs/manifest.json
Labels: docs

#16548 docs: add new workspace notifications dashboard and config
  docs/admin/monitoring/notifications/index.md
  docs/images/icons/inbox-in.svg
  docs/manifest.json
  docs/user-guides/inbox/index.md
Labels: docs

#16563 docs: add new section on managing provisioners from the dashboard
  .vscode/settings.json
  coderd/provisionerdserver/acquirer_test.go
  docs/admin/infrastructure/architecture.md
  docs/admin/monitoring/health-check.md
  docs/admin/monitoring/logs.md
  docs/admin/provisioners/index.md
  docs/admin/provisioners/manage-provisioner-jobs.md
  docs/admin/security/secrets.md
  docs/admin/setup/index.md
  docs/admin/templates/creating-templates.md
  docs/admin/templates/extending-templates/modules.md
  docs/admin/templates/extending-templates/provider-authentication.md
  docs/admin/users/groups-roles.md
  docs/admin/users/organizations.md
  docs/images/admin/provisioners/provisioner-jobs.png
  docs/manifest.json
  docs/tutorials/best-practices/scale-coder.md
  docs/tutorials/best-practices/security-best-practices.md
  docs/tutorials/best-practices/speed-up-templates.md
Labels: docs

#17220 docs: clarify details around MCP
  docs/manifest.json
  docs/tutorials/ai-agents/create-template.md
  docs/tutorials/ai-agents/custom-agents.md
  docs/tutorials/ai-agents/headless.md
Labels: hotfix

#17222 ci: linkspector: fix 403 to external site
  .github/.linkspector.yml
Labels: hotfix

#17204 fix: silence One-Way WebSocket error messages in React Strict Mode
  site/src/utils/OneWayWebSocket.ts
Labels: hotfix

#17226 docs: remove enterprise from docs
  docs/admin/external-auth.md
  docs/admin/monitoring/notifications/index.md
  docs/admin/networking/index.md
  docs/admin/networking/port-forwarding.md
  docs/admin/security/audit-logs.md
  docs/admin/setup/appearance.md
  docs/admin/templates/extending-templates/process-logging.md
  docs/admin/templates/managing-templates/index.md
  docs/admin/templates/managing-templates/schedule.md
  docs/admin/users/groups-roles.md
  docs/admin/users/idp-sync.md
  docs/admin/users/oidc-auth.md
  docs/manifest.json
  docs/user-guides/workspace-management.md
  docs/user-guides/workspace-scheduling.md
  helm/provisioner/README.md
Labels: docs

#17233 fix: prevent invalid render output for build logs
  site/src/components/Logs/LogLine.tsx
  site/src/components/Logs/Logs.stories.tsx
  site/src/components/Logs/Logs.tsx
  site/src/modules/resources/AgentLogs/AgentLogLine.tsx
  site/src/modules/resources/AgentLogs/AgentLogs.tsx
  site/src/modules/resources/AgentLogs/mocks.tsx
  site/src/modules/resources/AgentRow.tsx
  site/src/modules/workspaces/WorkspaceBuildLogs/WorkspaceBuildLogs.tsx
  site/src/pages/WorkspaceBuildPage/WorkspaceBuildPageView.tsx
Labels: hotfix

#17235 chore: skip flakey e2e tests
  site/e2e/tests/externalAuth.spec.ts
  site/e2e/tests/outdatedAgent.spec.ts
Labels: hotfix

#17258 fix!: use names not IDs for agent SSH key seed
  agent/agent.go
  cli/ssh_test.go
Labels: release/breaking

#16734 docs: add a section about latency and how it's measured
  docs/admin/networking/index.md
  docs/admin/networking/workspace-proxies.md
Labels: docs

#17265 fix: log correct error on drpc connection close error
  agent/agent.go
Labels: community

#17162 docs: document that default GitHub app requires device flow
  docs/admin/users/github-auth.md
Labels: docs

#17283 fix(agent): log correct error variable in createTailnet
  agent/agent.go
Labels: community

#17281 docs: add zed code_app to extending-templates doc
  docs/admin/templates/extending-templates/index.md
Labels: docs

#17285 docs: remove blank inbox doc
  docs/images/icons/inbox-in.svg
  docs/manifest.json
  docs/user-guides/inbox/index.md
Labels: docs, hotfix

#17286 chore: fix swagger type of AuditLog AdditionalFields
  coderd/apidoc/docs.go
  coderd/apidoc/swagger.json
  codersdk/audit.go
  docs/reference/api/audit.md
  docs/reference/api/schemas.md
Labels: hotfix

#17166 feat(provisioner): propagate trace info
  provisioner/terraform/otelenv.go
  provisioner/terraform/otelenv_internal_test.go
  provisioner/terraform/provision.go
Labels: community

#17164 docs: add details on external authentication priority
  docs/admin/external-auth.md
Labels: docs

#17318 docs: update note markdown in parameters
  docs/admin/templates/extending-templates/parameters.md
Labels: docs, hotfix

#17324 chore: remove usage of github.com/go-chi/render
  provisionersdk/agent_test.go
Labels: hotfix

#17342 feat(testutil): add GetRandomNameHyphenated
  cli/templatepush_test.go
  coderd/templateversions_test.go
  testutil/names.go
Labels: hotfix

#17231 docs: move AI-agent docs out of tutorials and into a top-level section
  docs/coder-ai/README.md
  docs/coder-ai/agents.md
  docs/coder-ai/best-practices.md
  docs/coder-ai/coder-dashboard.md
  docs/coder-ai/create-template.md
  docs/coder-ai/custom-agents.md
  docs/coder-ai/headless.md
  docs/coder-ai/ide-integration.md
  docs/coder-ai/issue-tracker.md
  docs/coder-ai/securing.md
  docs/images/icons/wand.svg
  docs/manifest.json
Labels: docs

#17344 docs: update aws instance recommendations
  docs/admin/infrastructure/validated-architectures/1k-users.md
  docs/admin/infrastructure/validated-architectures/2k-users.md
  docs/admin/infrastructure/validated-architectures/3k-users.md
  docs/admin/infrastructure/validated-architectures/index.md
Labels: docs

#17346 docs: hotfix rename coder-ai readme to index
  docs/coder-ai/index.md
  docs/manifest.json
Labels: docs, hotfix

#17348 docs: rename coder-ai directory to avoid wildcard removal
  docs/ai-coder/agents.md
  docs/ai-coder/best-practices.md
  docs/ai-coder/coder-dashboard.md
  docs/ai-coder/create-template.md
  docs/ai-coder/custom-agents.md
  docs/ai-coder/headless.md
  docs/ai-coder/ide-integration.md
  docs/ai-coder/index.md
  docs/ai-coder/issue-tracker.md
  docs/ai-coder/securing.md
  docs/manifest.json
Labels: docs, hotfix

#17347 chore: update trivy
  go.mod
  go.sum
Labels: hotfix

#15962 docs: add steps to pre-install JetBrains IDE backend
  docs/admin/templates/extending-templates/jetbrains-gateway.md
  docs/changelogs/v2.1.5.md
  docs/install/offline.md
  docs/manifest.json
  docs/user-guides/workspace-access/index.md
  docs/user-guides/workspace-access/jetbrains.md
  docs/user-guides/workspace-access/jetbrains/index.md
  docs/user-guides/workspace-access/jetbrains/jetbrains-airgapped.md
  docs/user-guides/workspace-access/jetbrains/jetbrains-pre-install.md
  docs/user-guides/workspace-lifecycle.md
Labels: docs

#17365 fix(codersdk/toolsdk): fix tool schemata
  cli/exp_mcp.go
  codersdk/toolsdk/toolsdk.go
Labels: hotfix

#17353 chore!: remove JFrog integration
  coderd/apidoc/docs.go
  coderd/apidoc/swagger.json
  coderd/database/dbauthz/dbauthz.go
  coderd/database/dbauthz/dbauthz_test.go
  coderd/database/dbmem/dbmem.go
  coderd/database/dbmetrics/querymetrics.go
  coderd/database/dbmock/dbmock.go
  coderd/database/querier.go
  coderd/database/queries.sql.go
  coderd/database/queries/jfrog.sql
  codersdk/jfrog.go
  docs/reference/api/enterprise.md
  docs/reference/api/schemas.md
  enterprise/coderd/coderd.go
  enterprise/coderd/jfrog.go
  enterprise/coderd/jfrog_test.go
  site/src/api/api.ts
  site/src/api/queries/integrations.ts
  site/src/api/typesGenerated.ts
  site/src/modules/resources/AgentRow.stories.tsx
  site/src/modules/resources/AgentRow.tsx
  site/src/modules/resources/XRayScanAlert.tsx
  site/src/testHelpers/handlers.ts
Labels: release/breaking

#17392 chore(dogfood): switch to JetBrains Toolbox module
  dogfood/coder/main.tf
Labels: hotfix

#17400 fix: increase context timeout in `TestProvisionerd/MaliciousTar` to avoid flake
  provisionerd/provisionerd_test.go
Labels: hotfix

#17312 docs: document workspace naming rules and restrictions
  coderd/apidoc/docs.go
  coderd/apidoc/swagger.json
  codersdk/organizations.go
  docs/reference/api/schemas.md
  docs/user-guides/workspace-management.md
Labels: docs, api

#17284 chore: clarify error variable name in doAttach
  agent/reconnectingpty/screen.go
Labels: community

#17332 chore(site): add mlflow, lakefs and argo logos
  site/src/theme/icons.json
  site/static/icon/argo-workflows.svg
  site/static/icon/lakefs.svg
  site/static/icon/mlflow.svg
Labels: community

#17413 docs: update jfrog-artifactory integration docs
  docs/admin/integrations/jfrog-artifactory.md
Labels: hotfix

#17438 chore: format code
  coderd/idpsync/organizations_test.go
Labels: hotfix

#17441 test: fix flake in TestRoleSyncTable with test cases sharing resources
  coderd/idpsync/role_test.go
Labels: hotfix

#17427 chore: reduce storybook flakes
  site/src/pages/DeploymentSettingsPage/OverviewPage/OverviewPageView.stories.tsx
  site/src/pages/DeploymentSettingsPage/OverviewPage/UserEngagementChart.tsx
  site/src/pages/OrganizationSettingsPage/CustomRolesPage/PermissionPillsList.stories.tsx
  site/src/pages/OrganizationSettingsPage/OrganizationProvisionerJobsPage/JobRow.tsx
  site/src/pages/OrganizationSettingsPage/OrganizationProvisionersPage/ProvisionerRow.tsx
  site/src/pages/TerminalPage/TerminalPage.stories.tsx
  site/src/pages/WorkspacePage/WorkspaceTopbar.stories.tsx
  site/src/utils/schedule.tsx
Labels: hotfix

#17440 chore: upgrade fish to v4
  dogfood/coder/files/etc/apt/sources.list.d/ppa.list
  dogfood/coder/files/usr/share/keyrings/fish-shell.gpg
  dogfood/coder/update-keys.sh
  site/src/modules/resources/AgentLogs/mocks.tsx
Labels: hotfix

#17464 chore: add agent query parameter to `VSCodeDevContainerButton`
  site/src/modules/resources/AgentDevcontainerCard.tsx
Labels: hotfix

#17484 fix: fix empty workspaces result
  site/src/pages/WorkspacesPage/WorkspacesEmpty.tsx
Labels: hotfix

#17511 fix: don't show promote button for members
  site/src/pages/TemplatePage/TemplateVersionsPage/VersionRow.tsx
Labels: hotfix

#17514 fix: fix build timeline scale for longer builds
  site/src/modules/workspaces/WorkspaceTiming/Chart/utils.ts
  site/src/modules/workspaces/WorkspaceTiming/WorkspaceTimings.stories.tsx
  site/src/modules/workspaces/WorkspaceTiming/WorkspaceTimings.tsx
Labels: hotfix

#17457 docs: document GIT_ASKPASS for OAuth connections
  docs/admin/external-auth.md
Labels: docs

#17521 docs: edit the ai agents doc
  docs/ai-coder/agents.md
Labels: docs

#17550 docs: fix ssh coder example in testing-templates doc
  docs/tutorials/testing-templates.md
Labels: docs, hotfix

#17553 fix(examples/templates/docker-devcontainer): update folder path and provider version constraint
  examples/templates/docker-devcontainer/main.tf
Labels: community

#17590 fix: fix script timings spam in the workspace UI
  site/src/pages/WorkspacePage/WorkspaceReadyPage.tsx
Labels: hotfix

#17593 fix: handle missed actions in workspace timings
  site/src/modules/workspaces/WorkspaceTiming/ResourcesChart.tsx
  site/src/modules/workspaces/WorkspaceTiming/WorkspaceTimings.stories.tsx
Labels: hotfix

#17610 test: avoid sharing `echo.Responses` across tests
  cli/restart_test.go
  cli/start_test.go
Labels: hotfix

#17604 chore(cli): fix test flake when running in coder workspace
  cli/exp_mcp_test.go
Labels: hotfix

#17607 chore: update windsurf icon
  site/static/icon/windsurf.svg
Labels: hotfix

#17619 fix: update devcontainer data every 10s
  site/src/modules/resources/AgentRow.tsx
Labels: hotfix

#17620 docs: update ai feature stage to beta and ease the intro note's tone
  docs/ai-coder/best-practices.md
  docs/ai-coder/coder-dashboard.md
  docs/ai-coder/create-template.md
  docs/ai-coder/custom-agents.md
  docs/ai-coder/headless.md
  docs/ai-coder/ide-integration.md
  docs/ai-coder/index.md
  docs/ai-coder/issue-tracker.md
  docs/ai-coder/securing.md
  docs/images/guides/ai-agents/landing.png
  docs/images/icons/wand.svg
  docs/manifest.json
Labels: docs

#17623 refactor: change how timings are formatted
  site/src/modules/workspaces/WorkspaceTiming/Chart/utils.ts
Labels: hotfix
