Repository coder/coder, pull requests merged in 2025-03, with the labels that each got.

#16555 docs: fix anchor and repo links
  docs/admin/networking/index.md
  docs/admin/networking/port-forwarding.md
  docs/admin/templates/extending-templates/icons.md
  docs/admin/templates/extending-templates/web-ides.md
Labels: stale, community

#16407 feat(provisioner): add support for workspace_owner_rbac_roles
  coderd/provisionerdserver/provisionerdserver.go
  coderd/provisionerdserver/provisionerdserver_test.go
  provisioner/terraform/provision.go
  provisioner/terraform/provision_test.go
  provisionersdk/proto/provisioner.pb.go
  provisionersdk/proto/provisioner.proto
  site/e2e/provisionerGenerated.ts
Labels: stale, community

#16663 docs: document default GitHub OAuth2 configuration and device flow
  docs/admin/users/github-auth.md
Labels: docs

#16773 fix: use `dbtime` in `dbmem` query to fix flake
  coderd/database/dbmem/dbmem.go
Labels: hotfix

#16774 feat: update default audit log avatar
  site/src/components/Avatar/Avatar.tsx
  site/src/pages/AuditPage/AuditLogRow/AuditLogRow.tsx
Labels: hotfix

#16544 docs: add Coder Desktop early preview documentation
  docs/images/icons/computer-code.svg
  docs/images/templates/coder-login-web.png
  docs/images/user-guides/desktop/chrome-insecure-origin.png
  docs/images/user-guides/desktop/coder-desktop-pre-sign-in.png
  docs/images/user-guides/desktop/coder-desktop-session-token.png
  docs/images/user-guides/desktop/coder-desktop-sign-in.png
  docs/images/user-guides/desktop/coder-desktop-workspaces.png
  docs/images/user-guides/desktop/firefox-insecure-origin.png
  docs/images/user-guides/desktop/mac-allow-vpn.png
  docs/manifest.json
  docs/user-guides/desktop/index.md
Labels: docs

#16582 docs: add oom/ood to notifications
  docs/admin/monitoring/notifications/index.md
  docs/admin/templates/extending-templates/resource-monitoring.md
  docs/manifest.json
Labels: docs

#16612 docs: document workspace presets feature
  docs/admin/templates/extending-templates/parameters.md
  docs/images/admin/templates/extend-templates/template-preset-dropdown.png
Labels: docs

#16815 chore: remove unused code
  site/.storybook/preview.jsx
  site/e2e/helpers.ts
  site/src/@types/storybook.d.ts
  site/src/api/queries/insights.ts
  site/src/api/queries/templates.ts
  site/src/components/DropdownMenu/DropdownMenu.tsx
  site/src/components/ErrorBoundary/GlobalErrorBoundary.tsx
  site/src/components/IconField/EmojiPicker.tsx
  site/src/components/Paywall/PopoverPaywall.tsx
  site/src/components/Select/Select.stories.tsx
  site/src/components/SettingsHeader/SettingsHeader.tsx
  site/src/modules/dashboard/Navbar/DeploymentDropdown.tsx
  site/src/modules/dashboard/Navbar/MobileMenu.stories.tsx
  site/src/modules/dashboard/Navbar/MobileMenu.tsx
  site/src/modules/provisioners/ProvisionerAlert.tsx
  site/src/modules/provisioners/ProvisionerTagsField.tsx
  site/src/modules/resources/TerminalLink/TerminalLink.tsx
  site/src/pages/CreateUserPage/CreateUserPage.tsx
  site/src/pages/CreateWorkspacePage/CreateWorkspacePage.tsx
  site/src/pages/DeploymentSettingsPage/ExternalAuthSettingsPage/ExternalAuthSettingsPage.tsx
  site/src/pages/DeploymentSettingsPage/GeneralSettingsPage/GeneralSettingsPage.tsx
  site/src/pages/DeploymentSettingsPage/GeneralSettingsPage/GeneralSettingsPageView.tsx
  site/src/pages/DeploymentSettingsPage/NetworkSettingsPage/NetworkSettingsPage.tsx
  site/src/pages/DeploymentSettingsPage/NotificationsPage/NotificationsPage.tsx
  site/src/pages/DeploymentSettingsPage/OAuth2AppsSettingsPage/CreateOAuth2AppPage.tsx
  site/src/pages/DeploymentSettingsPage/OAuth2AppsSettingsPage/CreateOAuth2AppPageView.tsx
  site/src/pages/DeploymentSettingsPage/OAuth2AppsSettingsPage/EditOAuth2AppPage.tsx
  site/src/pages/DeploymentSettingsPage/SecuritySettingsPage/SecuritySettingsPage.tsx
  site/src/pages/DeploymentSettingsPage/UserAuthSettingsPage/UserAuthSettingsPage.tsx
  site/src/pages/OrganizationSettingsPage/CustomRolesPage/CustomRolesPageView.tsx
  site/src/pages/OrganizationSettingsPage/IdpSyncPage/IdpSyncPage.tsx
  site/src/pages/OrganizationSettingsPage/OrganizationRedirect.test.tsx
  site/src/pages/OrganizationSettingsPage/OrganizationSettingsPageView.tsx
  site/src/pages/OrganizationSettingsPage/ProvisionersPage/ProvisionerDaemonsPage.tsx
  site/src/pages/OrganizationSettingsPage/ProvisionersPage/ProvisionerJobsPage.tsx
  site/src/pages/OrganizationSettingsPage/UserTable/EditRolesButton.tsx
  site/src/pages/ResetPasswordPage/ChangePasswordPage.stories.tsx
  site/src/pages/ResetPasswordPage/ChangePasswordPage.tsx
  site/src/pages/ResetPasswordPage/RequestOTPPage.tsx
  site/src/pages/SetupPage/SetupPage.tsx
  site/src/pages/SetupPage/SetupPageView.tsx
  site/src/pages/TemplatePage/TemplateInsightsPage/TemplateInsightsPage.stories.tsx
  site/src/pages/TemplateSettingsPage/TemplateGeneralSettingsPage/TemplateSettingsPage.test.tsx
  site/src/pages/TemplatesPage/CreateTemplateButton.tsx
  site/src/pages/UserSettingsPage/ExternalAuthPage/ExternalAuthPageView.tsx
  site/src/pages/UserSettingsPage/NotificationsPage/NotificationsPage.stories.tsx
  site/src/pages/UserSettingsPage/OAuth2ProviderPage/OAuth2ProviderPageView.tsx
  site/src/pages/UserSettingsPage/SecurityPage/SecurityForm.tsx
  site/src/pages/UsersPage/UsersFilter.tsx
  site/src/pages/UsersPage/UsersPage.tsx
  site/src/pages/WorkspacePage/Workspace.stories.tsx
  site/src/pages/WorkspacesPage/WorkspacesEmpty.tsx
  site/src/pages/WorkspacesPage/filter/menus.tsx
Labels: hotfix

#16817 docs: update docs for 2.20 release
  docs/install/kubernetes.md
  docs/install/releases.md
Labels: hotfix

#16826 docs: add beta label to workspace presets
  docs/admin/templates/extending-templates/parameters.md
Labels: docs, hotfix

#16761 docs: fix formatting of note callouts
  docs/admin/provisioners.md
  docs/admin/templates/extending-templates/parameters.md
  examples/examples.gen.json
  examples/templates/aws-devcontainer/README.md
  examples/templates/docker-devcontainer/README.md
  examples/templates/gcp-devcontainer/README.md
  examples/templates/kubernetes-devcontainer/README.md
Labels: community

#16856 fix: remove <title> from bug template
  .github/ISSUE_TEMPLATE/1-bug.yaml
Labels: hotfix

#16857 test: skip tests affected by daylight savings issues
  coderd/database/querier_test.go
  coderd/insights_internal_test.go
Labels: hotfix

#16868 revert: "chore: enable SBOM attestation for image builds"
  .github/workflows/release.yaml
  dogfood/contents/files/etc/docker/daemon.json
  scripts/build_docker.sh
Labels: hotfix

#16890 refactor: name null users in audit logs
  site/src/pages/AuditPage/AuditLogRow/AuditLogDescription/AuditLogDescription.stories.tsx
  site/src/pages/AuditPage/AuditLogRow/AuditLogDescription/AuditLogDescription.tsx
  site/src/pages/AuditPage/AuditLogRow/AuditLogDescription/BuildAuditDescription.tsx
Labels: hotfix

#16888 docs: add warning for multiple Coder Desktop mac installations
  docs/user-guides/desktop/index.md
Labels: docs

#16902 docs: remove broken gfm alert
  docs/user-guides/desktop/index.md
Labels: hotfix

#16918 docs: use consistent examples in prometheus doc and add namespaceSelector spec
  docs/admin/integrations/prometheus.md
Labels: docs

#16923 docs: fix offline dockerfile bug
  docs/install/offline.md
Labels: docs, s3

#16920 docs: add cgroup memory troubleshooting to install doc
  docs/admin/templates/troubleshooting.md
  docs/images/install/coder-setup.png
  docs/images/screenshots/welcome-create-admin-user.png
  docs/install/cli.md
  docs/install/index.md
Labels: docs

#16943 docs: adjust order of options in external-auth
  docs/admin/external-auth.md
Labels: docs, customer-reported

#16944 fix: fix audit log search
  site/src/pages/AuditPage/AuditPage.tsx
Labels: hotfix

#16886 fix: update `WorkspacesEmpty.tsx` from material ui to tailwind
  site/src/pages/WorkspacesPage/WorkspacesEmpty.tsx
Labels: community

#16937 docs: add AWS AMI upgrade instructions
  docs/install/upgrade.md
Labels: docs, community

#16882 docs: document steps for adding cert to JetBrains plugin settings
  docs/user-guides/workspace-access/jetbrains.md
Labels: docs

#16989 chore: don't autofocus `OrganizationAutocomplete` on user creation page
  site/src/components/OrganizationAutocomplete/OrganizationAutocomplete.tsx
Labels: hotfix

#17000 fix: fix overflowing text in inbox notifications
  site/src/modules/notifications/NotificationsInbox/InboxItem.stories.tsx
  site/src/modules/notifications/NotificationsInbox/InboxItem.tsx
Labels: hotfix

#17001 fix: close popover when notification settings are clicked
  site/src/modules/notifications/NotificationsInbox/InboxPopover.tsx
  site/src/modules/notifications/NotificationsInbox/NotificationsInbox.tsx
Labels: hotfix

#16973 docs: add AWS AMI upgrade instructions
  docs/install/upgrade.md
Labels: docs

#17007 feat: update notification badge to support 99+
  site/src/modules/notifications/NotificationsInbox/UnreadBadge.stories.tsx
  site/src/modules/notifications/NotificationsInbox/UnreadBadge.tsx
Labels: hotfix

#16534 docs: add new doc on how to deploy Coder on Rancher
  docs/images/icons/rancher.svg
  docs/images/install/coder-rancher.png
  docs/install/rancher.md
  docs/manifest.json
Labels: docs

#17005 feat: make notifications header sticky
  site/src/modules/notifications/NotificationsInbox/InboxPopover.stories.tsx
  site/src/modules/notifications/NotificationsInbox/InboxPopover.tsx
Labels: hotfix

#17021 fix: add notifications back to desktop
  site/src/modules/dashboard/Navbar/NavbarView.tsx
Labels: hotfix

#17026 chore(cli): wait for agent to connect before dialing it in TestExpRpty
  cli/exp_rpty_test.go
Labels: hotfix

#17041 chore: linkspector ignore mutagen.io
  .github/.linkspector.yml
Labels: hotfix

#16941 docs: document definition of workspace activity
  docs/admin/templates/managing-templates/schedule.md
  docs/user-guides/workspace-scheduling.md
Labels: docs

#17044 fix: fix double ws connection for notifications
  site/src/modules/dashboard/Navbar/NavbarView.tsx
Labels: hotfix

#17075 feat: support markdown in notifications
  site/src/modules/notifications/NotificationsInbox/InboxItem.stories.tsx
  site/src/modules/notifications/NotificationsInbox/InboxItem.tsx
Labels: hotfix

#17080 docs: add a table to feature stages doc
  docs/about/feature-stages.md
Labels: docs

#17112 refactor: improve markdown rendering on notifications
  site/package.json
  site/pnpm-lock.yaml
  site/src/modules/notifications/NotificationsInbox/InboxItem.stories.tsx
  site/src/modules/notifications/NotificationsInbox/InboxItem.tsx
  site/tailwind.config.js
Labels: hotfix

#17098 docs: add troubleshooting section to Desktop docs
  docs/user-guides/desktop/index.md
Labels: docs

#17122 fix(scripts/check_unstaged.sh): add argument separator in git diff command
  scripts/check_unstaged.sh
Labels: hotfix

#17125 chore: linkspector: ignore 503s from docs.github.com
  .github/.linkspector.yml
Labels: hotfix

#17116 chore(enterprise/dbcrypt): adjust behaviour of TestHelpMeEncryptSomeValue
  enterprise/dbcrypt/cipher_internal_test.go
Labels: hotfix

#17114 feat(cli): push dynamically generated templates with version name
  cli/templatepush.go
Labels: cli

#17119 refactor: add nice enter animation for notification badge
  site/src/modules/notifications/NotificationsInbox/InboxButton.tsx
  site/src/modules/notifications/NotificationsInbox/UnreadBadge.tsx
Labels: hotfix

#17135 chore: upgrade msw to 2.4.3
  site/package.json
  site/pnpm-lock.yaml
Labels: hotfix

#17142 fix: fix data race in echo provisioner
  provisioner/echo/serve.go
Labels: hotfix

#17146 docs: edit workspace lifecycle description
  docs/manifest.json
Labels: docs

#17115 feat: set icons for each type of notification
  coderd/inboxnotifications.go
  coderd/inboxnotifications_internal_test.go
  coderd/inboxnotifications_test.go
  codersdk/inboxnotification.go
  site/src/api/typesGenerated.ts
  site/src/components/Avatar/Avatar.tsx
  site/src/modules/notifications/NotificationsInbox/InboxAvatar.stories.tsx
  site/src/modules/notifications/NotificationsInbox/InboxAvatar.tsx
  site/src/modules/notifications/NotificationsInbox/InboxItem.stories.tsx
  site/src/modules/notifications/NotificationsInbox/InboxItem.tsx
  site/src/testHelpers/entities.ts
Labels: hotfix
