Repository coder/coder, pull requests merged in 2025-01, with the labels that each got.

#15990 docs: document issue with direnv and nix-shell on macOS
  docs/CONTRIBUTING.md
Labels: community

#16018 chore: remove leftover meticulous code
  site/package.json
  site/pnpm-lock.yaml
Labels: hotfix

#15970 docs: update external auth to better explain process
  docs/admin/external-auth.md
Labels: community

#16031 chore: replace `github.com/go-jose/go-jose/v3` with v4
  coderd/coderdtest/oidctest/idp.go
  coderd/jwtutils/jws.go
  coderd/workspaceapps/apptest/apptest.go
  go.mod
  go.sum
Labels: community

#15527 docs: markdown fixes and edits
  docs/admin/external-auth.md
  docs/admin/integrations/island.md
  docs/admin/integrations/jfrog-artifactory.md
  docs/admin/integrations/jfrog-xray.md
  docs/admin/integrations/prometheus.md
  docs/admin/integrations/vault.md
  docs/admin/monitoring/health-check.md
  docs/contributing/frontend.md
Labels: docs

#16023 fix(provisioner/terraform/tfparse): skip evaluation of unrelated parameters
  coderd/templateversions_test.go
  enterprise/coderd/workspaces_test.go
  provisioner/terraform/parse.go
  provisioner/terraform/tfparse/tfparse.go
  provisioner/terraform/tfparse/tfparse_test.go
Labels: backport

#16034 chore: cleanup Makefile
  Makefile
Labels: hotfix

#16037 chore: ignore cherry-pick-bot created branches for Deploy PR
  .github/workflows/pr-deploy.yaml
Labels: hotfix

#16041 chore: fix template-from-scratch.md
  docs/tutorials/template-from-scratch.md
Labels: community

#16052 chore(docs): skip january release in calendar
  docs/install/releases.md
Labels: hotfix

#16027 docs: update external auth to better explain process
  docs/admin/external-auth.md
  docs/admin/setup/index.md
Labels: docs

#16051 docs: fix workspacebuilds logs api docs
  coderd/workspacebuilds.go
Labels: community

#15956 fix: provide useful debug info when retrieving a version from GitHub fails
  install.sh
Labels: stale

#16092 fix: ensure active Deployment Page nav links are highlighted
  site/src/components/Sidebar/Sidebar.tsx
  site/src/modules/management/DeploymentSidebarView.tsx
Labels: hotfix

#16091 docs: fix typo in prometheus.md
  docs/admin/integrations/prometheus.md
Labels: community

#16099 fix(site): fix typo on new workspace screen
  site/src/components/Form/Form.stories.tsx
  site/src/pages/CreateWorkspacePage/CreateWorkspacePageView.tsx
Labels: hotfix

#16078 feat: add --network-info-dir and --network-info-interval flags to coder ssh
  cli/ssh.go
  cli/ssh_test.go
  cli/testdata/coder_ssh_--help.golden
  cli/vscodessh.go
  docs/reference/cli/ssh.md
Labels: community

#16080 chore: add parent PID to coder ssh log file name
  cli/ssh.go
Labels: community

#16088 feat: add --ssh-host-prefix flag for "coder ssh"
  cli/ssh.go
  cli/ssh_test.go
  cli/testdata/coder_ssh_--help.golden
  docs/reference/cli/ssh.md
Labels: community

#16141 fix: improve shell compatibility of netstat check in test
  cli/ssh_test.go
Labels: hotfix

#16145 refactor: set min width as 80px for buttons
  site/src/components/Button/Button.tsx
Labels: hotfix

#16094 chore: update `github.com/cespare/xxhash` to v2
  go.mod
  go.sum
  provisioner/terraform/internal/timings_test_utils.go
  provisioner/terraform/timings.go
Labels: community

#16165 chore: use better PR titles for cherry-pick-bot PRs
  .github/cherry-pick-bot.yml
Labels: hotfix

#16209 refactor: replace MUI buttons on Alerts
  site/src/components/Alert/Alert.stories.tsx
  site/src/components/Alert/Alert.tsx
  site/src/components/Alert/ErrorAlert.stories.tsx
  site/src/pages/TerminalPage/TerminalAlerts.tsx
Labels: hotfix

#16210 fix: display error when a build fails on template editor
  site/src/components/GlobalSnackbar/GlobalSnackbar.tsx
  site/src/pages/TemplateVersionEditorPage/TemplateVersionEditor.tsx
Labels: hotfix

#16211 refactor: replace MUI button on FullPageHorizontalForm
  site/src/components/FullPageForm/FullPageHorizontalForm.tsx
Labels: hotfix

#15904 docs: add new scaling doc to best practices section
  docs/admin/infrastructure/scale-testing.md
  docs/admin/infrastructure/scale-utility.md
  docs/manifest.json
  docs/tutorials/best-practices/scale-coder.md
Labels: docs

#16229 fix: update licenses to seats
  site/src/pages/DeploymentSettingsPage/LicensesSettingsPage/LicenseSeatConsumptionChart.tsx
Labels: hotfix

#16249 fix(vpn): pass dup'd FDs to tunnel
  vpn/dylib/lib.go
Labels: hotfix

#16251 refactor: remove Docs from the navbar
  site/src/modules/dashboard/Navbar/MobileMenu.stories.tsx
  site/src/modules/dashboard/Navbar/MobileMenu.tsx
  site/src/modules/dashboard/Navbar/Navbar.tsx
  site/src/modules/dashboard/Navbar/NavbarView.test.tsx
  site/src/modules/dashboard/Navbar/NavbarView.tsx
Labels: hotfix

#16242 docs: add zed editor doc to workspace-access
  docs/images/zed/zed-ssh-open-remote.png
  docs/manifest.json
  docs/user-guides/workspace-access/zed.md
Labels: docs

#16305 fix(cli): remove loading indicator when pinging with verbose logs
  cli/ping.go
Labels: hotfix

#16333 docs: add a screenshot of the admin settings to doc
  docs/admin/index.md
  docs/images/admin/admin-settings-general.png
Labels: docs

#16338 docs(admin/templates/): fix terraform provider links
  docs/admin/templates/extending-templates/workspace-tags.md
  docs/admin/templates/troubleshooting.md
Labels: community

#16352 fix(vpn): configure dns hosts with username
  vpn/client.go
  vpn/tun_darwin.go
Labels: hotfix

#16354 chore: rename config.yaml to config.yml for issue template
  .github/ISSUE_TEMPLATE/config.yml
Labels: hotfix

#16315 docs: update IdP group and role sync documentation for UI configuration
  docs/admin/users/idp-sync.md
  docs/images/admin/users/organizations/group-sync-empty.png
  docs/images/admin/users/organizations/group-sync.png
  docs/images/admin/users/organizations/role-sync-empty.png
  docs/images/admin/users/organizations/role-sync.png
  docs/images/admin/users/organizations/template-org-picker.png
  docs/images/admin/users/organizations/workspace-list.png
  docs/manifest.json
  docs/tutorials/best-practices/organizations.md
Labels: docs
