Repository coder/coder, pull requests merged in 2025-10, with the labels that each got.

#20150 fix(coderd): correct the name of the unmarshall error variable
  coderd/oauthpki/oidcpki.go
Labels: community

#19973 feat(cli): prompt for missing required template variables on template creation
  cli/templatepush.go
  cli/templatepush_test.go
  codersdk/provisionerdaemons.go
  codersdk/templatevariables.go
Labels: stale

#20205 docs: fix link to Grafana dashboard example for AI Bridge
  docs/ai-coder/ai-bridge.md
Labels: cherry-pick/2.27
