Repository coder/coder, pull requests merged in 2025-05, with the labels that each got.

#17628 fix: create directory before writing coder connect network info file
  cli/ssh.go
Labels: hotfix

#17655 docs: fix link in tutorials faq to new docker-code-server link
  docs/tutorials/faqs.md
Labels: docs, hotfix

#17663 fix: fix size for non-squared app icons
  site/src/modules/resources/AgentButton.tsx
  site/src/modules/resources/AppLink/AppLink.stories.tsx
Labels: hotfix

#17679 fix: fix windsurf icon on light theme
  site/src/modules/resources/AppLink/BaseIcon.tsx
  site/src/theme/externalImages.ts
Labels: hotfix

#17700 chore!: fix workspace apps response
  codersdk/workspaceapps.go
  site/src/api/typesGenerated.ts
  site/src/modules/resources/AgentRow.test.tsx
  site/src/modules/resources/AgentRowPreview.test.tsx
  site/src/modules/resources/AgentRowPreview.tsx
  site/src/modules/resources/AppLink/AppLink.tsx
  site/src/modules/workspaces/WorkspaceAppStatus/WorkspaceAppStatus.tsx
  site/src/pages/WorkspacePage/AppStatuses.tsx
  site/src/utils/apps.ts
Labels: release/breaking, hotfix

#17708 fix: fill session token when app is external
  site/src/modules/resources/AppLink/AppLink.tsx
Labels: hotfix

#17580 chore: add prebuild docs
  docs/admin/templates/extending-templates/prebuilt-workspaces.md
  docs/images/admin/templates/extend-templates/prebuilt/prebuilt-workspaces.png
  docs/images/admin/templates/extend-templates/prebuilt/replacement-notification.png
  docs/manifest.json
Labels: docs

#17726 chore: add keys for each app on workspaces table
  site/src/pages/WorkspacesPage/WorkspacesTable.tsx
Labels: hotfix

#17741 refactor: improve apps.ts readbility
  site/migrate-icons.md
  site/src/modules/apps/apps.ts
  site/src/modules/apps/useAppLink.ts
  site/src/modules/resources/AppLink/AppLink.tsx
Labels: hotfix

#17727 chore: fix :first-child warning
  site/src/components/InputGroup/InputGroup.tsx
  site/src/components/Markdown/Markdown.tsx
  site/src/components/Table/Table.tsx
  site/src/modules/resources/ResourceCard.tsx
  site/src/modules/workspaces/WorkspaceTiming/Chart/Chart.tsx
  site/src/modules/workspaces/WorkspaceTiming/Chart/XAxis.tsx
  site/src/modules/workspaces/WorkspaceTiming/Chart/YAxis.tsx
  site/src/pages/TemplatePage/TemplateInsightsPage/TemplateInsightsPage.tsx
  site/src/pages/WorkspacePage/WorkspaceNotifications/Notifications.tsx
Labels: hotfix

#17731 chore: replace MUI icons - 1
  site/src/components/BuildIcon/BuildIcon.tsx
  site/src/pages/TemplatePage/TemplatePageHeader.tsx
  site/src/pages/WorkspacePage/WorkspaceActions/WorkspaceActions.tsx
  site/src/pages/WorkspacesPage/WorkspacesPageView.tsx
  site/src/utils/workspace.tsx
Labels: hotfix

#17728 docs: clarify parameter autofill documentation
  docs/admin/templates/extending-templates/parameters.md
Labels: docs

#17742 refactor: add safe list for external app protocols
  site/src/modules/apps/apps.test.ts
  site/src/modules/apps/apps.ts
  site/src/modules/resources/AppLink/AppLink.stories.tsx
Labels: hotfix

#17732 chore: replace MUI icons - 2
  site/src/components/CopyButton/CopyButton.tsx
  site/src/components/DropdownArrow/DropdownArrow.tsx
  site/src/components/DurationField/DurationField.tsx
  site/src/components/Filter/Filter.tsx
  site/src/modules/resources/PortForwardButton.tsx
  site/src/modules/resources/SSHButton/SSHButton.tsx
  site/src/modules/workspaces/WorkspaceTiming/WorkspaceTimings.tsx
  site/src/pages/WorkspacesPage/WorkspacesPageView.tsx
  site/src/pages/WorkspacesPage/WorkspacesTable.tsx
Labels: hotfix

#17733 chore: replace MUI icons - 3
  site/src/components/Paywall/Paywall.tsx
  site/src/components/Paywall/PopoverPaywall.tsx
  site/src/components/Pill/Pill.stories.tsx
  site/src/modules/resources/AppLink/AppLink.tsx
  site/src/modules/workspaces/WorkspaceStatusBadge/WorkspaceStatusBadge.tsx
  site/src/pages/WorkspacePage/ChangeVersionDialog.tsx
  site/src/pages/WorkspacePage/WorkspaceNotifications/WorkspaceNotifications.tsx
  site/src/utils/workspace.tsx
Labels: hotfix

#17748 chore: replace MUI icons - 4
  site/src/components/FileUpload/FileUpload.tsx
  site/src/components/FullPageLayout/Topbar.tsx
  site/src/pages/GroupsPage/GroupPage.tsx
  site/src/pages/UserSettingsPage/TokensPage/TokensPageView.tsx
  site/src/pages/WorkspacePage/WorkspaceTopbar.tsx
Labels: hotfix

#17744 feat: display user apps in the workspaces table
  site/src/pages/WorkspacesPage/WorkspacesPageView.stories.tsx
  site/src/pages/WorkspacesPage/WorkspacesTable.tsx
  site/src/testHelpers/entities.ts
Labels: hotfix

#17751 chore: replace MUI icons - 6
  site/src/components/GlobalSnackbar/EnterpriseSnackbar.tsx
  site/src/modules/provisioners/ProvisionerTag.tsx
  site/src/modules/resources/PortForwardButton.tsx
  site/src/pages/CreateTemplatePage/BuildLogsDrawer.tsx
  site/src/pages/HealthPage/Content.tsx
  site/src/pages/TemplatePage/TemplateInsightsPage/TemplateInsightsPage.tsx
  site/src/pages/UserSettingsPage/SecurityPage/SingleSignOnSection.tsx
Labels: hotfix

#17563 docs: add note about experiment_report_tasks to ai-coder/create-template
  docs/ai-coder/create-template.md
Labels: docs

#17750 chore: replace MUI icons with Lucide icons - 5
  site/migrate-icons.md
  site/src/components/Filter/Filter.tsx
  site/src/components/HelpTooltip/HelpTooltip.tsx
  site/src/components/Latency/Latency.tsx
  site/src/components/RichParameterInput/RichParameterInput.tsx
  site/src/modules/dashboard/DeploymentBanner/DeploymentBannerView.tsx
  site/src/modules/resources/AgentOutdatedTooltip.tsx
  site/src/modules/resources/PortForwardButton.tsx
  site/src/modules/workspaces/WorkspaceOutdatedTooltip/WorkspaceOutdatedTooltip.tsx
  site/src/modules/workspaces/WorkspaceTiming/Chart/Tooltip.tsx
  site/src/pages/GroupsPage/GroupPage.tsx
  site/src/pages/HealthPage/Content.tsx
  site/src/pages/StarterTemplatePage/StarterTemplatePageView.tsx
  site/src/pages/TemplateVersionEditorPage/TemplateVersionStatusBadge.tsx
  site/src/pages/UserSettingsPage/TokensPage/TokensPageView.tsx
  site/src/pages/WorkspacePage/AppStatuses.tsx
  site/src/pages/WorkspaceSettingsPage/WorkspaceParametersPage/WorkspaceParametersPage.tsx
  site/src/pages/WorkspacesPage/WorkspacesButton.tsx
Labels: hotfix

#17774 fix: use monochrome zed icon
  site/src/theme/externalImages.ts
  site/static/icon/zed.svg
Labels: hotfix

#17773 chore: update alpine 3.21.2 => 3.21.3
  scripts/Dockerfile.base
Labels: dependencies

#17798 docs: add section on how to retrieve user list
  cli/testdata/coder_users_--help.golden
  cli/testdata/coder_users_create_--help.golden
  cli/testdata/coder_users_list_--help.golden
  cli/usercreate.go
  cli/userlist.go
  docs/admin/users/index.md
  docs/manifest.json
  docs/reference/cli/users.md
  docs/reference/cli/users_create.md
  docs/reference/cli/users_list.md
Labels: docs

#17463 docs: add file sync to coder desktop docs
  docs/images/user-guides/desktop/coder-desktop-file-sync-add.png
  docs/images/user-guides/desktop/coder-desktop-file-sync-conflicts-mouseover.png
  docs/images/user-guides/desktop/coder-desktop-file-sync-staging.png
  docs/images/user-guides/desktop/coder-desktop-file-sync-watching.png
  docs/images/user-guides/desktop/coder-desktop-file-sync.png
  docs/images/user-guides/desktop/coder-desktop-workspaces.png
  docs/manifest.json
  docs/user-guides/desktop/index.md
Labels: docs

#17854 docs: add dev containers to manifest.json
  docs/manifest.json
Labels: docs, hotfix

#17848 feat: add elixir icon
  site/src/theme/icons.json
  site/static/icon/elixir.svg
Labels: community

#17882 docs: add provisioner job state transition diagram
  docs/admin/provisioners/manage-provisioner-jobs.md
  docs/images/admin/provisioners/provisioner-jobs-status-flow.png
Labels: docs

#17653 docs: add new dynamic parameters information to parameters doc
  docs/admin/templates/extending-templates/parameters.md
Labels: docs

#17936 chore: add vsphere icon
  site/src/theme/icons.json
  site/static/icon/vsphere.svg
Labels: community

#17868 docs: rename external-auth heading in setup doc
  docs/admin/setup/index.md
  docs/manifest.json
Labels: docs

#17954 chore: fix autoversion script and update experiments/docs versions
  docs/install/kubernetes.md
  docs/install/releases/feature-stages.md
  scripts/release/docs_update_experiments.sh
Labels: docs/eng

#17661 docs: add jetbrains toolbox steps
  docs/user-guides/workspace-access/jetbrains/jetbrains-toolbox.md
Labels: docs

#17987 docs: add Bottlerocket section to rootless Podman
  docs/admin/templates/extending-templates/docker-in-workspaces.md
Labels: community

#17784 feat: add ConvertUserLoginType func to codersdk
  codersdk/users.go
Labels: community

#17769 docs: update the GitHub Auth section
  docs/admin/users/github-auth.md
Labels: docs

#18068 docs: separate coder desktop sections into install and use pages
  docs/manifest.json
  docs/user-guides/desktop/desktop-connect-sync.md
  docs/user-guides/desktop/index.md
Labels: docs
